### ISSUE TITLE
Cordova FB plugin (saw it on the forum but not tracked in github)

### ISSUE THREAD

**Issue by maxg7** [driftyco/ng-cordova#102]
It would be great to have the cordova fb plugin included in ngCordova. It's a pain to integrate, Conraets (http://coenraets.org/blog/2013/03/sociogram-mobile-a-starter-kit-application-for-phonegap-and-facebook-integration/) has a workaround but it's not native within the OS and instead forces the user to login through the browser.

**Comment by jsappme** [comment]
+1
