### ISSUE TITLE
Plugins not available after $ionicPlatform.ready

### ISSUE THREAD

**Issue by sgentile** [driftyco/ng-cordova#1028]
https://github.com/driftyco/ng-cordova/issues/860 seems to imply it would work, but it's not working for me:

```
angular.module('myApp', ['ionic', 'ngCordova', 'angular.filter'])
   .run(function (...) {
     $ionicPlatform.ready(function() {
                if ($window.cordova &&
                    $window.cordova.plugins) {
                    console.log('Plugin available');
                }
                else{
                    console.log('plugin NOT available')
                }
            });
});
```

the plugin is never available

I am trying to setup and configuration localnotifications on ready and $window.cordova is always undefined

**Comment by Ionitron** [comment]
Greetings @sgentile!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by shahroon** [comment]
I am having the same issue,

var wmcApp = angular.module('wmcApp', ['ionic','ionic.service.core',
  'wmcControllers',
  'wmcTruckMapController',
  'wmcDashboardController',
  'wmcFactories',
  'wmcTruckMapFactory',
  'wmcProductionDataFactory',
  'wmcDirectives',
  'ionic-timepicker',
  'ui.date','ngTouch','pusher-angular','ngCordova']);

wmcApp.run(function($ionicPlatform) {

    $ionicPlatform.ready(function() {
        console.log("window::::"+window); // Gives object
        console.log("window.cordova::::" + window.cordova); // Gives object
        console.log("window.cordova plugins::::" + window.cordova.plugins); // Gives Undefined
        console.log("window.StatusBar"+ window.StatusBar); //Gives Undefined
        if(window.cordova && window.cordova.plugins.Keyboard) { // App breaks here
            cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
        }
        if(window.StatusBar) {
            // org.apache.cordova.statusbar required
            StatusBar.styleDefault();
        }
        var push = new Ionic.Push({
            "debug": true
        });
        push.register(function(token) {
            alert(token.token);
            console.log("Device token:",token.token);
        });
  });
});

Recently started working on Push Notifications.
