### ISSUE TITLE
$cordovaDatePicker Issue

### ISSUE THREAD

**Issue by randdusing** [driftyco/ng-cordova#1047]
Not sure if this more of an issue of the actual plugin or with the wrapper. When I cancel/clear a datepicker box in iOS, the success function is called with a date value of null. When I cancel a datepicker box in Android, the success function is never called. It looks like Android uses the error function instead, but the $cordovaDatePicker only wraps the success function. Is this intended? It seems like the actual plugin should be more consistent with whether it uses the success or error callback.

Original
```javascript
show: function (options) {
	var q = $q.defer();
	options = options || {date: new Date(), mode: 'date'};
	$window.datePicker.show(options, function (date) {
		q.resolve(date);
	});
	return q.promise;
}
```

Modifications
```javascript
show: function (options) {
	var q = $q.defer();
	options = options || {date: new Date(), mode: 'date'};
	$window.datePicker.show(options, function (date) {
		q.resolve(date);
	}, function() {
		q.resolve(null);
	});
	return q.promise;
}
```

**Comment by gortok** [comment]
I believe this was resolved in our latest release.

https://github.com/driftyco/ng-cordova/releases/tag/v0.1.24-alpha
