### ISSUE TITLE
PushV5

### ISSUE THREAD

**Issue by tombeech** [driftyco/ng-cordova#1062]
Hi,

I've upgraded ngcordova to the latest version v0.1.21-alpha and i'm trying to use the new PushV5 stuff. However, whenever I add $cordovaPushV5 to my code code, it all falls over with a 

Error: [$injector:unpr] Unknown provider: $cordovaPushV5Provider <- $cordovaPushV5 <- globalCtrl
http://errors.angularjs.org/1.3.6/$injector/unpr?p0=%24cordovaPushV5Provider%20%3C-%20%24cordovaPushV5%20%3C-%20globalCtrl
    at ionic.bundle.js:7888
    at ionic.bundle.js:11806
    at Object.getService [as get] (ionic.bundle.js:11953)
    at ionic.bundle.js:11811
    at getService (ionic.bundle.js:11953)
    at Object.invoke (ionic.bundle.js:11985)
    at extend.instance (ionic.bundle.js:16247)
    at ionic.bundle.js:15502
    at forEach (ionic.bundle.js:8155)
    at nodeLinkFn (ionic.bundle.js:15501)

**Comment by root-io** [comment]
v0.1.22-alpha is the latest one :)

**Comment by tombeech** [comment]
Mmm so it is, (I think it still says 1.21 in the file itself though) - either way, that code was in 21 too and it still doesnt work unfortunately

**Comment by gortok** [comment]
The code wasn't in 1.21-alpha. That was a mistake on my part.

**Comment by tombeech** [comment]
Ah - Where can I find the right one, both https://github.com/driftyco/ng-cordova/blob/master/dist/ng-cordova.js and https://github.com/driftyco/ng-cordova/blob/dev-next/dist/ng-cordova.js state 1.21-alpha at the top of them?

**Comment by gortok** [comment]
That may be a build error on my part.

**Comment by gortok** [comment]
If you had pulled down the bower package for v0.1.22-alpha, you wouldn't have this issue; but by installing against master, you do.  This is my fault; I somehow didn't add the actual build for master. It's in there now.  Whenever possible, you either want to use a tagged release, or if you want to live on the edge, go for `dev-next`.

**Comment by victordas** [comment]
I still have this error 
```
 "devDependencies": {
    "ionic": "driftyco/ionic-bower#1.2.4"
  },
  "dependencies": {
    "ngCordova": "^0.1.24-alpha"
  }
```

**Comment by cinder92** [comment]
i'm having same issue 👍

**Comment by technotip** [comment]
Same issue for me too :(
