### ISSUE TITLE
window.resolveLocalFileSystemURL() callback not working

### ISSUE THREAD

**Issue by pixelvirus** [driftyco/ng-cordova#1067]
I'm using ngcordova camera (v0.1.23-alpha) and uploading the image to google drive.
Testing on android with ionic view and jsconsole.com for viewing console logs.

Below is my code, I only see in log 'got uri file:///storage/emulated/0/Android/data/com.ionic.viewapp/cache/1447714232041.jpg' and not 'trying to read file', so it never goes inside the function. 

I've seen previous issues such as this http://stackoverflow.com/questions/21980112/cordova-resolvelocalfilesystemurl-success-call-back-failing-on-ios 

Is there anything wrong with my image file path? Any help would be greatly appreciated!

       var options = {
               quality: 75,
               destinationType: Camera.DestinationType.FILE_URI,
               encodingType: Camera.EncodingType.JPEG,
               correctOrientation: true,
               saveToPhotoAlbum: false
             };
        
       $cordovaCamera.getPicture(options).then(function(uri) {

        console.log('got uri ' + uri);
        window.resolveLocalFileSystemURL(uri, function(fileEntry) {

          console.log('trying to read file');
          fileEntry.file(function(file) {
            
            console.log('file read');
            // (MediaUploader is this https://github.com/googledrive/cors-upload-sample)
            var uploader = new MediaUploader({
              file: file,
              token: access_token,
              onComplete: function(res) {
                console.log("Upload successful " + res);
              },
              onError: function(res) {
                console.log('Upload not successful ' + res);
              },
            });
            uploader.upload();

          }, function(err) {
            console.log(err);
          });
        }, function(err) {
          console.log(err);
        });
      }, function(err) {
        console.log(err);
      });

**Comment by krookten14** [comment]
Is there a solution to this now? please help. I'm really having troubles here.
