### ISSUE TITLE
AppRate is not defined

### ISSUE THREAD

**Issue by RalfGe81** [driftyco/ng-cordova#1081]
I use version 0.1.23-alpha. I got the error AppRate is not defined.

Here will throw the error

````
this.$get = ['$q', function ($q) {
      return {
        promptForRating: function (immediate) {
          var q = $q.defer();
          var prompt = AppRate.promptForRating(immediate); // here is thrown the error line 197
          q.resolve(prompt);

          return q.promise;
        },

        navigateToAppStore: function () {
          var q = $q.defer();
          var navigate = AppRate.navigateToAppStore();
          q.resolve(navigate);

          return q.promise;
        },

        onButtonClicked: function (cb) {
          AppRate.onButtonClicked = function (buttonIndex) {
            cb.call(this, buttonIndex);
          };
        },

        onRateDialogShow: function (cb) {
          AppRate.onRateDialogShow = cb();
        }
```

My code in config:
```javascript
.config(
    function ($cordovaAppRateProvider) {
        document.addEventListener("deviceready", function () {
            $cordovaAppRateProvider.setPreferences(
            {
                language: 'de',
                appName: 'Hausbau, Kredit & Ratenrechner',
                androidURL: 'market://details?id=de.ihritprojekt.BauKreditkostenkalkulator',
                usesUntilPrompt: 1
            }
          )
        }, false);
    }
)
```
My code in controller:

```
'use strict';
mainView.controller(
    'WelcomeController',
    [
        '$scope',
        '$cordovaAppRate',
        'gettextCatalog',
        function ($scope, $cordovaAppRate, gettextCatalog) {
            if (true === config.ratingOn) {
                document.addEventListener("deviceready", function () {
                    $cordovaAppRate.promptForRating(true).then(function (result) {
                        // success
                    });
                    $cordovaAppRate.navigateToAppStore().then(function (result) {
                        // success
                    });
                }, false);
            }
        }
    ]
);
```

**Comment by gortok** [comment]
Is this on the device or on the web? Also, can you provide me a link to a repo I can pull down and put on my device to reproduce this?

**Comment by RalfGe81** [comment]
I can send you a debug apk file

**Comment by gortok** [comment]
That won't really help; if you can make a sample project that reproduces the issue; that will help.

**Comment by RalfGe81** [comment]
okey, so i will do

2015-12-01 20:38 GMT+01:00 George Stocker <notifications@github.com>:

> That won't really help; if you can make a sample project that reproduces
> the issue; that will help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ng-cordova/issues/1081#issuecomment-161073015>
> .
>



-- 
Ralf Geisthardt
-Bachelor Professional of IT Systems Management-
Donaustr. 24

15827 Blankenfelde-Mahlow

Telefon: 0176/56563261
Email: RalfGe@gmail.com
Skype: RalfGe81
Xing: https://www.xing.com/profile/Ralf_Geisthardt
Webseite: http://www.ihr-it-projekt.de/
Google+: https://plus.google.com/u/0/+Ihr-it-projektDe/about

**Comment by RalfGe81** [comment]
in my demo app it works, so i will debug my main app... .

**Comment by gortok** [comment]
Alright; let me know if anything turns up.

**Comment by RalfGe81** [comment]
Thanks

**Comment by RalfGe81** [comment]
Okey i found the problem. It was an old cordova plugin:

WARNING: org.apache.cordova.globalization has been renamed to cordova-plugin-globalization. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.globalization` and `cordova plugin add cordova-plugin-globalization`.

**Comment by pushparajsamant** [comment]
Can someone please note down the steps needed to install this plugin. I installed the plugin correctly. But from there I am unable to inject the $appRateProvider plugin into my app.

**Comment by ihr-it-projekt** [comment]
What is you error message?

**Comment by pushparajsamant** [comment]
No worries. I figured out finally.  Actually the way we have used ng-cordova is a little different. Sorry about that.
