### ISSUE TITLE
Release Notes Not Updated

### ISSUE THREAD

**Issue by RangerRick** [driftyco/ng-cordova#1115]
CHANGELOG.md says: "Please refer to the [Github ngCordova Releases file](https://github.com/driftyco/ng-cordova/releases) for detailed information." but the releases have not had release notes since 0.1.17-alpha.

**Comment by gortok** [comment]
I knew I keep forgetting something.

**Comment by gortok** [comment]
This has been fixed; going forward we will include release notes.  Thanks for bringing this up.

https://github.com/driftyco/ng-cordova/releases/tag/v0.1.24-alpha
