### ISSUE TITLE
Remove Oauth

### ISSUE THREAD

**Issue by mirkonasato** [driftyco/ng-cordova#1117]
`ng-cordova` currently includes an old and [unsupported](https://github.com/driftyco/ng-cordova/issues/809#issuecomment-169162122) version of [ng-cordova-oauth](https://github.com/nraboy/ng-cordova-oauth).

This makes it impossible to use both `ng-cordova` and the latest, working version of `ng-cordova-oauth` in the same project.

**Comment by ignacio-chiazzo** [comment]
So, What is the solution for "Oauth Could not find inappbrowser" ????

**Comment by gortok** [comment]
This should be included in the next release.

**Comment by Manduro** [comment]
@gortok What is the ETA of the next release?

**Comment by gortok** [comment]
@manduro this week

**Comment by gortok** [comment]
@Manduro This has been released under v0.1.24-alpha.
