### ISSUE TITLE
How can I run the unit tests for ngCordova?

### ISSUE THREAD

**Issue by abcd-ca** [driftyco/ng-cordova#1122]
I’ve contributed to ngCordova​ and will create a pull request. How can I run the existing tests? If I can run those I’ll update the mocks & tests for my plugin changes too.

I’ve tried gulp karma and gulp karma-watch but these throw, Uncaught ReferenceError: angular is not defined. This is from a cloned copy of ngCordova, not integrated into a project.

**Comment by gortok** [comment]
```
git clone https://github.com/driftyco/ng-cordova.git
cd ng-cordova
npm install
bower install
gulp karma
```

If you get 'angular is not defined', it's because Angular is a bower dependency, so you have to run `bower install` before trying to run `gulp karma`.
