### ISSUE TITLE
Add progressIndicator $cordovaProgress Mock

### ISSUE THREAD

**Issue by leocaseiro** [driftyco/ng-cordova#1126]
I'd like to unit test some $cordovaProgress, that would be nice if had a Mock for it.

http://ngcordova.com/docs/plugins/progressIndicator/

**Comment by gortok** [comment]
Up for grabs. Feel free to create one and submit a PR against Dev-next to make it happen.

**Comment by leocaseiro** [comment]
I was wondering how would it work, should I create a HTML for it? Would be console enough? alert for show messages? so we could have e2e testing?
Any ideas?

**Comment by leocaseiro** [comment]
Is it good to go? Did you like it?

**Comment by leocaseiro** [comment]
????
