### ISSUE TITLE
Task 'git' is not in your gulpfile

### ISSUE THREAD

**Issue by toddhalfpenny** [driftyco/ng-cordova#1141]
I think this is a bug with the gulpfile where the _git_ task was removed (perhaps something to do with the submodule approach that was in use at one point).

The _default_ gulp task still refers to a _git_ task... is it OK to just remove this? If so I can create a PR.

If you run `gulp` then the default task runs with this output;

```
[11:10:17] Using gulpfile ~/projects/ng-cordova/gulpfile.js
[11:10:17] Task 'git' is not in your gulpfile
[11:10:17] Please check the documentation for proper gulpfile formatting
```

Issue is on line 20.
`gulp.task('default', ['git', 'build']);`

**Comment by gortok** [comment]
You're right. Go ahead and create the PR and target Dev-next
