### ISSUE TITLE
Use of reserved 'package' keyword

### ISSUE THREAD

**Issue by RangerRick** [driftyco/ng-cordova#1143]
I updated ngCordova recently, and now webpack  is failing for me with the following error:

```
ERROR in ./bower_components/ngCordova/dist/ng-cordova.js
Module parse failed: /Users/ranger/rcs/CruiseMonkey/node_modules/eslint-loader/index.js!/Users/ranger/rcs/CruiseMonkey/bower_components/ngCordova/dist/ng-cordova.js The keyword 'package' is reserved (243:55)
You may need an appropriate loader to handle this file type.
|       getPackageName: function () {
|         var q = $q.defer();
|         cordova.getAppVersion.getPackageName(function (package) {
|           q.resolve(package);
|         });
 @ multi vendor
```

getPackageName appears to be passing 'package' as the function argument name, and it is a reserved keyword in most ES standards.

**Comment by gortok** [comment]
http://stackoverflow.com/questions/8569303/javascript-package-is-a-reserved-keyword

Good find; could you submit a PR to resolve this issue? Please issue it to dev-next.

**Comment by Meekohi** [comment]
+1

**Comment by MHaendel** [comment]
+1

**Comment by Meekohi** [comment]
Pull request is at https://github.com/driftyco/ng-cordova/pull/1164

**Comment by Meekohi** [comment]
New pull request is at https://github.com/driftyco/ng-cordova/pull/1188
