### ISSUE TITLE
Plugin does not work, 'Native Audio' of undefined

### ISSUE THREAD

**Issue by ivanssa** [driftyco/ng-cordova#1147]
Hello I am more than a week trying to run audio on an unsuccessful app, I'm using the plugin did everything as described always get the error Uncaught TypeError: Can not read property 'NativeAudio' of undefined in the tests in the browser via ionic also serves tried in ios via the phonegap more also get an error undefined is not an object app (Evaluating '$ window.plugins.NativeAudio.play') and can not make it work can anyone help me?

**Comment by ivanssa** [comment]
Hello after so wait solved the problem to include audio in my app with only two lines below.

var audio = new Audio('audio/audio.mp3');
audio.play();

**Comment by kamal-adepu** [comment]
hii.. i m also facing same problem

**Comment by leason00** [comment]
hii.. i m also facing same problem

**Comment by ivanssa** [comment]
@kamal-adepu and @leason00 Hello, I gave the solution below, have you solved it?

**Comment by xke** [comment]
@ivanssa  Does the simple Audio solution work on the device for you? I was able to get the sound to play doing "ionic serve" but haven't yet been able to get it working on an Android device.

**Comment by ivent** [comment]
Hello, I'm using the html5 audio diffetives that worked perfectly on ios and android, and you can also use the media stream to make the launch of your audios check examples in the links below

Html5 http://jsfiddle.net/tabalinas/hNZ4y/
Cordovamedia https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-media/
