### ISSUE TITLE
Save rendered image using file API?

### ISSUE THREAD

**Issue by gigablox** [driftyco/ng-cordova#115]
This is more of a general question so forgive me if this is not the right place but how would I save an image that's rendered in the DOM?

For example:

    <img src="cordova.jpg" ng-click="saveMeViaFileAPI()"/>

I know downloading downloading a file from a URL is possible through the API just just wondering if there's a way to save a little bit more HTTP traffic :)

**Comment by aneeshmg** [comment]
You would have to render the images in a canvas as shown [here](http://www.html5canvastutorials.com/advanced/html5-canvas-load-image-data-url/) and then use [this](http://phonegap-plugins.com/plugins/devgeeks/canvas2imageplugin) plugin for cordova
