### ISSUE TITLE
$cordovaMedia.getDuration() and .getCurrentPosition()

### ISSUE THREAD

**Issue by will-ockmore** [driftyco/ng-cordova#1198]
On the [docs](http://ngcordova.com/docs/plugins/media/) these are listed as "not working", just wondering if they are being fixed or on hold? If they are being fixed, any ETA on when they will be up and working?

Thanks!

**Comment by gortok** [comment]
If you want to take a stab at fixing them, it'd help. And it would put the open in open source. And the great in grateful.

**Comment by will-ockmore** [comment]
Apologies if the original message came off wrong - clearly hadn't done my research on the subject. Was about to open a PR yesterday but then I saw there already is one for this issue - https://github.com/driftyco/ng-cordova/pull/1165. Would be happy to open a duplicate later today with the dist files removed if that's helpful at all

**Comment by gortok** [comment]
@will-ockmore thsts definitely Helpful.

**Comment by will-ockmore** [comment]
All done - up on https://github.com/driftyco/ng-cordova/pull/1211
