### ISSUE TITLE
Problem with iFrame and link

### ISSUE THREAD

**Issue by ibnbd** [driftyco/ng-cordova#1219]
Hey there guys,

I am developing an ionic app, where I will show some html content from my SQLite database. I tried to show those content on a div using `$sce.trustAsHtml` problem is CSS style within those content affecting whole app. Like app header, navigation changed. I have been searching for a solution everywhere and found a working idea using jQuery. So I created a `iframe` tag and pushing those content using `jQuery.html()`. It works fine just as I wanted, those content showing perfect without affecting app style.

Now the problem is all links within iframe opens inside iframe. Then I used `target="_blank"`  on my anchor tag. Now links opening on blank page but in app. Means my app interface change with link. I used inappborwser, which  actually doesn't work for iframe. I want those links to open in system browser, not in my app.

Anyone knows, how to trigger all links within the iframe to open in system browser?

Thank you

**Comment by wicktus** [comment]
That's weird try maybe :
**<base target="_parent" />**. Normally this should open the link in the parent which is the system browser.

Tell me how it goes :).

**Comment by ibnbd** [comment]
working same as _blank :(

**Comment by ibnbd** [comment]
@mhartington @mlynch @bensperry any kind of help please.

**Comment by wicktus** [comment]
With the InAppBrowser Plugin installed, try replacing href by an
`onclick="window.open('MyLink.com', '_system')"`

If you can't do that directly in your Iframe, then you could figure a way to trigger a window.open in your app each time someone clicks a link in your iframe.

I'm afraid other solutions are really difficult because InAppBrowser and Iframe don't get along really well.

**Comment by mhartington** [comment]
Hi there! So using an iFrame is probably not the correct solution. 

The problem with links in the iFrame stems from the fact that it's an entire separate context. It does not have cordova injected into it, it doesn't load angular. iFrames have completely isolated context from the parent html that loads them. 

You're best solution is to use the `trustAsHtml` method and figure out the issues on the contents styling.

**Comment by ibnbd** [comment]
@wicktus thank you for your replay, I tried replacing href with onclick event and nothing happens.
@mhartington thank you for your replay too, my app kind of email service, not totally consumer email like Gmail. As I mentioned earlier when I am pushing those content on a div with trustAsHtml. It's changes all content of app (Header, Navigation Fonts). I came so far with ionic, now this is the only thing I am stuck with. Please if you can suggest something else would save my day.

Thank You

**Comment by ipehimanshu** [comment]
any solutions 
I am trying to add embedded twitter timeline and here issue is when user click on that iframe tweet it hide current app web view and open twitter url, so fully weird things happen,
Any one have solution, 
Thanks
