### ISSUE TITLE
Docs for the new Push Plugin

### ISSUE THREAD

**Issue by James-Parsons** [driftyco/ng-cordova#1242]
The documentation [here](http://ngcordova.com/docs/plugins/pushNotifications/) is using the old push plugin. Are there any docs for using the new one under ngCordova? Are the wrappers essentially the same?

**Comment by bondeulv** [comment]
If you look in the ng-cordova.js file, I believe you'll find the cordovaPushV5 service (line 6214), which corresponds to the  "new" plugin.
I haven't been able to make it work yet though.

**Comment by gortok** [comment]
Thanks!
