### ISSUE TITLE
$cordovaDatePicker: Assigned options not working/reflecting to native date picker.

### ISSUE THREAD

**Issue by albertonaperijr** [driftyco/ng-cordova#1257]
Hi,

Assigning options to ```$cordovaDatePicker``` is not reflecting to native date picker.
Also, after selecting a date and then opening again the native date picker it always show the current date not the last selected date.

Thanks.

**Comment by gortok** [comment]
@albertonaperijr I need you to provide a minimal, complete, verifiable example so I can help you. Include what models of phone you've tested this on as well. If you have a github repo that reproduces this issue that I can build and run, that will also work. http://stackoverflow.com/help/mcve
