### ISSUE TITLE
Cordova Toast, showWithOptions() method seems to be missing from NgCordova

### ISSUE THREAD

**Issue by AlDrag** [driftyco/ng-cordova#1272]

**Comment by ledfusion** [comment]
I have proposed a pull request with a new wrapper for showWithOptions: https://github.com/driftyco/ng-cordova/pull/1273

**Comment by gortok** [comment]
It's in `dev-next`, and will be in master during the next release, which will be next week.
https://github.com/driftyco/ng-cordova/blob/dev-next/src/plugins/toast.js#L69
