### ISSUE TITLE
PR #1231 still not in alpha, also Content of /dist is outdated

### ISSUE THREAD

**Issue by MatthieuMB** [driftyco/ng-cordova#1283]
I want to update my version of ng-cordova so that I can profit of this PR #1231 unfortunately this commit is still on the dev-next branch. 

That isn't a problem in itself, since I can still add '"ngCordova": "dev-next"' to my bower.json. But if bower pull the git from this branch, the content of ./dist (ng-cordova-mocks.js) doesn't include the changes from this PR! Bower also don't include source file so I can't add a task in gulp to build it.

The code changes in this PR are trivial, but important in order to not breaks unit tests, and yet they are:
- still not in any alpha release
- not built in ./dist

I don't have any other choice than to git clone outside of my project, build it and copy the ng-cordova-mocks.js which is ridiculously complicated for an update this trivial.

**Comment by gortok** [comment]
You're right; that's not trivial. 

There are a few possible solutions:

 - "Build" dev-next in a nightly fashion (on our end);
 - more frequent releases (I tend not to do that because I want to give time for people to test out differences
- going back to asking PRs to build and merge in ./dist (a nightmare for contributors, and a nightmare to merge back into master).

**Comment by gortok** [comment]
do you see any other ways of handling it?

**Comment by MatthieuMB** [comment]
A "nightly" git branch with a ./dist updated to the last dev-next would be perfect.
Or some kind of pre-alpha that would be released more often.

**Comment by gortok** [comment]
I just released v0.1.27-alpha; so that should solve your immediate issue; and we'll work on doing both.

Thanks for bringing this up, @MatthieuMB

**Comment by MatthieuMB** [comment]
Thank you very much. I really appreciate it.
