### ISSUE TITLE
Can't run ngCordova on iOS3 with Ionic

### ISSUE THREAD

**Issue by moneytree-doug** [driftyco/ng-cordova#1294]
Running
```bash
ionic emulate ios -lc
```
and getting the following error.

```
 error    TypeError: undefined is not an object (evaluating 'ref.addEventListener'), http://10.0.1.25:8100/lib/ngCordova/dist/ng-cordova.js, Line: 4709
```

However, when running it in the browser with ``ionic serve`` then it works fine.

The reason for using iOS3 is because I am running to tons of issues using iOS4 with livereload and splash screen infinitely loading.

**Comment by Sparksx** [comment]
Ios 3 ? really ?

[https://david-smith.org/iosversionstats/](https://david-smith.org/iosversionstats/)

nobody use ios 3...

**Comment by gortok** [comment]
Ionic is not compatible with iOS3; therefore ngCordova is not compatible with iOS3.
