### ISSUE TITLE
readFile and applicationDirectory

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ng-cordova#130]
I'm trying to port a demo (will be on Github soon and can push quicker if need be) that demonstrates reading from cordova.file.applicationDirectory. My existing code looks like so:

	window.resolveLocalFileSystemURL(cordova.file.applicationDirectory + "www/index.html", gotFile, fail);

In gotFile I simply call .file on the entry object then make a reader. This is failing when using $cordovaFile.readFile. I keep getting error code 5.

**Comment by pbernasconi** [comment]
The file plugin has been updated to use `resolveLocalFileSystemURL` (in the master). Docs show changes too. Hopefully that fixes your issues.
