### ISSUE TITLE
$cordovaGeolocation doesn't work on iOS 10

### ISSUE THREAD

**Issue by cballock** [driftyco/ng-cordova#1359]
Hi, guys.
I have an Ionic app that uses cordova Geolocation plugin to watch my device position.
When I run my app in Ionic View, everything works fine. But if I try to deploy the same app with XCode in my iPhone 6 (iOS 10), I cannot get any GPS position.
Any ideas?
Thanks and regards!

**Comment by cballock** [comment]
Investigating further I've found that the problem is that $ionicPlatform.ready() is not being called in iOS 10.

**Comment by MarcusXie** [comment]
So how to solve this problem? thanks.

**Comment by gortok** [comment]
@MarcusXie You have to provide a working reproduction for me to see the issue.  I can't really guess. :-/
