### ISSUE TITLE
$cordovaCamera - exposed beyond app through ClipData.Item.getUri()

### ISSUE THREAD

**Issue by TrueGeek** [driftyco/ng-cordova#1381]
I've attempting to take a photo with $cordovaCamera using this code:

`$cordovaCamera.getPicture(
            {
                destinationType: Camera.DestinationType.DATA_URL,
                encodingType: Camera.EncodingType.JPEG,
                mediaType: Camera.MediaType.PICTURE,
                sourceType: 1,
                saveToPhotoAlbum: false,
                correctOrientation: true
            }
        )`

This works fine on iOS and it works fine on Adroid when I change the source type to use the photo library.

But for Android with the source type of Camera it gives the error:

`file:///data/user/0/com.app.name/.android/cache/Capture.jpg exposed beyond app through ClipData.Item.getUri()`

This worked before, I think two weeks ago was the last time I tested it and we haven't changed the code since. I'm guessing if anything changed it's the Android SDK but it's odd that it works for existing photos and not new photos.

Does anyone have a fix for this?

**Comment by joewoodhouse** [comment]
I'm also seeing the same issue on Android 7.0. I suspect it's nothing to do with ng-cordova itself as I'm seeing it using ionic-native - so the problem is probably due to the camera plugin itself?

**Comment by naveedahmed1** [comment]
Any update on this?

**Comment by boyboi86** [comment]
Same here. I googled the error and found this [Stackoverflow](http://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed)

I thought it was something to do with android SDK 24. But I have no idea what it means. Can someone explain a little bit?

**Comment by naveedahmed1** [comment]
For Ionic team: please have a look at https://github.com/MLSDev/RxImagePicker/issues/13 may be it can help in fixing this.

**Comment by fhackenb** [comment]
Any update on this? I'm having the same issue using $cordovaCamera on a google pixel running android 7.1 and targetSdk 24. It seems to be working fine on all android devices below 7.0

**Comment by joewoodhouse** [comment]
For me I resolved this by updating to the latest version of the camera plugin (2.3.1) and by updating my cordova-android platform to 6.1.0.

Particularly I think this fix might be related: https://issues.apache.org/jira/browse/CB-11625

**Comment by fhackenb** [comment]
Upgrading to 2.3.1 (from 2.3.0) worked for me as well, thanks!. I did have to explicitly install 2.3.1 though - simply doing cordova plugin add cordova-plugin-camera installed version 2.3.2-dev which would not build

**Comment by guerson** [comment]
@joewoodhouse thank you.
The problem was only for android.

I just had to update the camera plugin version from 2.0.0 to 2.3.1
Now, it works on my nexus5, nexus5x and nexus6p. 

I have to test this version on IOS.

**Comment by TrueGeek** [comment]
I updated to 2.3.1, removed and re-added the Android platform, and confirmed that the plugin is indeed at 2.3.1 now. I'm on the latest version of Cordova (6.4.0) and my Android SDK 24 build tools are up to date but I'm getting the follow error when I try to build. If I bring the plugin version down to 2.3.0 the error goes away but, of course, the bug is still there.

I see someone else on StackOverflow getting this error and they were just told to bring the plugin down to v1:
http://stackoverflow.com/questions/41451100/android-build-error-upon-upgrading-cordova-camera-plugin

Anyone else seeing this after updating?

Error follows:

Error: cmd: Command failed with exit code 1 Error output:
C:\{projectpath}\platforms\android\src\org\apache\cordova\camera\CameraLauncher.java:32: error: cannot find symbol
import org.apache.cordova.BuildHelper;
                         ^
  symbol:   class BuildHelper
  location: package org.apache.cordova
C:\{projectpath}\platforms\android\src\org\apache\cordova\camera\CameraLauncher.java:140: error: cannot find symbol
        this.applicationId = (String) BuildHelper.getBuildConfigValue(cordova.getActivity(), "APPLICATION_ID");
                                      ^
  symbol:   variable BuildHelper
  location: class CameraLauncher
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

**Comment by mpk2** [comment]
I still have this issue with 2.3.1 on Nexus 5X, Android 7.1.1

**Comment by TrueGeek** [comment]
I was able to fix this. The solution has been added to the SO question in the link in my last post. The cordova-plugin-compat plugin needs to be updated:

```
cordova plugin remove cordova-plugin-compat --force
cordova plugin add cordova-plugin-compat
```

**Comment by mahlijah** [comment]
have same issue here , this solution is working for me

**Comment by nanmu42** [comment]
Thanks bro, you saved my day! 😄
