### ISSUE TITLE
Updated file Wrapper

### ISSUE THREAD

**Issue by evanshortiss** [driftyco/ng-cordova#141]
How would people feel about adding [this wrapper](https://github.com/evanshortiss/fs-browserify) for the file system plugin? It would support make development easier as it transparently supports multiple variations of the webkit file system and Cordova plugin so local development is easier.

Naturally this would require setting this as a dependency via the package.json. It may even be beneficial to browserify the ng-cordova project following a similar style to [this](https://github.com/evanshortiss/cordova-angular-browserify) as it would enable the use of some handy node modules?

**Comment by pbernasconi** [comment]
I preferred the idea of abstracting the file-transfer plugin from the file plugin so I've done it recently and will be available in v0.1.11-alpha. See 11717fcfb02a3779836c5350cb45d76cbbfcf995

Also we're working on improving the File plugin to be more robust and option-friendly, more soon.
