### ISSUE TITLE
ngCordova should not be abandoned

### ISSUE THREAD

**Issue by jsuiker** [driftyco/ng-cordova#1454]
ngCordova stands on its own apart from ionic. It does not make sense to abandon this project unless the ionic-native package is capable of meeting the same needs as ngCordova (ie providing angularjs apps a quick and reliable api for cordova functionality)

@mlynch 
@gortok 
@ihadeed

**Comment by mlynch** [comment]
Thanks, you can continue to use ngCordova and the docs are still available here: http://ngcordova.com/docs/

Ionic Native is a sufficient replacement with a very similar API. Use version 2.9.0 and see the instructions here for Angular usage: https://github.com/ionic-team/ionic-native/tree/v2.9.0#angular-1

The next release of Ionic Native, version 5, will have further improvements to the API and be more usable across frameworks.
