### ISSUE TITLE
TypeScript definition support

### ISSUE THREAD

**Issue by gautamsi** [driftyco/ng-cordova#148]
any plans to provide TypeScript definition file?

**Comment by scokmen** [comment]
That would be great. Typescript is very popular in angularjs word

**Comment by Zorgatone** [comment]
I need this...
It's not available in DefinitelyTyped's repo

**Comment by gortok** [comment]
This sounds like a great idea! Feel free to take a stab at it. If you get going and run into issues that you need help with, feel free to open an issue. http://definitelytyped.org/guides/contributing.html

**Comment by Zorgatone** [comment]
I was learning TypeScript.. I'm not quite ready to write type definitions xD
But if I will write them in the future, I will let you know

**Comment by MarkAurit** [comment]
Is that what this is?
https://github.com/mvidailhet/ngcordova-typescript-definitions/blob/master/typings/ngcordova/ngcordova.d.ts
