### ISSUE TITLE
Custom build - mismatch in module / dependency name?

### ISSUE THREAD

**Issue by stefek99** [driftyco/ng-cordova#166]
Video: https://www.youtube.com/watch?v=fULX5ILmMfQ [58 seconds]

Snippet from my custom build:

```
angular.module('ngCordova', [
  'ngCordova.plugins'
]);
angular.module('ngCordova.plugins.barcodeScanner', [])
```

'ngCordova.plugins' doesn't match 'ngCordova.plugins.barcodeScanner'

Bug / feature / or maybe it is documented somewhere?

**Comment by cfjedimaster** [comment]
This is still an issue. I see #348 was closed, but I just ran into this now. Please consider reopening it and addressing it.
