### ISSUE TITLE
App hangs on white screen after adding 'ngCordova'

### ISSUE THREAD

**Issue by kevbaker** [driftyco/ng-cordova#172]
I added the `ng-cordova.js` file to my index.html before the `cordova.js` file.

I then added `ngCordova` to my module:

```
var app = angular.module('app', ['ionic', 'app.controllers', 'ngCordova'])
```

When I `ionic run ios` my app and then open it, I see the splash screen and then it hangs on a white screen.

Any thoughts?

**Comment by hbmartin** [comment]
@pbernasconi  I have my plugins ordered as ionic.bundle.js, ng-cordova.js, cordova.js (in <head>) but am still having this issue

**Comment by pepetox** [comment]
I only have this problem in android 2.3.6, with 5.1 works fine but....

Any solution?

**Comment by bastiantowers** [comment]
Same here.
Maybe is there something about the Android API Version?
I saw that on Android 4, the API Version is 22; but on Android 2.3.6 the minimium version required is 10. Does anyone see a solution here?

Thanks!!

**Comment by maikokuppe** [comment]
had the same problem and solved it by changing the js implementation path:
    <script src="lib/ngCordova/dist/ng-cordova.min.js"></script>

**Comment by sundaywork** [comment]
Silly but I found out I misspelled cordova

**Comment by ebruner** [comment]
Same prob.  Here.  My app was running fine in chromium (ionic serve --lab).
Ionic 1.5.0
npm 1.3.10
Linux Mint 17

using:
<script src="lib/js/ionic.bundle.js"></script>
<script src="lib/ngCordova/dist/ng-cordova.js"></script>
<script src="cordova.js"></script>

**Comment by atulrungta** [comment]
Solved this error by updating ngCordova to latest stable version.

**Comment by sylfree9999** [comment]
I bumped into the same situation before. You should use bower to install the ngCordova like http://ngcordova.com/docs/plugins/contacts/, after installing, you will find the min.js is under some lib/ngCordova/dist file. Remember to reference it before cordova.js and after angular.js. Good luck!

**Comment by smajl** [comment]
Don't make the same mistake as me: make sure you use `bower install ngCordova` NOT! `bower install ng-cordova`

**Comment by ambrosiorafa** [comment]
Hey, Thanks a lot **maikokuppe**!
You solved my problem!

**Comment by PterPmnta** [comment]
@maikokuppe you solved my problem, was making the mistake of writing ng - Cordova

**Comment by motoitanigaki** [comment]
@maikokuppe  Thanks, you helped me a lot. 
I also needed to be careful to put `<script src="lib/ngCordova/dist/ng-cordova.min.js"></script>` before cordova.js and after ionic in index.html.

**Comment by armankarimi** [comment]
@motoitanigaki Thanks!
This was my problem all along: "I also needed to be careful to put <script src="lib/ngCordova/dist/ng-cordova.min.js"></script> before cordova.js and after ionic in index.html."
