### ISSUE TITLE
checking if plugin is active

### ISSUE THREAD

**Issue by michelhabib** [driftyco/ng-cordova#228]
it is very useful to check if the plugin is correctly installed before trying to use it.
for this purpose, i created a method isActive inside each one of the plugins that i am using.

``` javascript
    isActive: function() {
        if (navigator.splashscreen) return true;
        else return false;
    },
```

this can be very handy in the code, where at the application startup, one can do a check for all of the plugins before using them

``` javascript
        if (!$cordovaSplashscreen.isActive()) {
            inactivePlugins += "$cordovaSplashscreen,";
        }       
```

i could do this for almost all plugins i am using except for console, which doesn't have/need a plugin.
i also had a problem identifying if InAppBrowser plugin is installed, but that may be out of scope for ngCordova, since it does not need an angular wrapper like the rest of them.

one final note, also we need to check for window.cordova, many plugins depend on this check or they would create errors.

``` javascript
        if (!window.cordova) {          
            console.log("Error: Cordova is not loaded!");
            // Do not check the rest, since some plugins depend on window.cordova
            return false;
        }
```

i put that in my code, but couldnt find a way to include it in ngCordova.

Hope you consider my suggestions in a future update

**Comment by tallcoder** [comment]
Has anything happened with this? I'm looking for that exact functionality and having problems finding it.
