### ISSUE TITLE
File - storage location

### ISSUE THREAD

**Issue by ScreenDriver** [driftyco/ng-cordova#259]
Can I change the storage location in $cordovaFile like documented in the [official docs](https://github.com/apache/cordova-plugin-file/blob/master/doc/index.md#where-to-store-files) of cordova file plugin? I want to store / read all my files in cordova.file.dataDirectory.

**Comment by pbernasconi** [comment]
The file plugin has been updated to use resolveLocalFileSystemURL (in the master), so read/write/copy/move methods can use the various FileSystem `cordova.file.*` objects. Docs show changes too. Hopefully that fixes your issues.

**Comment by pritish5** [comment]
can any one reply this thread.
https://forum.ionicframework.com/t/cordova-file-datadirectory-not-creating-file-inside-the-app-folder/76471
