### ISSUE TITLE
local notification onclick not working, am I doing something wrong?

### ISSUE THREAD

**Issue by Freundschaft** [driftyco/ng-cordova#310]
Hey there,

thanks for this excellent plugin! I am trying to use
http://ngcordova.com/docs/#LocalNotification
the wrapper for local notifications

In my app I am trying to do:

```javascript
    .controller('SocialCtrl', function($scope, $state, $cordovaLocalNotification){
        $scope.StartScan = function(){
			var now                  = new Date().getTime(),
			_2_seconds_from_now = new Date(now + 2*1000);
			
			$cordovaLocalNotification.add({
				id:      'social',
				title:   'LTE Radar',
				message: 'Social Contacts discovered',
				date:    _2_seconds_from_now,
			});

			$cordovaLocalNotification.onclick = function (id, state, json) {
				$state.go('social_discovered');
			};
        };
        $scope.StopScan = function(){
            $state.go('social');
        };
    })
```

And the notification appears without any issues, but the onclick event never fires. When I click on the notification, the application comes back from background, but the event handler is not fired.
I have tried debugging with console.log but also no luck. It seems that the onclick function is never invoked. 

Am I doing something wrong?

Thanks & Best Regards
Freundschaft

**Comment by danda1man** [comment]
@rbecheras this needs to be reopened, an update must have overridden the fix
