### ISSUE TITLE
$cordovaFile.removeFile() leaves dangling promise if file doesn't exist

### ISSUE THREAD

**Issue by SpenceDiNicolantonio** [driftyco/ng-cordova#319]
When you call $cordovaFile.removeFile() with the path of a non-existent file, the returned promise is never resolved or rejected. Because the file doesn't exist, the underlying getFile() call fails and there is no failure callback specified.

**Comment by pbernasconi** [comment]
The File plugin has been overhauled. See the docs for more info, but it's much more expandable now.
