### ISSUE TITLE
createFile function with error code 5

### ISSUE THREAD

**Issue by angelocala94** [driftyco/ng-cordova#362]
``` javascript
document.addEventListener("deviceready", init, false);

function init() {
    var path=cordova.file.externalDataDirectory+'this_is_a_file';
    $cordovaFile.createFile(path, false).then(function(result) {
        console.log(JSON.stringify(result))
    }, function(err) {
        console.log(JSON.stringify(err));
    });
}
```

Every time i run this, it returns me an error with {"code":5} that is ENCODING_ERR.
What am I doing wrong?

**Comment by matthiaslieb** [comment]
Now you save it to the directory ```'this_is_a_file'``` but I think that is what you don't want. I have the same issue and I solved it with the elimination of the ```file:///''' prefix of ```cordova.file.externalDataDirectory```

**Comment by cometnice** [comment]
I have a problem here is my code please help me...

  showProducts(brand){
	this.common.showLoading().then((response) => {
		this.products = [];
		this.data.products[brand].filter(item => {
			File.readAsDataURL(this.directory, item.image).then((data) => {
				if(item.brand_name==brand){
					item.image = data;
					this.products.push(item);
				}
			});
		});
		this.common.hideLoading();
	});
  }

When i show the product for first time its working fine but when call again showProducts with same parameter it gives me error Error: Uncaught (in promise): [object Object] at s
Please help me. Thanks in advance
