### ISSUE TITLE
serve with Camera

### ISSUE THREAD

**Issue by janober** [driftyco/ng-cordova#373]
I am currently playing around with "ionic serve". Wanted to simply try the camera example from:
http://ngcordova.com/docs/#Camera
However when I try it on my phone with the PhoneGap-App I get the error "ReferenceError: Camera is not defined" every time I call the "takePicture" function .
It complains about the "Camera.DestinationType.DATA_URL" (and obviously all the other ones).

Is it not supposed to work with "serve" or am I missing something. Thanks!

**Comment by rajarajan09** [comment]
Yes you can't use cordova plugin if you need to run emulator it's working fine
