### ISSUE TITLE
Google Analytics functions fail unless they are forced to wait for device_ready

### ISSUE THREAD

**Issue by paishin** [driftyco/ng-cordova#395]
I am using Ionic and I have added the tracking code in my landing page controller. The code fails to run the first time the app opens because device_ready has not yet fired when controller runs. Navigating to another screen and comming back works fine.

Including the tracking code in $ionicPlatform.ready() fixes the error so this leads me to believe that when the cod run the plugin was not ready yet. My app incorporates deep linking and it doesn't seem right to me to have to include all tracking code in $ionicPlatform.ready() in every controller.

Is this how it is suppose to work?

**Comment by 0reo** [comment]
yes
http://ngcordova.com/docs/common-issues/
