### ISSUE TITLE
ReferenceError: LocalFileSystem is not defined

### ISSUE THREAD

**Issue by nekulin** [driftyco/ng-cordova#397]
app.js

	.run(function($ionicPlatform, $cordovaFile) {
	  $ionicPlatform.ready(function() {
	      $cordovaFile.checkFile('dataDirectory').then(function(result) {
		  console.log('user - ok');
	      }, function(err) {
		  console.log('user - error');
	      });
	    // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
	})

Error
ReferenceError: LocalFileSystem is not defined

**Comment by ranrolls** [comment]
I am not even able to use the core $cordovaFile functions.
Can u help
Thanks in advance

greatwebist@outlook.com

**Comment by MichaelJCole** [comment]
Do you have them in a 'ready' event?

E.g.

      $ionicPlatform.ready(function() {
        $scope.audioFile = Audio.openFile($scope.slug);
      });
