### ISSUE TITLE
$cordovaBackgroundGeolocation.configure() resolves a single promise multiple times

### ISSUE THREAD

**Issue by gordonpmurphy** [driftyco/ng-cordova#403]
$cordovaBackgroundGeolocation.configure() returns a promise that is resolved each time the location is updated in the background.  This means that ony the first background location update is processed through ngCordova $q will only resolve a promise once.

This should function like $cordovaGeolocation.watchPosition, where promises are .notify()'d of new positions.

**Comment by LuisMRibeiro** [comment]
Did you think that this could origin https://github.com/driftyco/ng-cordova/issues/485, because it is happening to me. 
Any fix?

Thanks.

**Comment by pbernasconi** [comment]
This should be fixed in 86d22e61723581226443ebfb9a12142c87ee1ffe

File ref:  https://github.com/driftyco/ng-cordova/blob/master/src/plugins/backgroundGeolocation.js#L23
