### ISSUE TITLE
ngCordova Local Notifications need Permission

### ISSUE THREAD

**Issue by yourbuddyconner** [driftyco/ng-cordova#419]
I've been putzing around with ngCordova/ionic recently, and I haven't been able to get the Local Notification plugin to work. 

I've got this controller doing ngCordova stuff: 

```
.controller('EventsCtrl', function($scope, $ionicPlatform, $cordovaLocalNotification, $cordovaDialogs) {
    $scope.setReminder = function() {
        $ionicPlatform.ready(function () {
            console.log("ready!"); // This fires
            $cordovaLocalNotification.add({
                message: "You yolo just like I yolo."
            });
        });
    };
    $scope.beep = function() {
        $ionicPlatform.ready(function(){
            $cordovaDialogs.beep(3);
        });
    };
})
```

I've got a button in this controller's view that calls $scope.setReminder() onClick, but in the logs I get an error: ```Attempting to schedule a local notification {...} with an alert but haven't received permission from the user to display alerts``` 

I've gotten other plugins to work, (like cordovaDialogs) but not this one... Any ideas?

**Comment by gortok** [comment]
closing; will re-open if this is reproduced.
