### ISSUE TITLE
ngCordova File : Unable to Create folder in sdcard or internal memory of device

### ISSUE THREAD

**Issue by kapilkarda** [driftyco/ng-cordova#422]
Hello,

I am new in ngCordova Ionic can you help me for that i implement an application in ionic in which i have to create folder of the application name and store server images into the device . 
please give me some example for that.

Thanks in Advance.

**Comment by gortok** [comment]
Could you include a minimal reproduction of the issue you're having? I'll be happy to re-open this once you do that.
