### ISSUE TITLE
Network information plugin is broken

### ISSUE THREAD

**Issue by bend0303** [driftyco/ng-cordova#443]
Using cordova 3.7 and ng-cordova with newest version and looks like the network-information service is broken?

When using $cordovaNetwork.isOnline()
Error: undefined is not an object (evaluating 'navigator.connection.type')
isOnline@file:///***/ngCordova/dist/ng-cordova.js:2058:48

It seems like the HTML NetworkAPI is experimental. is that mean the ngcordovaNetwork is as well?

**Comment by Namdnitbk92** [comment]
i have same problem,Please help me

**Comment by Namdnitbk92** [comment]
i've test on device ,but $cordovaNetwork.isOnline() is not working....

**Comment by konstantinkrassmann** [comment]
```
 $rootScope.$on('$cordovaNetwork:online', function(event, networkState){       
        console.info("Turned online");
    });
```

Does never trigger. Doesnt matter of my phone has connection or not.
