### ISSUE TITLE
make network.js function return more browser friendly objects

### ISSUE THREAD

**Issue by redhot358** [driftyco/ng-cordova#444]
Dear ng-cordova team

Keeping with the aim of ng-cordova ("make it easier to build, test, and deploy Cordova apps with AngularJS") please can you make the network.js functions return browser friendly objects. 

I find this will be useful when switching between the app and the browser versions of apps, especially when testing network connectivity issues on specific pages.

If there is another way of testing this please let me know OR if other developers have found simpler mechanisms please share with the wider developer community.

Thanks

**Comment by pbernasconi** [comment]
Closing this as I couldn't find any concrete API for network information as stale issue.
