### ISSUE TITLE
Odd behavior after back button pressed...  Failed to load resource... ng-cordova_plugins.js

### ISSUE THREAD

**Issue by jecourtney** [driftyco/ng-cordova#468]
Hello,

(This happens in emulators and on actual Android devices!)

I'm having a strange problem. When the app initially loads, there are no errors and the plugin for local-notification works splendidly! However, after I press the back button (app is still in memory) and then tap the app again, the app fails to find the plugin. Looking at the Sources in the debugger, I see the plugins folder is missing and an android2.3-jscompat.js file is added. Now, when I swipe the app off of running apps (no longer in memory) and click again all is fine once more until the back button is used. It seems like the WebView is starting up from a different point from when it loads originally (not in memory.)

Does anyone have thoughts? All of the other sources and index.html, etc remain unchanged... very odd.

I'm trying to fully close the app on the back button, but have not had much luck doing that.

Thanks in advance
![image](https://cloud.githubusercontent.com/assets/9951652/5268695/b57dd5d6-7a29-11e4-8493-3c94b173d297.png)

**Comment by gortok** [comment]
Could you include a link to a minimal reproduction of this issue in a new repo?  I'll be happy to take a look at this issue then (without code, it's hard to see where the problem is).
