### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pushNotification' of undefined

### ISSUE THREAD

**Issue by azizimusa** [driftyco/ng-cordova#494]
I am using the latest ngcordova. I have no such error in the previous version of ngcordova and push notification code template.

I use code as written on the ngcordova/com/docs

.run(function($scope,$cordovaPush) {

  var androidConfig = {
    "senderID": "9368xxxx571"
  };

  $cordovaPush.register(androidConfig).then(function(token) {
    // send token to server and save
  }, function(err) {
    // An error occurred. Show a message to the user
  });

  // receive a notification
  $rootScope.$on('pushNotificationReceived', function(event, notification) {
    if (notification.alert) {
      alert(notification.alert);
    }
  });
})

the error appeared on the browser console. But when i run in on my device (nexus5), black screen appeared.

**Comment by Tzafra** [comment]
@pbernasconi that worked for me, using ionic.  thanks!  why doesn't it work otherwise?

**Comment by gopi2mohan** [comment]
I am also working in ionic push notification i have a doubt in the "senderID": "9368xxxx571" what should we give there gcm project number or something else ?? i don't know please help me
