### ISSUE TITLE
$cordovaKeychain error - Keychain not defined

### ISSUE THREAD

**Issue by chicheongweng** [driftyco/ng-cordova#499]
I followed the steps listed on ngCordova website:

http://ngcordova.com/docs/#Keychain

but I am getting this error:

 ReferenceError: Keychain is not defined
    at Object.<anonymous> (http://localhost:8100/lib/ngCordova/dist/ng-cordova.js:2940:18)
    at Object.invoke (http://localhost:8100/lib/ionic/js/ionic.bundle.js:11591:17)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:11433:37

// install   :      cordova plugin add https://github.com/shazron/KeychainPlugin.git
// link      :      https://github.com/shazron/KeychainPlugin

angular.module('ngCordova.plugins.keychain', [])

  .factory('$cordovaKeychain', ['$q', function ($q) {

```
var kc = new Keychain();
```

**Comment by sreerammohan** [comment]
Still I see this error.
