### ISSUE TITLE
inappbrowser fails to build on ios

### ISSUE THREAD

**Issue by ferrao** [driftyco/ng-cordova#500]
iOS build fails on my ionic projects due to missing CDVInAppBrowser.m and CDVInAppBrowser.h
To make it work i had to create a new directory :

```
platforms/ios/<app_name>/Plugins/org.apache.cordova.inappbrowser
```

and copy to it the above files from :

```
plugins/org.apache.cordova.inappbrowser/src/ios
```

**Comment by verdi327** [comment]
Thanks for this workaround
