### ISSUE TITLE
appRate is undefined

### ISSUE THREAD

**Issue by saimon24** [driftyco/ng-cordova#503]
The appRate plugin is currently not working. $cordovaAppRate can be called, but when it reaches:
`var prompt = AppRate.promptForRating(immediate);`
the var AppRate is undefined. 

Maybe the cordova plugin from https://github.com/pushandplay/cordova-plugin-apprate.git is not imported/working as expected?

**Comment by robertoibarra** [comment]
After some fiddling, it seems AppRate is only populated after the onDeviceReady() in index.js is executed. This code seems to work as an example (from index.js):

var app = {
    // Application Constructor
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    // deviceready Event Handler
    //
    // Bind any cordova events here. Common events are:
    // 'pause', 'resume', etc.
    onDeviceReady: function() {
        //this.receivedEvent('deviceready');
        
		AppRate.preferences.storeAppURL = {
			android: 'market://details?id=com.catolicapp.misal'
		};

		AppRate.promptForRating();        
                
    },
........ rest of the code from index.js
