### ISSUE TITLE
facebookConnect web

### ISSUE THREAD

**Issue by djhr** [driftyco/ng-cordova#505]
Hi guys,
In the web version of the facebookConnect is required to call the plugin initializer before being able to use the plugin, currently you are just doing the initialization when $cordovaFacebook.login is called, which is wrong. Most of the times the first method that will be called is $cordovaFacebook.getLoginStatus which causes the promise to be not resolved.
This initialization should be done before any call to facebookConnect, and just once. Leaving the call to developers responsibility is ok (via $cordovaFacebook.init), what is not ok is do the initialization just sometimes, and without verifying if it was already initialized or not.
Cheers

**Comment by nandanrao** [comment]
@pbernasconi - so what is the correct way to do this now, and are those changes not yet on the latest bower version? 

Struggling to get this working, when I try doing browserInit() in the config module i get 'facebookConnectPlugin is not defined'... apparently that global isn't available at the time of the app bootstrapping when the config runs?

Any help would be appreciated, or I'd be happy to help in any way if I can, right now I'm just running off the current bower version, which doesn't have your fb patches, and then connecting the facebookconnectplugin directly to run fb.init right before I login, which works but I'd like to get this working in a proper way as soon as possible!

**Comment by pbernasconi** [comment]
@nandanrao first off install the latest through bower:

```
bower install ngCordova#master
```

That'll give you the latest changes to the FB plugin in ngCordova, and the working implementations that are in [the FB docs](http://ngcordova.com/docs/plugins/facebook/).

Then you should take a look at the DEMO app inside of ngCordova. It has a working example of the FB plugin. Look at [this source code specifically](https://github.com/driftyco/ng-cordova/blob/master/demo/www/app/app.js#L74).

**Comment by nandanrao** [comment]
Indeed loading the facebookConnectPlugin.js file manually would solve the problem, but is that really a solution you're suggesting? I would much prefer my current hack to this, but are you suggesting there's not an issue with the fact that
