### ISSUE TITLE
URL scheme plugin

### ISSUE THREAD

**Issue by ohh2ahh** [driftyco/ng-cordova#51]
I'm using this plugin to add an URL scheme to my app:
https://github.com/EddyVerbruggen/LaunchMyApp-PhoneGap-Plugin

It works great, but I'm sure I could have implement it much easier (I'm still learning AngularJS). So it would be great if ng-Cordova would support it (or a different URL scheme plugin if you want).

**Comment by shankari** [comment]
Although this commit is over two years old, it does not appear to be included in either the current `master` or the current `devnext` branch. I can work around this by manually including the code from the commit, but this seems like it is a useful plugin and should be included by default...
