### ISSUE TITLE
Unable to get recorded file content (read recorded file as text)

### ISSUE THREAD

**Issue by poshetz** [driftyco/ng-cordova#514]
Hello, sorry for the issue, but i can't understand who to record and read an audio file, i am using this code:
  
I first created a www/audio.wav empty file, then:

 _ .run(function($ionicPlatform, $cordovaMedia, $cordovaFile) {
    $ionicPlatform.ready(function() {

    var src = "audio.wav";

    var media = $cordovaMedia.newMedia(src);
    media.startRecord();

    // success
    console.log('Srtarted recording.....');

    $cordovaFile.checkFile("documents://audio.wav").then(function(result) {
      // Success!
      console.log('checking file ....');
      console.log(result);
    }, function(err) {
      // An error occurred. Show a message to the user

      console.log('ERROR CHECKING FILE');
      console.log(err);
    });

  });
});

It doesn't work, no errors, and no console.logs in xcode console, i already added all the console,media,file cordova plugins to the platform.

I just would like to record an audio.wav file and get its content as text, what i am doing wrong?

I am using ios emulator for this

thank you

**Comment by ranrolls** [comment]
I am not even able to use the core $cordovaFile functions.
Can u help
Thanks in advance

greatwebist@outlook.com
