### ISSUE TITLE
Unable to read cordova.file.dataDirectory

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ng-cordova#519]
I'm trying to create a directory under cordova.file.dataDirectory, but I was not able to get it to work. To simplify things I just tried to create/return dataDirectory itself:

			$cordovaFile.createDir(cordova.file.dataDirectory, false).then(function(result) {
				console.log('ok, i got the dir');
				console.dir(result);
			}, function(err) {
				console.log('err in $cordovaFile');
				console.dir(err);
			});

This returns error code 5, encoding error, which is apparently a bad url, but cordova.file.dataDirectory should be valid.

**Comment by cfjedimaster** [comment]
I assume *all* the methods that take paths are relative?

**Comment by kevingrabher** [comment]
this is how I do it:
`window.resolveLocalFileSystemURL(cordova.file.dataDirectory, function(dir){
     dir.getDirectory("myFolder", {create: true});
});`

**Comment by pbernasconi** [comment]
All methods now use `resolveLocalFileSystemURL` to get the FileSystem. Docs should be helpful

**Comment by ranrolls** [comment]
Getting 1000 and 5 no. error code

after using following code

                                                        // $cordovaFile.createDir('/pics/')
							  // .then(function (success) {
								// // success
									// toastr.success('Directory Created');
							  // }, function (error) {
									// // error
									// toastr.error(error);
									// toastr.info('v0.0.18');
									// toastr.error('Directory Creation Error');
							  // });

Hope any of you found the solution. Kindly mail to greatwebist@outlook.com

Thanks in advance
