### ISSUE TITLE
Update Changelog

### ISSUE THREAD

**Issue by gio82** [driftyco/ng-cordova#524]
Hey Paolo,

I understand this is "only" an alpha release.
It starts to be hard to check what is changed form one release to another.
It could be possible to keep updated the CHANGELOG.md file?
:)

thanks!

**Comment by Heshyo** [comment]
@pbernasconi Maybe you could simply put a link to the releases at the beginning of CHANGELOG.md. That way you wouldn't have to update both, and people would easily be able to find them.
