### ISSUE TITLE
$cordovaFile.upload options

### ISSUE THREAD

**Issue by EricWVGG** [driftyco/ng-cordova#537]
The documentation for the $cordovaFile.upload and download methods are missing an explanation of the possible options. They are, for reference: fileKey, fileName, mimeType, headers. Possibly more.

When the $cordova functionality is closely coupled to its cordova-plugin counterpart, it would be useful to have a link to the Cordova plugin documentation in question for reference, ex. https://github.com/apache/cordova-plugin-file-transfer/blob/master/doc/index.md

**Comment by pbernasconi** [comment]
Thank you @EricWVGG  we plan on adding more details to the docs soon, but for now this reference should help:

http://ngcordova.com/docs/plugins/fileTransfer/
