### ISSUE TITLE
"ble not defined" when using $cordovaBLE

### ISSUE THREAD

**Issue by docherty** [driftyco/ng-cordova#541]
Hi,
I'm trying to use the ngCordova plugin with Ionic to access Bluetooth LE functionality. I'm a n00b to angular so I'm obviously doing something wrong. When I use something like this in app.js:
```
.run(function($ionicPlatform, $cordovaDialogs) {
  $ionicPlatform.ready(function() {
	  // show an alert
	  $cordovaDialogs.alert("Hello there!", "A great title", "Dismiss");
	  })
})
```
I get the dialogue fine.

However, when I do this:
```
.run(function($ionicPlatform, $cordovaDialogs, $cordovaBLE) {
  $ionicPlatform.ready(function() {
	  $cordovaBLE.isEnabled(
		  function() {
			  $cordovaDialogs.alert("Bluetooth LE is enabled", "Bluetooth LE", "GREAT!");
		  },
		  function() {
			  $cordovaDialogs.alert("Bluetooth LE is NOT enabled", "Bluetooth LE", "Oops!");
		  });
  });
})
```
The alerts don't display (I don't get either one) and I get an error "ble is not defined" on line 527 of ng-cordova.js - the first line ble appears.

To check that I've got the correct Cordova plugins installed, I type "cordova plugins" in Terminal and get the following:
```
$ cordova plugins
com.megster.cordova.ble 0.1.0 "BLE"
com.megster.cordova.bluetoothserial 0.3.4 "Bluetooth Serial"
com.unarin.cordova.beacon 3.1.2 "Proximity Beacon Plugin"
de.appplant.cordova.plugin.local-notification 0.7.6 "LocalNotification"
nl.x-services.plugins.toast 2.0.2 "Toast"
org.apache.cordova.device 0.2.13 "Device"
org.apache.cordova.dialogs 0.2.11 "Notification"
org.apache.cordova.geolocation 0.3.11 "Geolocation"
org.apache.cordova.network-information 0.2.14 "Network Information"
org.apache.cordova.splashscreen 0.3.5-dev "Splashscreen"
```
For completeness, here are the relevant lines from index.html (the /lib/ng-cordova.js is the "full" file copied from the /dist/ directory):
```
<script src="lib/ng-cordova.js"></script>

    <!-- cordova script (this will be a 404 during development) -->
	<script src="cordova.js"></script>
	<script src="js/app.js"></script>
    <script src="js/controllers.js"></script>

```
I suspect that ble is a global variable that needs setting somewhere but I'm not sure how to get that working and poking about in the dark isn't helping. If anyone has any idea what I'm doing wrong, I'd be very grateful to be pointed in the right direction.
Many thanks,
James

**Comment by rlucian** [comment]
encountering the same issue.
did you find a solution, any alternative cordova plugins for BT LE?
maybe some workaround or fix available?

**Comment by josholdham** [comment]
I am not sure if you will have made the mistake I did, but I was wrongly testing through the simulator/web view. For ble to work, it seems you need to test on an actual device.

**Comment by rlucian** [comment]
thanks for getting back to me. I am on the device, for me it seems to be related to a mistake in using deviceready.. 
One more question though: does the module find all BT devices, or just BT LE?

**Comment by Fayozjon** [comment]
radu

http://scaer.ru/bankter

24.03.2015, 12:03, "radu" <notifications@github.com>:thanks for getting back to me. I am on the device, for me it seems to be related to a mistake in using deviceready.. 
One more question though: does the module find all BT devices, or just BT LE?

**Comment by dwimberger** [comment]
Actually isEnabled() in $cordovaBLE returns a promise, so your code should read:

    .run( function($ionicPlatform, $cordovaDialogs, $cordovaBLE) {
      $ionicPlatform.ready(function() {
          $cordovaBLE.isEnabled().then(
              function() {
                  $cordovaDialogs.alert("Bluetooth LE is enabled", "Bluetooth LE", "GREAT!");
              },
              function() {
                  $cordovaDialogs.alert("Bluetooth LE is NOT enabled", "Bluetooth LE", "Oops!");
              }
           );
      });
    })

Used as a promise, it seems to work properly on Android and iOS.
