### ISSUE TITLE
cordovaPush: Instead of "document.querySelector('[ng-app]')" use document.body for ecb

### ISSUE THREAD

**Issue by rickyk586** [driftyco/ng-cordova#542]
If an app uses angular.bootstrap() instead of the ng-app directive, the notification callback won't work because of this code:

    config.ecb = "angular.element(document.querySelector('[ng-app]')).injector().get('$cordovaPush').onNotification";

Maybe use document.body instead?

**Comment by pbernasconi** [comment]
hmm, that's a good point. I'll look into it. I don't like the way the Push Notification plugin handles the `notification` event, so it's a bit tedious to implement.

**Comment by pbernasconi** [comment]
Fix it now. 1cb428af99fbac3c55ef8152a619db6b64f89199

It check if `ng-app` is available in the body, if not uses `document.body`. Checked it on my iPhone 6 and is working.

**Comment by commandantp** [comment]
Hi,
It doesn't work with Android, I keep receiving that error when loading when angular.bootstrap but not with ng-app:
````
processMessage failed: Error: TypeError: Cannot read property 'get' of undefined
processMessage failed: Stack: TypeError: Cannot read property 'get' of undefined
    at eval (eval at processMessage (file:///android_asset/www/cordova.js:1021:26), <anonymous>:1:74)
    at processMessage (file:///android_asset/www/cordova.js:1021:13)
    at Function.androidExec.processMessages (file:///android_asset/www/cordova.js:1091:13)
    at pollOnce (file:///android_asset/www/cordova.js:956:17)
    at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:946:5)
processMessage failed: Message: Jjavascript:angular.element(document.querySelector('[ng-app]')).injector().get('$cordovaPush').onNotification({"event":"registered","regid":"APA91bFCuwFAveicLbPtR[...]"})
````
