### ISSUE TITLE
How to test facebook oauth on localhost?

### ISSUE THREAD

**Issue by JiriChara** [driftyco/ng-cordova#543]
I am getting

```
Given url is not permitted by the application configuration
```

anytime when I try to login through facebook. I suppose it is a problem with configuration on facebook site. How to set up app on facebook properly to play well with ngCordova OAuth? I have added `localhost` to App Domains in Basic app tab, added Website and set Site URL to: `http://localhost:3000/` and set redirect uri to `http://localhost:3000/callback`.

Can someone save my time and help me with the configuration? It should take part in `ngCordova` docs too.

Thanks

**Comment by nraboy** [comment]
Hi @JiriChara,

$cordovaOauth uses `http://localhost/callback` as the redirect / callback URI.  By including `:3000`, the logic won't know how to respond.

On The Facebook dashboard, make sure you set the Oauth Redirect URI to `http://localhost/callback'

A working demo application can be seen here:

https://github.com/nraboy/ng-cordova-facebook-example

Regards,

**Comment by JiachenDuan** [comment]
Hi nraboy,

Thanks for your example, it is awesome. Really helps a lot. Would you please make a Oauth2 facebook login version. Most popular way to do facebook login right now is just click it and redirect to facebook login using existing facebook app info without typing the username and password again. It will be extremely helpful, if you can do it for us. Thanks ahead!

Regards,
JK

**Comment by pbernasconi** [comment]
@JiachenDuan Are you talking about the Facebook plugin? http://ngcordova.com/docs/plugins/facebook/

**Comment by nraboy** [comment]
I agree with @pbernasconi.  If your looking to integrate with the Facebook app, then the Facebook plugin is the way to go.

However, $cordovaOauth does use Oauth2.  It is API based and is a fine solution.  It will only be isolated from the Facebook official app.

Regards,

**Comment by JiachenDuan** [comment]
@pbernasconi Thanks for your reply. Though I was actually talking about the $cordovaOauth example that nraboy created on his repo, your like did help me on other part of my project.

**Comment by JiachenDuan** [comment]
@nraboy Thanks for the confirmation. I implemented your example on my project. It works great. Just one thing is that it will redirect to a facebook login page which requires me to input my username and password. Is it possible to make it just redirect to a page that ask my permission to use my facebook account to login directly without asking me to input username and password again.

**Comment by pbernasconi** [comment]
@JiachenDuan You need the facebook plugin to do that. Since the `$cordovaOAuth` plugin opens a new browser inside of the app, it doesn't have access to a logged-in Facebook account, so the user will have to log in every time through the browser.

**Comment by pbernasconi** [comment]
@JiriChara Have you resolved your issue? Can this issue be closed now?

**Comment by nraboy** [comment]
After you sign in using $cordovaOauth, you just save the access token and the user won't need to signin again.

My example, I force a sign in every time.  Leave the rest to your imagination.

Regards,

**Comment by JiriChara** [comment]
@pbernasconi I haven't checked it until now, because of lack of time for my personal projects :cry:, but I had a short look on implementation of ng-cordova oauth and I suppose that callback to `http://localhost/callback` should work. I will just close the issue for now and occasionally reopen if I have the issue in the future. Thanks guys for your help!

**Comment by JiachenDuan** [comment]
@pbernasconi that make sense, I will try the facebook plugin tonight, thanks!

**Comment by JiachenDuan** [comment]
@nraboy yes, agree. However, I think allowing user to use their logged-in facebook account just simply make their life easier and everybody is doing it that way now. I think It would be nicer to make $sordovaOauth that way.

**Comment by nraboy** [comment]
Yes, I understand there is a convenience factor, but $cordovaOauth will never do that.  It is not the intention of the module.  $cordovaOauth is for web based authentication and it accomplishes the same end result as the app based authentication.  The dependencies are minimal as well making it easy on the developer.

At this point it becomes your own personal preference.
