### ISSUE TITLE
[Oauth] the 'exit' event always trigger before $http request return

### ISSUE THREAD

**Issue by Enkows** [driftyco/ng-cordova#544]
https://github.com/driftyco/ng-cordova/commit/4d93e126fd13a3116f16a4fd7687b9f7d32302b5

Maybe this works:
```
$http(...)
.success(function (data) {
  deferred.resolve(data);
})
.error(function (data, status) {
  deferred.reject("Problem authenticating");
})
.finally(function(){
  browserRef.close();
});
```

**Comment by pbernasconi** [comment]
@nraboy Any ideas for this?

@Enkows I think your fix is correct. It seems `browserRef.close();` is being called before the `defferred.resolve()` is fulfilled.

**Comment by nraboy** [comment]
I had this exact change in my development repository.  Just hadn't had the chance to make a pull request.

Thanks for beating me to it :)
