### ISSUE TITLE
Support copy operations for files in $cordovaFile

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ng-cordova#546]
Title says it all.

**Comment by PureSpider** [comment]
+1

**Comment by pbernasconi** [comment]
Working on this at the moment, hope to get it out today.

I'm also refactoring the `getDirectory()` method from `requestFileSystem` --> `resolveLocalFileSystemURL` so that it can be better configured.

@cfjedimaster would have time to comment / test?

**Comment by cfjedimaster** [comment]
Sure. Not a lot of time, but I would Monday. Let me know.

**Comment by pbernasconi** [comment]
Done in the latest few commits.

**Comment by pbernasconi** [comment]
Docs coming soon too.
