### ISSUE TITLE
ngCordova instalation

### ISSUE THREAD

**Issue by brunyan** [driftyco/ng-cordova#550]
I'm using ionic and I've installed ngCordova through"bower install ngCordova", and bower downloaded and installed "angular", "angular-animate", "angular-sanitize" and "angular-ui-router", do I need this packages? 
Doesn't ionic brings angular?

**Comment by pbernasconi** [comment]
Bower installed these because Ionic uses them as a dependency. And no you don't need these, in theory you can delete them and it won't affect your ionic project.

**Comment by brunyan** [comment]
Thank you for your fast response, but you say Ionic uses them as dependency, did you mean ngCordova, I've already Ionic installed and those packages appears after install ngCordova.

**Comment by pbernasconi** [comment]
Check out this file : https://github.com/driftyco/ionic/blob/master/bower.json#L50
It has the dependencies that you mentioned above. So when you do ANY `bower instal ...` action it will automatically get these dependencies.

If you project is working in your browser/phone there should be no problem

**Comment by pbernasconi** [comment]
@brunyan I hope that makes it clearer?

**Comment by brunyan** [comment]
Yes, thank you
