### ISSUE TITLE
$cordovaPush iOS - sometimes pushNotificationReceived event is not called

### ISSUE THREAD

**Issue by rickyk586** [driftyco/ng-cordova#555]
I was receiving this error sometimes when clicking on the push notification:
"$digest already in progress"

Changing
```
    $rootScope.$apply(function () {
        $rootScope.$broadcast('pushNotificationReceived', {notification : notification});
    });
```

to
```
    $timeout(function(){
      $rootScope.$broadcast('pushNotificationReceived', {notification : notification});
    });
```

fixed the issue.

**Comment by pbernasconi** [comment]
Thanks for the issue, and you're definitely right. If several push notifications are sent at the same time, the $digest cycle is likely to still be running. Fix in 1cb428af99fbac3c55ef8152a619db6b64f89199

Now uses `$timeout`
