### ISSUE TITLE
pickContact broken

### ISSUE THREAD

**Issue by ozexpert** [driftyco/ng-cordova#557]
not working, but instead i use navigator.contacts.pickContact(), then works.

**Comment by pbernasconi** [comment]
@ozexpert Can you give me details about your environment?
- Phone OS
- ngCordova version
- the code you're using

I have the `$cordovaContacts.pickContact()` method working on my iPhone (look at the `/demo/www/app/contacts` folder).

**Comment by ozexpert** [comment]
Android 4.4.4
ngCordova 0.1.9-alpha

code grabbed from sample. no syntax error...
