### ISSUE TITLE
ORM PersistenceJS 

### ISSUE THREAD

**Issue by brunogonncalves** [driftyco/ng-cordova#561]
Hi, you know persistenceJS ?  Is the best ORM Library for javascript, would be very interesting to add it to the project, I can help with this ?
https://github.com/coresmart/persistencejs

**Comment by pbernasconi** [comment]
It's an interesting concept, but I don't think it fits well into ngCordova. PersistenceJS creates its own wrapper for the SQLite plugin, which directly collides with the purpose of ngcordova. You should probably use this as a supplement to ngCordova.
