### ISSUE TITLE
 $cordovaSocialSharing - posting pre-written messages to facebook notworking

### ISSUE THREAD

**Issue by unaor** [driftyco/ng-cordova#562]
Hi
i know about the facebook issue described here https://developers.facebook.com/x/bugs/332619626816423/

but the developer of the plugin has published a walk around using a method called shareViaFacebookWithPasteMessageHint

when doing it using the ng-cordova i get in the logs message saying 'TypeError: Object #<Object> has no method 'shareViaFacebookWithPasteMessageHint''

Looks like the library was not updated

**Comment by pbernasconi** [comment]
Fixed in a5df9db264a72fa7ef10848d93925ab15490cf75

**Comment by unaor** [comment]
Tested and working ,thanks
