### ISSUE TITLE
PushPlugin - pending notifications : how?

### ISSUE THREAD

**Issue by biapar** [driftyco/ng-cordova#563]
is't possible to catch pending notification?

**Comment by pbernasconi** [comment]
Yes there is, check out the [Push Notification Docs in ngCordova](http://ngcordova.com/docs/plugins/pushNotifications/).

But generally you want to listen for the `notificationReceieved` event like so:

```javascript
$rootScope.$on('pushNotificationReceived', function(event, notification) {
...
});
```
