### ISSUE TITLE
Not working with ng-strict-di anymore

### ISSUE THREAD

**Issue by PureSpider** [driftyco/ng-cordova#571]
I just replaced my ngCordova with non-minified v0.1.11-alpha,  now I am getting following error when using ng-strict-di:
`Uncaught Error: [$injector:strictdi] function($cordovaBatteryStatus) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.3.6/$injector/strictdi?p0=function(%24cordovaBatteryStatus)`
I suspect it's because https://github.com/driftyco/ng-cordova/blob/master/dist/ng-cordova.js#L437 is not using strict DI (maybe?).
There may be more occurances of this but my app stopped after the first error.

**Comment by westor21** [comment]
True, I replaced line 437, 438 to   
  .run([function ($cordovaBatteryStatus) {
  }]);
but the next one is $cordovaNetwork, which is not well annotated.
