### ISSUE TITLE
$cordovaDeviceMotion for when shake starts and ends

### ISSUE THREAD

**Issue by Duovili** [driftyco/ng-cordova#577]
How would you use this plugin to check for shakes? I have tried to implement this but none of my call backs work.

**Comment by pbernasconi** [comment]
I've never used the Device Motion plugin to detect shakes, and I'm not sure that it would be the right plugin to use. You might want to look at http://plugreg.com/ for a plugin that might help you do this. Or ask a question on the http://forum.ionicframework.com/

**Comment by pbernasconi** [comment]
@Duovili I've found a plugin you want: https://github.com/leecrossley/cordova-plugin-shake-detection

I might have time to add it to ngCordova this afternoon.

**Comment by Duovili** [comment]
Has it been added to ngcordova?

On 21 January 2015 at 19:34, Paolo Bernasconi <notifications@github.com>
wrote:

> Closed #577 <https://github.com/driftyco/ng-cordova/issues/577>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ng-cordova/issues/577#event-222474219>.
>



-- 
Ross Rawlins
*Tel:* 021 531 7087
*Cell:* 072 424 9480
*Skype:* ross.rawlins
*Email:* ross@duovili.co.za

<http://www.duovili.co.za>
<https://plus.google.com/113781084234234096576/posts>
<https://www.facebook.com/Duovili>
<http://www.linkedin.com/company/duovili/>     <https://twitter.com/Duovili>


This e-mail message and all attachments contain the CONFIDENTIAL AND
PROPRIETARY information of DUOVILI DEVELOPMENTS. and may contain LEGALLY
PRIVILEGED information. If you are not the intended recipient, you are
hereby notified that any disclosure, distribution, or use of this e-mail,
its attachments or any information contained therein is unauthorised and
prohibited. If you have received this in error, please contact the sender
immediately and delete this e-mail and any attachments.

**Comment by Duovili** [comment]
Hi I just wanted to see if you have had a chance to add it to ng-cordova?

**Comment by dmastag** [comment]
Don't think this has been implemented, but here is a nice articel I found on the Web which also covers Shake I think
http://www.gajotres.net/detecting-device-motion-with-ionic-framework-and-ngcordova/

**Comment by Kratos-SA** [comment]
Hey thank you for the link I tried that code but Only my costum functions work. I am getting null values for the shake detection. I am really just wanting to build a test shake app and any help in fixing this would be much appreciated.
