### ISSUE TITLE
inviteViaEmail social sharing problem

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ng-cordova#579]
Hey there, all the social sharing functions work great except for `inviteViaEmail`, I wrapped it in a `try catch` and get the following error.

http://www.jsoneditoronline.org/?id=134c6e0e0ba5d227ad76344f83313660

Any assistance would be greatly appreciated!

**Comment by sean-hill** [comment]
I found a bit of the issue

	console.log('1');
	console.log($cordovaSocialSharing);
	console.log('2');
	console.log($cordovaSocialSharing.shareViaEmail);
	console.log('3');

The output of that is

	1
	{}
	2
	3

Looks like `$cordovaSocialSharing` isn't defined for some reason.

**Comment by pbernasconi** [comment]
Can you share your code + environment (phone, cordova version, etc)

And Checkout http://ngcordova.com/docs/common-issues/

**Comment by sean-hill** [comment]
// JS

	.controller('InviteCtrl', function($scope, $cordovaSocialSharing){

		$scope.invite = function(type) {

			switch(type) {

				case 'sms':
					$scope.inviteViaSMS();
					break;
				case 'email':
					$scope.inviteViaEmail();
					break;
				case 'facebook':
					$scope.inviteViaFacebook();
					break;
				case 'twitter':
					$scope.inviteViaTwitter();
					break;
				default:
					break;

			}

		};


		$scope.inviteViaEmail = function() {
			$cordovaSocialSharing
				.shareViaEmail($scope.message + "\n\n" + $scope.link, 'Join ' + $scope.user.name.first + ' on Unbill')
				.then($scope.onSuccess, $scope.onError)
			;
		};

		$scope.inviteViaFacebook = function() {
			$cordovaSocialSharing
				.shareViaFacebook($scope.message, null, $scope.link)
				.then($scope.onSuccess, $scope.onError)
			;
		};
		
		$scope.inviteViaTwitter = function() {
			$cordovaSocialSharing
				.shareViaTwitter($scope.message, null, $scope.link)
				.then($scope.onSuccess, $scope.onError)
			;
		};

		$scope.onSuccess = function() {
			console.log('Success');
		};

		$scope.onError = function(err) {
			console.log('Error', err);
		};

	});

	// HTML

	<div class="list">
		<div class="item item-divider">How would you like to invite?</div>
		<div class="item item-icon-left" ng-click="invite('sms')">
			<i class="icon ion-chatbubble-working" style="color: #5677FC"></i>
			<h2>Text Message</h2>
			<p>Text your friend an invitation</p>
		</div>
		<div class="item item-icon-left" ng-click="invite('email')">
			<i class="icon ion-email" style="color: #EEAF4B"></i>
			<h2>Email</h2>
			<p>Email your friends the invitation</p>
		</div>
		<div class="item item-icon-left" ng-click="invite('facebook')">
			<i class="icon ion-social-facebook" style="color: #567DCE"></i>
			<h2>Facebook</h2>
			<p>Find your friends on Facebook</p>
		</div>
		<div class="item item-icon-left" ng-click="invite('twitter')">
			<i class="icon ion-social-twitter" style="color: #41C1FC"></i>
			<h2>Twitter</h2>
			<p>Tweet your friends the invite</p>
		</div>
	</div>

**Comment by pbernasconi** [comment]
You have to wrap each plugin call with 

```
document.addEventListener("deviceready", function () {
  $cordovaPlugin.someFunction().then(success, error);
}, false);
```

**Comment by sean-hill** [comment]
I'll try that, but this view is multiple states down from the launch of the app, so I'd hope the `deviceready` event had already fired :)

**Comment by sean-hill** [comment]
Yeah I still get the same error after wrapping in the `deviceready` call.

**Comment by sean-hill** [comment]
It's weird because it's never actually getting into the `ng-cordova` code, it crashes at

    $cordovaSocialSharing
            .shareViaEmail(...)

**Comment by pbernasconi** [comment]
Ahh check out the [official docs](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin#sharing-directly-to) And look at the `shareViaEmail` example:

```js
window.plugins.socialsharing.shareViaEmail(
  'Message', // can contain HTML tags, but support on Android is rather limited
  'Subject',
  ['to@person1.com', 'to@person2.com'], // TO: must be null or an array
  ['cc@person1.com'], // CC: must be null or an array
  null, // BCC: must be null or an array
  ['https://www.google.nl/images/srpr/logo4w.png','www/localimage.png'], // FILES: can be null, a string, or an array
  onSuccess, // called when sharing worked, but also when the user cancelled sharing via email (I've found no way to detect the difference)
  onError // called when sh*t hits the fan
);
```

so with ngCordova it would be 

```
$cordovaSocialSharing
        .shareViaEmail(message, subject, null, null, null, null)
```

If that works for you, I'll make some changes to the ngCordova source file to catch this type of error

**Comment by sean-hill** [comment]
Lol, I found my real issue. My `Subject` was crashing the program because `$scope.user` was undefined. We can close this issue...

**Comment by pbernasconi** [comment]
Good to know.
