### ISSUE TITLE
Feat: register ngCordova plugins on cordova plugin registry (for PGB)

### ISSUE THREAD

**Issue by dmytro-shchurov** [driftyco/ng-cordova#583]
Since phonegap supports cordova plugin registry official names, now it's possible to build an app with their remote build service using registered cordova plugins, but they still require a plugin must be registered either in a cordova or in phonegap registry.
Now it's very simple and transparent to put it into the registry. Everybody can register anyone's plugin, but I'd like to avoid doing this by myself.

**Comment by pbernasconi** [comment]
I like your idea and think it would in fact be very beneficial to have **all** cordova plugins registered on both the phonegap + cordova registry.

I've always considered a side project of ngCordova to contain it's own registry, which could be downloaded like:

```
ngCordova add $cordovaFile
ngCordova add $cordovaFacebook
...
```

The main issue with this is that the plugins are officially owned and maintained by their respective creators. This means that it's neither my place to put them into the registry nor is it very efficient for keeping them all up to date on the registry.

But your idea is good, so I'm going to start some issues on each plugin to get the owner to register them.

**Comment by ranrolls** [comment]
I am not even able to use the core $cordovaFile functions.
Can u help
Thanks in advance

greatwebist@outlook.com
