### ISSUE TITLE
Problem : angular.element(null) is not undefined

### ISSUE THREAD

**Issue by fretman92** [driftyco/ng-cordova#585]
Hello guys,

Great work here.

I think I detected an issue here -> https://github.com/driftyco/ng-cordova/blob/master/dist/ng-cordova.js#L5335 because my Angular app is not launched via ng-app directive but with angular.bootstrap

This test `if (angular.element(document.querySelector('[ng-app]')) === undefined) ` is never true, because when `document.querySelector('[ng-app]')` is null (normal), then `angular.element(null)` returns `[]` (empty array).
Tested on Angular 1.26 and lastest 1.3.9

**Comment by pbernasconi** [comment]
Thanks for raising that issue! And you're right, tested and fixed: d46d6ae368f4abdc2270621644fc592255aa9c4c

**Comment by fretman92** [comment]
Thanks for the reply, however your solution won't work either.
As I said, `angular.element(null)` returns `[]`, not `null`.
And `[] == null` returns `false`

**Comment by pbernasconi** [comment]
Shoot, sorry I just woke up -- mind is slow. How about:

```
if (angular.element(document.querySelector('[ng-app]')) === undefined) {
  if (angular.element(document.querySelector('[ng-app]'))) {
     injector = "document.querySelector('[ng-app]')";
  }
  else {
    injector = "document.body";
  }
```

**Comment by fretman92** [comment]
Why not just test : `if(document.querySelector('[ng-app]') == null)`?
or if you want to keep angular :  `if(angular.element(document.querySelector('[ng-app]')) === [])`

**Comment by pbernasconi** [comment]
You're right, no point testing if the angular element exists, when we are really determining if the `ng-app` element exists.

**Comment by pbernasconi** [comment]
Should be right now 1522f3d278401c2fe5133fed148a19dd1233465d

**Comment by fretman92** [comment]
Thanks a lot for the responsiveness. Keep up the good work ;)
