### ISSUE TITLE
App white screen before adding 'ngCordova' Gingerbread

### ISSUE THREAD

**Issue by Midraks** [driftyco/ng-cordova#586]
Hi.

I have this problem in the version Gingerbread, which are the versions supported for ngCordova?

(Sorry for my english).

**Comment by pbernasconi** [comment]
@Midraks there must be an error in your code somewhere, since ngCordova doesn't break apps (as far as I know). Can you provide your error log

**Comment by pepetox** [comment]
Hi,

I have the same problem, the app works fine in browser and newer version of android but in 2.3.6 (Gingerbread) the app stay in a white screen after add the ng-cordova.
