### ISSUE TITLE
Difficulty with $cordovaMedia.newMedia().then()

### ISSUE THREAD

**Issue by EricWVGG** [driftyco/ng-cordova#588]
I’m running a very simple instance of $cordovaMedia.newMedia(), and running into problems with my success callback.

```
var audio = $cordovaMedia.newMedia(scope.player.src).then(function(r) {
    audio.play();
}, function (r) {
    console.log(r);
});
```

This returns…
`Error: undefined is not a function (evaluating 'c.newMedia(a.player.src).media.then(function(a){console.log(a),d=a,d.play()},function(){})')`

… what has me confused is, I don’t even see why this would work in the first place. Upon closer inspection of ng-cordova, I’m seeing that newMedia() returns an object holding three properties: media, mediaStatus, promise. How would then() know which property to run off of?

I’ve tried running $cordovaMedia.newMedia().promise.then(function()… but it doesn’t appear to be working either.

**Comment by danielcrisp** [comment]
Take a look at my answer to #591

Also, don't call the `audio.play()` method inside the success callback (I believe that only fires once playback has completed).

Call it after you create the object, like this:

    var audio = $cordovaMedia.newMedia(scope.player.src);

    audio.then(function(r) {
        console.log('success');
        console.log(r);
    }, function (r) {
        console.log('error');
        console.log(r);
    });

    audio.play();

**Comment by inceptiveKshitij** [comment]
TypeError: mediaSrc.then is not a function. (In 'mediaSrc.then', 'mediaSrc.then' is undefined) i got this error on below code 

for audio.then()
