### ISSUE TITLE
Docs: add version drop down

### ISSUE THREAD

**Issue by Mayho** [driftyco/ng-cordova#589]
App rate docs (http://ngcordova.com/docs/plugins/appRate/) are based on master branch, rather than latest release branch.

Would be nice if there was a version selector for docs like the core Ionic docs.

**Comment by Hendrixer** [comment]
:+1:

**Comment by steinernein** [comment]
:+1:

**Comment by gdi2290** [comment]
:+1:

**Comment by pbernasconi** [comment]
Great idea. I'll look into. It will take some time to implement if I can get around to it.
