### ISSUE TITLE
Bug: BLE of source is outdated and different README

### ISSUE THREAD

**Issue by guanbo** [driftyco/ng-cordova#590]
- In src, BLE is base on @don 's [cordova-plugin-ble-central](https://github.com/don/cordova-plugin-ble-central) and it's outdated. Please refer to [ble.js](https://github.com/don/cordova-plugin-ble-central/blob/master/www/ble.js), some has been deprecated.
- In README, I found [Bluetooth Low Energy](https://github.com/evothings/cordova-ble) link to @evothings . Does it mean BLE will going to replace by [cordova-ble](https://github.com/evothings/cordova-ble). Had any roadmap?
- I plan to  update ngCordova BLE plugin, But don't konwn which plugin will be chose? 

@pbernasconi

**Comment by don** [comment]
@guanbo [my ble plugin](https://github.com/don/cordova-plugin-ble-central) is under development, as the API evolves I'm deprecating older methods. So far, it has just been renaming existing methods for better clarity.

**Comment by guanbo** [comment]
> my ble plugin is under development

Yes @don , I found $cordovaBLE is not work well under iOS. Due to send `PluginResult` of `CDVCommandStatus_NO_RESULT`, such as [scan](https://github.com/don/cordova-plugin-ble-central/blob/master/src/ios/BLECentralPlugin.m#L266), it triggers ngCordova's promise reject null error. And then promise was gone, chain broken.

**Comment by don** [comment]
@guanbo just published version 0.1.3 of the BLE plugin with a fix for the iOS NO_RESULT bug

**Comment by guanbo** [comment]
It's great @don . iOS is OK.

BTW: cordova plugins registry still on 0.1.2
