### ISSUE TITLE
Media plugin issue

### ISSUE THREAD

**Issue by linkito** [driftyco/ng-cordova#591]
Hi!
I'm working on app with ionic, with ngCordova (versión 0.1.11-alpha) and cordova, and I have a problem when the Media Plugin...

This is my code:
```
.controller('AppCtrl', function($scope, $ionicFrostedDelegate, $ionicModal, $ionicPlatform, $cordovaMedia, $timeout) {

   var media;
    $ionicPlatform.ready(function() {
            var iOSPlayOptions = {
                playAudioWhenScreenIsLocked : true
            }
            var src = "http://www.url.com/track01.mp3";
            media = $cordovaMedia.newMedia(src).then(function() {
                // success
                alert("Sucess");               
            }, function () {
                // error
                alert("error");
            });
        });

    $scope.play = function(){
         media.play();
    };
    $scope.pause = function(){
        media.pause();
    };
    

})
```
And when i press the button that tiggers the play function, I have this error:
```

0     886333   error    Error: undefined is not a function (evaluating 'media.play()')
play@http://192.168.1.25:8100/js/controllers.js:29:20
````
Anybody can help me? Thanks!

**Comment by danielcrisp** [comment]
It seems that the documentation is not quite correct.

You need to split up this line: `media = $cordovaMedia.newMedia(src).then(function() {` because if you call the `then` method immediately (chained) then it doesn't return the promise that contains the `play`, `pause` methods etc.

So do this...

    .controller('AppCtrl', function($scope, $ionicFrostedDelegate, $ionicModal, $ionicPlatform, $cordovaMedia, $timeout) {

       var media;
        $ionicPlatform.ready(function() {
                var iOSPlayOptions = {
                    playAudioWhenScreenIsLocked : true
                }
                var src = "http://www.url.com/track01.mp3";
                
                // create media promise
                media = $cordovaMedia.newMedia(src);

                // promise completion
                media.then(function() {
                    // success
                    alert("Sucess");               
                }, function () {
                    // error
                    alert("error");
                });
            });

        $scope.play = function(){
             media.play();
        };
        $scope.pause = function(){
            media.pause();
        };


    })

**Comment by linkito** [comment]
Thanks dude! Solved! :+1: 

Only one question more... With this plugin, I can't play a streaming audio... Like that:
http://audio-online.net:2300/live

U know how can play a streaming audio with bufer with a cordova plugin?

Thanks again!

**Comment by danielcrisp** [comment]
Have you looked this? https://github.com/nchutchind/Streaming-Media-Cordova-Plugin

I've not tried it myself but it seems to do what you want

**Comment by linkito** [comment]
Sounds good... but I want a player with the methods of the Cordova Media Plugin (getDuration and  seekTo...). But the Media Plugin doesn't plays streaming audio, and with a mp3 file, first load it, and after start play...

U have another solution?

Anyway, thanks for your help :)

**Comment by danielcrisp** [comment]
I don't know of a plugin that does it but you can play it with pure JS:

http://jsfiddle.net/L1kwmepe/

**Comment by linkito** [comment]
Thanks a lot dude... I close this issue, all solved :+1:  :)

**Comment by inceptiveKshitij** [comment]
TypeError: mediaSrc.then is not a function. (In 'mediaSrc.then', 'mediaSrc.then' is undefined) i got this error on below code

`var src = ionic.Platform.isAndroid() ? "/android_asset/www/audio/beep.wav": "audio/beep.wav";
                var mediaSrc = $cordovaMedia.newMedia(src);
                //mediaSrc.promise.then($cordovaMedia.play(mediaSrc.media));

                mediaSrc.then(function(r) {
                    console.log('success');
                    console.log(r);
                }, function(r) {
                    console.log('error');
                    console.log(r);
                });

                mediaSrc.play();`

how to resolve it
