### ISSUE TITLE
ngCordova DeviceOrientation

### ISSUE THREAD

**Issue by pcrombach** [driftyco/ng-cordova#592]
In the doc for $cordovaDeviceOrientation:

    $cordovaDeviceOrientation.clearWatch(watch)
      .then(function(result) {
        // Success!
      }, function(err) {
        // An error occurred
      });

  }, false);

$cordovaDeviceOrientation.clearwatch is not a promise

if it should be a promise:

clearWatch: function (watchID) {
var q = $q.defer();
navigator.compass.clearWatch(watchID);
q.resolve();
return q.promise;
}
Or the example in the doc should not use method .then.

BTW why is there in watchHeading a method???:

        q.promise.clearWatch = function (id) {
          navigator.compass.clearWatch(id || watchID);
        };

**Comment by pbernasconi** [comment]
I'm adding the `clearWatch` method to the returned promise -- it allows the user to call this function after the promise has been resolved.
