### ISSUE TITLE
New Usefull function for $cordovaFile 

### ISSUE THREAD

**Issue by pcrombach** [driftyco/ng-cordova#593]
Here I suggest to adopt this new function I use a lot:

//
// creaetPath recursivily
//
// create folders start on root.
// creates folders tiles, genres and jazz
// createPath('/', 'tiles/music/genres/jazz/')
//
      createPath: function(filePath, path) {
        var q = $q.defer();

        function createDir(rootDirEntry, folders) {
          // Throw out './' or '/' and move on to prevent something like '/foo/.//bar'.
          if (folders[0] === '.' || folders[0] === '') {
            folders = folders.slice(1);
          }
          if (folders[0] !== undefined) {

            rootDirEntry.getDirectory(folders[0], {create: true}, function(dirEntry) {
              // Recursively add the new subfolder (if we still have another to create).
              if (folders.length) {
                createDir(dirEntry, folders.slice(1));
              }
            },
            function(err) {
              q.reject('DIRECTORY_NOT_FOUND');
            });
          } else {
            q.resolve(path);
          }
        }

        getDirectory(filePath, {create: false})
        .then(function (dirEntry) {
          createDir(dirEntry, path.split('/'));
        },
        function(err) {
          q.reject('DIRECTORY_NOT_FOUND');
        });

        return q.promise;
      },

**Comment by ranrolls** [comment]
I am not even able to use the core $cordovaFile functions.
Can u help
Thanks in advance

greatwebist@outlook.com
