### ISSUE TITLE
Some other usefull function for $cordovaFile

### ISSUE THREAD

**Issue by pcrombach** [driftyco/ng-cordova#594]
//
// copy('me.png', 'you.png')
//
      copy: function(src, dest) {
        var q = $q.defer();

          getFileEntry(src, {})
          .then( function(fileEntry) {
            getDirectory(dest, {})
            .then( function(dirEntry) {
              fileEntry.copyTo(dirEntry);
              q.resolve(dirEntry);
            },
            function() {
              q.reject('DEST_NOT_FOUND : ' + dest);
            });
          },
          function(err) {
            q.reject('SRC_NOT_FOUND : ' + src);
          });

        return q.promise;
      },
//
// rename('me.png', 'you.png');
//
      rename: function(src, newName) {

        var q = $q.defer();

        var cwd = src.substring(0, src.lastIndexOf('/') + 1);
        getDirectory(cwd, {})
        .then( function(dirEntry) {
          getFileEntry(src, {})
          .then( function(fileEntry) {
            fileEntry.moveTo(dirEntry, newName);
            q.resolve(fileEntry);
          },
          function(err) {
            q.reject('SRC_NOT_FOUND: ' + src);
          });
        },
        function(err) {
            q.reject('DIR_NOT_FOUND: ' + cwd);
        });

        return q.promise;
      },
//
// move('me.png', 'newFolder/');
//
      move: function(src, dirName) {
        var q = $q.defer();

        getFileEntry(src, {})
        .then( function(fileEntry) {
          getDirectory(dirName, {})
          .then( function(dirEntry) {
            fileEntry.moveTo(dirEntry);
            q.resolve(dirEntry);
          },
          function() {
            q.reject('DIRNAME_NOT_FOUND: ' + dirName);
          });
        },
        function() {
          q.reject('FILE_NOT_FOUND');
        });

        return q.promise;
      },

**Comment by josemadev** [comment]
this can be used for copy a photo token in this function ???

  $scope.getPhoto = function() {
      console.log('Getting camera');
      Camera.getPicture().then(function(imageURI) {
//Save de photo in dir 
//PLease show me a example

**Comment by pbernasconi** [comment]
I've added `copy` and `move` methods, but I'll look into the `rename` method

**Comment by pcrombach** [comment]
//
// creaetPath recursivily
Another very usefull extensions for ngCordova File
//
//Example:
// create folders start on root.
// creates folders tiles, genres and jazz
// createPath('/', 'tiles/music/genres/jazz/')
//
      createPath: function(filePath, path) {
        var q = $q.defer();

        function createDir(rootDirEntry, folders) {
          // Throw out './' or '/' and move on to prevent something like '/foo/.//bar'.
          if (folders[0] === '.' || folders[0] === '') {
            folders = folders.slice(1);
          }
          if (folders[0] !== undefined) {
console.log('createPath next subdirectory: ' + folders[0]);

            rootDirEntry.getDirectory(folders[0], {create: true}, function(dirEntry) {
              // Recursively add the new subfolder (if we still have another to create).
              if (folders.length) {
                createDir(dirEntry, folders.slice(1));
              }
            },
            function(err) {
  console.error('DIRECTORY_NOT_FOUND');
              q.reject('DIRECTORY_NOT_FOUND');
            });
          } else {
            q.resolve(path);
          }
        }

      },
