### ISSUE TITLE
Wrapper for filechooser cordova plugin

### ISSUE THREAD

**Issue by bukosabino** [driftyco/ng-cordova#598]
Hi, I'm new to 'ionic world', I would like to use a filechooser cordova plugin for Android https://github.com/cdibened/filechooser in my Ionic project.

Do I have to create my own wrapper? what/where I can read about it? Any indications for beginners?

Thank you!

**Comment by gortok** [comment]
If you need to create a wrapper; the best thing I can suggest is for you to look at any of the existing wrappers and then look at the code they wrap.  

In my case; I wrote a wrapper recently for a plugin that's not yet in the core of this project:

https://github.com/driftyco/ng-cordova/commit/f07176e606d32cf6ff3220e8fcc498c0181c2ef4

The biggest gotchas I've encountered is that sometimes the cordova plugins are continuous (they may trigger the success callback multiple times); but angularJS promises only resolve once; which means you may need to rely on the 'notify' condition and write custom code to determine when a promise should actually resolve.  This should follow the spirit of the plugin you're wrapping. An example of where I had to do that is referenced in issue #885.  

Let me know if you have any more questions about this.

Also, we have a file plugin; let me know if that's not what you need: https://github.com/driftyco/ng-cordova/blob/master/src/plugins/file.js
