### ISSUE TITLE
$cordovaNetwork: TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by pellekrogholt** [driftyco/ng-cordova#60]
hi,

i'm using current master (7980897625b489c6c4926134c275e7d695bec245) of ng-cordova and like to use $cordovaNetwork in a login  controller for example:

```
var loginControllers = angular.module('loginControllers', []);

loginControllers
  .controller('LoginCtrl', [
'$scope',
'$log',
'$state',
'$ionicLoading',
'$cordovaNetwork',
function($scope, $log, $state, $ionicLoading, $cordovaNetwork) {

  var type = $cordovaNetwork.getNetwork();
  var isOnline = $cordovaNetwork.isOnline();

  $log.log('network type', type);
  $log.log('network isOnline', isOnline);

  $ionicLoading.show({
    template: '... loading ...'
  });

}]);
```

when i deploy to an android (4.4) nexus 4 device i get a blank screen.

then with chrome://inspect device - i get the following in the console: 

```
TypeError: Cannot read property 'type' of undefined
at Object.getNetwork (file:///android_asset/www/lib/ng-cordova/dist/ng-cordova.js:793:34)
at new <anonymous> (file:///android_asset/www/js/login/controllers.js:27:66)
at invoke (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:12641:17)
at Object.instantiate (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:12652:23)
at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:15711:28
at updateView (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:41075:30)
at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:41031:9
at nodeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:15161:13)
at compositeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:14567:15)
at nodeLinkFn (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:15155:24) <ion-nav-view name="menuContent" animation="slide-left-right"> ionic.bundle.js:18366
```

"ng-cordova.js:793:34" ->

```
return navigator.connection.type;
```

but i can successfully in console do:

```
> navigator.connection.type
"wifi"
```

just for the record in the app.js where i load  loginControllers i have ngCordova as a dependency:

```
  var myApp = angular.module('myApp', [
    'ionic',
    'ngCordova',
   ...
```

sorry if its not a error related to ng-cordova ....

//

pelle

**Comment by MateenKadwaikar** [comment]
0
down vote
I am also facing the same issue. This is my controller

.controller('MapCtrl', ['$scope', '$rootScope', '$cordovaNetwork',

    function($scope, $rootScope, $cordovaNetwork) {


        $ionicPlatform.ready(function() {

            var type = $cordovaNetwork.getNetwork()

            var isOnline = $cordovaNetwork.isOnline()

            var isOffline = $cordovaNetwork.isOffline()


            // listen for Online event
            $rootScope.$on('$cordovaNetwork:online', function(event, networkState) {
                console.log(event);
                console.log(networkState);
                var onlineState = networkState;
            })

            // listen for Offline event
            $rootScope.$on('$cordovaNetwork:offline', function(event, networkState) {
                console.log(event);
                console.log(networkState);
                alert(networkState);
            });
        });
    }
]);

**Comment by diegognt** [comment]
```javascript
( function ()
{
    'use strict';
    angular.module( 'ouNow.core' )
        .factory( 'ConnectionDetectiorService', ConnectionDetectiorService );

    ConnectionDetectiorService.$inject = ['$cordovaNetwork'];

    function ConnectionDetectiorService($cordovaNetwork)
    {
        var service = {
            thereIsCellConnection: thereIsCellConnection,
            thereIsWiFiConnection: thereIsWiFiConnection,
        };

        return service;

        function thereIsCellConnection() {
            console.log('to detect');

            console.log($cordovaNetwork.getNetwork());
        }

        function thereIsWiFiConnection() {
            // body...
        }

    }
```

I got:

TypeError: Cannot read property 'type' of undefined
    at Object.getNetwork (http://localhost:8100/lib/ngCordova/dist/ng-cordova.js:5472:36)
    at Object.t [as thereIsCellConnection] (http://localhost:8100/dist/app.js:1:7163)
    at i (http://localhost:8100/dist/app.js:1:24049)
    at new e (http://localhost:8100/dist/app.js:1:24360)
    at invoke (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13277:17)
    at Object.instantiate (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13285:27)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:17841:28
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1544:22
    at IonicModule.controller.self.appendViewElement (http://localhost:8100/lib/ionic/js/ionic.bundle.js:52255:24)
    at Object.IonicModule.factory.ionicViewSwitcher.create.switcher.render (http://localhost:8100/lib/ionic/js/ionic.bundle.js:50449:41) <ion-nav-view name="menuContent" class="view-container" nav-view-transition="android">

I tried on nexus 6. Ionic 1.1.0

**Comment by derekdon** [comment]
Facing the same issue.

**Comment by vitorventurin** [comment]
Hey guys! I've got a solution! Start studying native iOS and Android! *LOL* #sadbuttrue

**Comment by alloyking** [comment]
@vitorventurin oh sure that's the solution.  Not all my clients want to pay for both IOS and Android development.  #sadbuttrue

**Comment by vitorventurin** [comment]
i agree with you @alloyking. i recommend ionic for simple projects but every app with low-level features are problematic. keep rockin'!!!
hugs
victor

**Comment by alloyking** [comment]
@vitorventurin I like hugs!  Thanks for that. :)

**Comment by vitorventurin** [comment]
@alloyking i am from Brazil. everyone here loves hugs. haha. you are welcome. https://www.youtube.com/watch?v=izGwDsrQ1eQ

**Comment by chukwu** [comment]
guys...lets not get personal. I still cant find a fix for the original issue/error. $cordovaNetwork.isOnline()
type of undefined

**Comment by rigobcastro** [comment]
any solution?

**Comment by muthuspark** [comment]
This one worked for me, use <code>window.navigator.network.connection.type</code>
```
 document.addEventListener("deviceready", function() {
                var networkState = window.navigator.network.connection.type;
                if (networkState == Connection.NONE) {
                    $scope.nointernet = true;
                }
            }, false);


            document.addEventListener("offline", onOffline, false);

            function onOffline() {
                // Handle the offline event
            }

            document.addEventListener("online", onOnline, false);

            function onOnline() {
                // Handle the offline event
            }
```

**Comment by rigobcastro** [comment]
Ok, my error was because I had a code outside of the "$ionicPlatform.ready". Just is check all lines.

**Comment by gynekolog** [comment]
I had same problem. This plugin not work at browser, only on device. So instead:
`document.addEventListener("deviceready", function () {
  $cordovaPlugin.someFunction().then(success, error);
}, false);`

try 
`document.addEventListener("deviceready", function () {
if (window.cordova) {
  $cordovaPlugin.someFunction().then(success, error);
 }
}, false);`
