### ISSUE TITLE
Catch Cordova actions when using ionic serve

### ISSUE THREAD

**Issue by ivanmayes** [driftyco/ng-cordova#603]
Would be awesome if ngCordova would catch errors relating to Cordova functions when using the browser version of the app via ionic serve, would save a lot of design related time to be able to work in the browser of most pages without a splashscreen code error blocking the progress of the app.

**Comment by AdamVig** [comment]
As I understand it, the appropriate way to handle these types of errors is to wrap your calls for Cordova functions in conditionals that check for the Cordova plugin's existence:

    if (window.cordova && window.cordova.plugins.Keyboard) {
        // Do something
    }
I agree that it would be cool to have a preprocessor to handle this for you, but in the meantime, this is the way I have been dealing with it.
