### ISSUE TITLE
dash docset?

### ISSUE THREAD

**Issue by mez** [driftyco/ng-cordova#609]
Would be awesome if we could get docset for Dash!
Thoughts?

**Comment by pbernasconi** [comment]
That's a great idea, but I'm not sure I have the time to transfer the docs over to Dash, especially when we have our own site. thanks for the idea.

**Comment by genu** [comment]
A docket should be able to be generated from the html docs that are available.

Instructions are here: https://kapeli.com/docsets#dashDocset

I, for one, never really figured out how this is done (I also think those instructions aren't that clear as they could be), but if anybody out there wants to give it a go, it'll be awesome.
