### ISSUE TITLE
AppRate does not change app name in custom locale

### ISSUE THREAD

**Issue by Purus** [driftyco/ng-cordova#611]
The AppRate plugin does not work with custom locale as expected. The literal string '%@' does not get changed to the app name in the window.

```JavaScript
document.addEventListener("deviceready", function() {
    var customLocale = {};
    customLocale.title = "Rate %@";
    customLocale.message = "If you enjoy using %@, would you mind taking a minute to rate it? Thanks for your support!";
    customLocale.cancelButtonLabel = "No, Thanks";
    customLocale.laterButtonLabel = "Remind Me Later";
    customLocale.rateButtonLabel = "Rate It Now";

    var prefs = {
        appName: 'Designs',
        androidURL: 'market://details?id=com.iyaffgfgle.fgf'
    };

    $cordovaAppRateProvider.setCustomLocale(customLocale);
    $cordovaAppRateProvider.setPreferences(prefs)

}, false);
```

**Comment by pbernasconi** [comment]
Maybe try setting the preferences before the customlocale? I'm not sure I can help here -- seems like an issue with the plugin itself.

**Comment by Purus** [comment]
Changing the order doesn't help. The standalone plugin works as required, I believe.

**Comment by pdsullivan** [comment]
I was having a similar issue (ended up just calling the plugin directly). I am not sure but I think its because the `setPreferences` and `setCustomLocale` functions in `appRate.js` are not exposed (maybe not the right terminology) to be called.
