### ISSUE TITLE
AdMob Guide

### ISSUE THREAD

**Issue by Purus** [driftyco/ng-cordova#612]
The AdMob guide is not present. It would be good to share some example how to do this. I am not able to make it work based on the tips from Internet.

**Comment by mattheworres** [comment]
So, I just figured this out on Android, and it'd be really helpful if they added this to the guide.

1. Follow the main ngCordova guidelines: test on-device only, and wrap your plugin calls to ensure the device is ready
2. The ngCordova guide (despite being empty) is still wrong. ngCordova is using floatinghotpot's original admob plugin here: `https://github.com/floatinghotpot/cordova-plugin-admob`
3. In addition to having ngCordova installed, ensure you also add floatinghotpot's admob plugin itself :(ngCordova just acts as a wrapper to allow it to be injected into your Angular app): `cordova plugin add https://github.com/floatinghotpot/cordova-plugin-admob.git`
4. Ensure your AdMob account has a few ad units setup for whatever platforms you target.
5. After setting up the proper admobid object with banner/interstitial IDs for the platform you're on, call `createBannerView` with options as needed

```javascript
$cordovaAdMob.createBannerView({
        publisherId: admobid.banner,
        bannerAtTop: false, // set to true, to put banner at top
        overlap: false, // set to true, to allow banner overlap webview
        offsetTopBar: false, // set to true to avoid ios7 status bar overlap
        isTesting: false, // receiving test ad
        autoShow: true // auto show interstitial ad when loaded
      });
```

**Comment by mattheworres** [comment]
So, its worth noting the options I pass `createBannerView` doesn't include the interstitial ads.

This version of floatinghotpot's AdMob plugin leaves quite a bit to be desired, as it seems he's moved on to the re-written "pro" plugin instead. But, it's AdMob, and it works. So, there's that.
