### ISSUE TITLE
New Plugin

### ISSUE THREAD

**Issue by kapilkarda** [driftyco/ng-cordova#617]
Hello,

I want a plugin for youtube videos for download in all formats and All the feature that is used in youtube mobile.
Please help me

Thanks and Regards,
Kapil Karda

**Comment by pbernasconi** [comment]
@kapilkarda Can you provide the link for the plugin you want?

**Comment by kapilkarda** [comment]
This type of youtube downloader I want please have a look on it
http://en.savefrom.net/

Thanks and Regards,
Kapil Karda
