### ISSUE TITLE
Needed a function to copy an file other directory

### ISSUE THREAD

**Issue by josemadev** [driftyco/ng-cordova#619]
for example a photo like here:

  $scope.getPhoto = function() {
      console.log('Getting camera');
      Camera.getPicture().then(function(imageURI) {
        console.log(imageURI);
        $scope.lastPhoto = imageURI;
// I cant do this way or yes?
        // FileService.writeFile(dir,encodeURI(imageURI)).then(function(){
        //   alert("imagen guardada");
        // }, function(){
        //   alert("error al guardar");
        // });
      }, function(err) {
        console.err(err);
      }, {
        quality: 75,
        targetWidth: 320,
        targetHeight: 320,
        saveToPhotoAlbum: false
      });
    }

**Comment by gortok** [comment]
Not quite sure what you need to be added as a new feature. Can you go into more detail about the use case?

**Comment by josemadev** [comment]
I want to read the photo that i saved previously.
