### ISSUE TITLE
requestFileSystem

### ISSUE THREAD

**Issue by mixersoft** [driftyco/ng-cordova#622]
If you make this change, it will play nicer with the Chrome browser for desktop testing

`$window.requestFileSystem = $window.requestFileSystem || $window.webkitRequestFileSystem`

    function getFilesystem() {
      var q = $q.defer();
      try {
        $window.requestFileSystem($window.PERSISTENT, 1024 * 1024, q.resolve, q.reject);
      } catch (err) {
        q.reject(err);
      }
      return q.promise;
    }

**Comment by pbernasconi** [comment]
That's a good idea, I'll get on that. But since the File plugin is now using `window.resolveLocalFileSystemURL`, I'll use this instead:

```
window.resolveLocalFileSystemURL = window.resolveLocalFileSystemURL ||
                                   window.webkitResolveLocalFileSystemURL
```
