### ISSUE TITLE
Issue when checking if ng-app exists

### ISSUE THREAD

**Issue by mdimaculangan** [driftyco/ng-cordova#627]
Looks like we have issue checking if ng-app directive exists as angular.element will return an empty array when provided with a null value. Thus, we would always end up in the "else" part of the code.

if (angular.element(document.querySelector('[ng-app]')) === undefined) {
            injector = "document.body";
 }
 else {
            injector = "document.querySelector('[ng-app]')";
}
config.ecb = "angular.element(" + injector + ").injector().get('$cordovaPush').onNotification";

**Comment by pbernasconi** [comment]
It seems you're using an older version of ngCordova. Please update to the latest: `bower install ngCordova`
