### ISSUE TITLE
$cordovaPush : Cannot read property 'pushNotification' of undefined

### ISSUE THREAD

**Issue by Chris-c-09** [driftyco/ng-cordova#63]
Hello,
I'm try to use ngCordova for notifications. I get the following error :
TypeError: Cannot read property 'pushNotification' of undefined 
at Object.register (http://localhost/mobile/www/lib/ngCordova/dist/ng-cordova.js:827:27") => window.plugins.pushNotification

Below is my controller :

//test Push Notification cordova
.controller('PushCtrl', function($scope, $cordovaPush) {
    var androidConfig = {
        "senderId": "MySenderId"  
        "ecb": "onNotification"
    };

```
console.log('DEBUG CORDOVA PUSH ',$cordovaPush);

$cordovaPush.register(androidConfig).then(function(result) {
        //success
        console.log('DEBUG  ', result);
    }, function(err) {
        console.log('DEBUG  ', err);
    }

)

function onNotification(e) {
    $("#app-status-ul").append('<li>EVENT -> RECEIVED:' + e.event + '</li>');

    switch (e.event) {
        case 'registered':
            if (e.regid.length > 0) {
                $("#app-status-ul").append('<li>REGISTERED -> REGID:' + e.regid + "</li>");
                // Your GCM push server needs to know the regID before it can push to this device
                // here is where you might want to send it the regID for later use.
                console.log("regID = " + e.regid);
            }
            break;

        case 'message':
            // if this flag is set, this notification happened while we were in the foreground.
            // you might want to play a sound to get the user's attention, throw up a dialog, etc.
            if (e.foreground) {
                $("#app-status-ul").append('<li>--INLINE NOTIFICATION--' + '</li>');

                // on Android soundname is outside the payload. 
                // On Amazon FireOS all custom attributes are contained within payload
                var soundfile = e.soundname || e.payload.sound;
                // if the notification contains a soundname, play it.
                var my_media = new Media("/android_asset/www/" + soundfile);
                my_media.play();
            } else { // otherwise we were launched because the user touched a notification in the notification tray.
                if (e.coldstart) {
                    $("#app-status-ul").append('<li>--COLDSTART NOTIFICATION--' + '</li>');
                } else {
                    $("#app-status-ul").append('<li>--BACKGROUND NOTIFICATION--' + '</li>');
                }
            }

            $("#app-status-ul").append('<li>MESSAGE -> MSG: ' + e.payload.message + '</li>');
            //Only works for GCM
            $("#app-status-ul").append('<li>MESSAGE -> MSGCNT: ' + e.payload.msgcnt + '</li>');
            //Only works on Amazon Fire OS
            $status.append('<li>MESSAGE -> TIME: ' + e.payload.timeStamp + '</li>');
            break;

        case 'error':
            $("#app-status-ul").append('<li>ERROR -> MSG:' + e.msg + '</li>');
            break;

        default:
            $("#app-status-ul").append('<li>EVENT -> Unknown, an event was received and we do not know what it is</li>');
            break;
    }



}
```

});

Thank you in advance.
Kristi.

**Comment by nasht00** [comment]
I followed the ionic push tutorial and I get:
```
TypeError: Cannot read property 'pushNotification' of undefined
    at Object.register (ng-cordova.js:5685)
    at init (ionic-push.js:146)
    at ionic-push.js:309
    at new Q (ionic.bundle.js:22259)
    at Q (ionic.bundle.js:22246)
    at Object.register (ionic-push.js:270)
    at Scope.$scope.pushRegister (controllers.js:41)
    at $parseFunctionCall (ionic.bundle.js:21172)
    at ionic.bundle.js:53674
    at Scope.$eval (ionic.bundle.js:23228)
```

Is this the same issue?

**Comment by molerat619** [comment]
@nasht00 same thing for me

**Comment by molerat619** [comment]
I used it in the browser and had to set dev_push to true first, like this:

`ionic config set dev_push true`

**Comment by fabienthetis** [comment]
Check that the plugin Cordova: com.phonegap.plugins.PushPlugin" is installed in your project.

to check the list of plugin install : cordova plugin list

**Comment by blakedietz** [comment]
If you're coming here from using the ionic push tutorial @molerat619 's solution works.

**Comment by vdeep** [comment]
+1 for @molerat619 's solution

**Comment by argonavis80** [comment]
I had the same problem today after I restored my project on a second developer machine from source control. I found that the push plugin was missing in folder \platforms\android\assets\www\plugins. I deleted the android folder and did "ionic platform remove android". Then I added it again, build and voilà! Working now for me.

**Comment by fahimshekaib** [comment]
I can see cordova-plugin-console 1.0.2 "Console" using cordova plugin list.
the folder \platforms\android\assets\www\plugins also contains com.phonegap.plugins.PushPlugin which has www folder inside that PushNotification.js
I have added ngCordova as a dependency
Also have added app.run(function ($ionicPlatform, $cordovaPush, $rootScope) {...
I also tried ionic config set dev_push true

Ofcourse in browser it says Cannot read property 'pushNotification' of undefined

I still am getting **Class not found ** error alert on real Android device, because it is failing to register at $cordovaPush.register(androidConfig).then....

Any ideas?

**Comment by sryze** [comment]
I have the same problem in the browser, but @molerat619 solution didn't work for me. Is there another way to fix it?

**Comment by BeRMaNyA** [comment]
@sryze I just check if the plugin is available before the register logic...

```
if (window.plugins && window.plugins.pushNotification){
  $cordovaPush.register(config);
}
```
