### ISSUE TITLE
 ReferenceError: Can't find variable: device, /lib/ngCordova/dist/ng-cordova.js, Line: 1294

### ISSUE THREAD

**Issue by laravelian** [driftyco/ng-cordova#630]
Just started happening today after upgrading some packages.  halts the application completely.

I am testing on the device.

**Comment by pbernasconi** [comment]
Did you solve this error?

**Comment by laravelian** [comment]
I ended up starting from scratch again using ionic start <project> and bower install ngCordova, and copying the code over from my controllers and services.  I imagine that somehow my configuration or versions of installed npm and/or bower packages were causing a conflict. 

Starting clean worked to resolve the issue, so I'm not sure what the exact cause was.

**Comment by pbernasconi** [comment]
Okay good to know. Do you think it was an issue with ngCordova, or more with how your configured your dependencies?

**Comment by laravelian** [comment]
Likely a dependency issue.  The issue started after updating Ionic, so I decided to do a full npm update to make sure I was at the latest versions of everything and the issue persisted.  Because starting fresh fixed the issue, I'm not sure exactly which dependency it was.

**Comment by jregele** [comment]
I started running into the same issue after I upgraded to Sierra to get another cordova plugin to build. I had to upgrade ionic and cordova which is when the problem started happening. I tried uninstalling and reinstalling, but still no luck.

I'm on
ionic 1.7.4
cordova 6.0.0
cordova-plugin-device 1.1.4
