### ISSUE TITLE
Documentation error  param file in the explanation = directory. This ocurred error more times

### ISSUE THREAD

**Issue by josemadev** [driftyco/ng-cordova#633]
createFile(path, file, replace)

Check if a file exists in a certain path, directory.

Param	Type	Detail
path	FileSystem	Base FileSystem. Please refer to the iOS and Android filesystems above
directory	String	Name of file to create
replace	Boolean	If true, replaces file with same name. If false returns error
Returns Object

**Comment by pbernasconi** [comment]
Thanks for raising the issue. Fixed now!
