### ISSUE TITLE
backgroundGeolocation - Detailed sample requested

### ISSUE THREAD

**Issue by pharindoko** [driftyco/ng-cordova#636]
Hey,
I would need a sample how to use backgroundGeolocation with Ionic

I`ve read the guide for backgroundGeolocation
http://ngcordova.com/docs/plugins/backgroundGeolocation/

1. added cordova plugin from the source provided
2. I put the code provided into my Controller and surrounded it with . The template and controller itself work.
 
 .controller('TrackingCtrl', function($scope, $cordovaGeolocation, $cordovaBackgroundGeolocation,$ionicPlatform) {

     var options = {
        desiredAccuracy: 10,
        stationaryRadius: 20,
        distanceFilter: 30,
        debug: true // <-- enable this hear sounds for background-geolocation life-cycle.
    };
$ionicPlatform.ready(function() {
    $cordovaBackgroundGeolocation.configure(options)
        .then(function(res) {
                console.log(res);
            },
            function(err) {
                console.log(err);
            });
});
})

- But I get the error "$window.plugins is undefined" - ok it`s clear that I get this error in the browser ok.

- I`m using appbuilder to take the www-folder to include my sources and test it in the appbuilder app on ios 8. Camera and Geolocation Plugin already work as expected.

- I tested the www-folder provided in the SampleApp folder of the plugin "org.transistorsoft.cordova.background-geolocation"--> this works on ios 8 in appbuilder app

What else I should check. As it is a custom cordova plugin do I need to attach anything e.g.
The plugin itself to appbuilder or a js file.

**Comment by gortok** [comment]
the plugin does need to be included through normal cordova means.
