### ISSUE TITLE
$cordovaMedia is prone to race conditions, and might cause issues already

### ISSUE THREAD

**Issue by Morriz** [driftyco/ng-cordova#639]
Hi, I have some issues with ngCordova plugins, and Media in particular.

I see only one promise being returned with $cordovaMedia.newMedia creation, while all the class methods rudely assume the media instance to be ready...this is inconsistent with the rest of the plugins and might be causing a lot of unforeseen errors and problems. I advice you to use a consistent approach in all plugins, making sure resolution is in order.

Anyway, the $cordovaMedia plugin is never calling it's success handler, as would be expected, but this is not your fault, since your simply wrapping Media's own callback.

But a bigger problem is that the documentation is wrong, as the ".then" does NOT return the same promise as the newMedia method returns. Too bad folks are losing time over this.
So please change the line with new Media to 

      media = $cordovaMedia.newMedia(sound);
      media.then(function() { ...

Anyways, I love open source, but it gives me a lot of headaches when documentation is flaky....but I get the fact that it's mostly due to developers stamping out many new handy features :)

**Comment by kdubuc** [comment]
thanks man ! i was stucked with an incomprehensible error, and your post save my time !

**Comment by quanghoc** [comment]
+1

**Comment by Morriz** [comment]
I advise using Media directly, as $cordovaMedia is flaky and only promisifying Media. Well, trying to ;p
