### ISSUE TITLE
$cordovaSocialSharing - posting pre-written messages to facebook not working

### ISSUE THREAD

**Issue by unaor** [driftyco/ng-cordova#640]
im using the shareViaFacebookWithPasteMessageHint to post a prefilled text and an image
the function does open the facebook share window and i can paste my pre filled code but the image is nowhere to be seen

i just updated my cordova version and removed and reinstalled the plugin but still no image

here is the relevant code

var message ="See Baykus Ecosystem www.baykus.com";	
		var image ='https://www.flickr.com/photos/gseloff/15856295854/in/explore-2015-02-09';
		var link = 'http://baykus.com';

		$cordovaSocialSharing
	    .shareViaFacebookWithPasteMessageHint(message,image,null,'Message pasted to clip board ,press on the area to paste it in the feed')
	    .then(function(result) {
	    	console.log(result);

**Comment by gortok** [comment]
Could you include a project that reproduces this issue with the latest versions?
