### ISSUE TITLE
$cordovaPush can not work

### ISSUE THREAD

**Issue by smallg** [driftyco/ng-cordova#641]
I follow the ngCordova $cordovaPush documents to implement push notification.
the code like this:
```
angular.module('starter', ['ionic', 'ngCordova', 'starter.controllers', 'starter.services'])
.run(function ($ionicPlatform, $cordovaToast, $cordovaPush, $rootScope) {
var androidConfig = {
            "senderID": "bionic-path-854" //https://console.developers.google.com/project/bionic-path-854?quickstart=1
        };
document.addEventListener("deviceready", function(){
            $cordovaPush.register(androidConfig).then(function(result) {
                // Success
                $cordovaToast.showShortCenter(result);
            }, function(err) {
                // Error
                $cordovaToast.showShortCenter(err);
            });

            $rootScope.$on('$cordovaPush:notificationReceived', function(event, notification) {
                switch(notification.event) {
                    case 'registered':
                        if (notification.regid.length > 0 ) {
                            alert('registration ID = ' + notification.regid);
                        }
                        break;

                    case 'message':
                        // this is the actual push notification. its format depends on the data model from the push server
                        alert('message = ' + notification.message + ' msgCount = ' + notification.msgcnt);
                        break;

                    case 'error':
                        alert('GCM error = ' + notification.msg);
                        break;

                    default:
                        alert('An unknown GCM event has occurred');
                        break;
                }
            });
        }, false);
});
```

when i run this app in actual mobile, the app only show ok message, not registration ID information.
So, what's wrong about this?

**Comment by smallg** [comment]
I also create project in google developers console, and open "Google Colud Messaging for Android" apis.
![image](https://cloud.githubusercontent.com/assets/225962/6184378/f5b40e58-b39b-11e4-8229-e9325e302e0d.png)

**Comment by smallg** [comment]
the project id like this:
![image](https://cloud.githubusercontent.com/assets/225962/6184388/0eb2d600-b39c-11e4-9f1a-5697385ed438.png)

**Comment by smallg** [comment]
![image](https://cloud.githubusercontent.com/assets/225962/6202312/be2299fa-b51c-11e4-9ae9-f2b8096124d9.png)
I found project number and instead of project id. but it's still not work.
Only return "OK" result.

**Comment by romaluca** [comment]
I have the same problem. After ok message the app crash before get the regiId

**Comment by j4ml3t** [comment]
Same problem, I cannot manage to receive the event.

**Comment by sydneyhenrard** [comment]
Your `senderId` is the project number and not the project ID. You should receive the regId. It works fine.

**Comment by smallg** [comment]
Somebody have good idea to fix this?

**Comment by Strnadj** [comment]
Try register push recv handler before you call google api, not sure if it help, but everything is possible ...

```javascript
angular.module('starter', ['ionic', 'ngCordova', 'starter.controllers', 'starter.services'])
  .run(function ($ionicPlatform, $cordovaToast, $cordovaPush, $rootScope) {
    var androidConfig = {
      "senderID": "bionic-path-854" //https://console.developers.google.com/project/bionic-path-854?quickstart=1
    };
        
    $rootScope.$on('$cordovaPush:notificationReceived', function(event, notification) {
      switch(notification.event) {
        case 'registered':
          if (notification.regid.length > 0 ) {
            alert('registration ID = ' + notification.regid);
          }
          break;

        case 'message':
          // this is the actual push notification. its format depends on the data model from the push server
          alert('message = ' + notification.message + ' msgCount = ' + notification.msgcnt);
          break;

        case 'error':
          alert('GCM error = ' + notification.msg);
          break;

        default:
          alert('An unknown GCM event has occurred');
          break;
      }
    });
    
    document.addEventListener("deviceready", function(){
      $cordovaPush.register(androidConfig).then(function(result) {
        // Success
        $cordovaToast.showShortCenter(result);
      }, function(err) {
        // Error
        $cordovaToast.showShortCenter(err);
      });
    }, false);
});
```

**Comment by Strnadj** [comment]
Maybe you should put handler registration into device ready listener, I use some example from my source code, but I start angular after device is ready..

**Comment by j4ml3t** [comment]
Take a look at this post: http://stackoverflow.com/questions/28677612/android-pushnotifications-with-pushplugin-on-emulator/28681145#28681145/

**Comment by smallg** [comment]
@j4ml3t  ok, I will try it, thanks.

**Comment by MayankLogiciel** [comment]
instead of project-id use project number in senderID

**Comment by smallg** [comment]
@MayankLogiciel I already instead this number, but still can not work.
https://github.com/smallg/ionic-plugin-test/blob/master/www/js/app.js

**Comment by ajhades** [comment]
Hi, I had the same problem and i had solve it so ...

**androidConfig** the object adds the **ecb** point to a function like "http://stackoverflow.com/questions/28677612/android-pushnotifications-with-pushplugin-on-emulator/28681145#28681145/" and what I did is to use 
```javascript
$rootScope.$broadcast('any_event_to_like.'); 
```
to trigger an event when you register or a message arrives, etc

...sorry for my bad English

**Comment by ajhades** [comment]
Hi, I had the same problem and i had solve it so ...

**androidConfig** the object adds the **ecb** point to a function like "http://stackoverflow.com/questions/28677612/android-pushnotifications-with-pushplugin-on-emulator/28681145#28681145/" and what I did is to use 
```javascript
$rootScope.$broadcast('any_event_to_like.'); 
```
to trigger an event when you register or a message arrives, etc

...sorry for my bad English

**Comment by smallg** [comment]
@ajhades can you show gcm server code for me?
my code in there https://github.com/smallg/ionic-plugin-test/blob/master/gcm-server/gcm-server.js
Thank you very much.

**Comment by MayankLogiciel** [comment]
// At least one reg id required
registrationIds.push('bionic-path-854');

bionic-path-854 is not a registration Id.
You will get registration id when following case get executed from within your code

case 'registered':
                        if (notification.regid.length > 0) {
                            alert('registration ID = ' + notification.regid);
                        }
                        break;


notification.regid is what to be supposed to put there in your server code instead of bionic-path-854. On successful registration you need to send this registration id to your server so that in future your server can send notifications to this registration id.

**Comment by ajhades** [comment]
Hello,
This is the code I'm using PHP, I have taken from a template but worked well.
https://github.com/ajhades/gcm-example-php/blob/master/example.php

I hope it's helpful

regards

**Comment by bnorrell** [comment]
Had exact same problem, replacing "$cordovaPush:notificationReceived" with "pushNotificationReceived" worked for me.  Hope that helps someone else.

**Comment by hlopezvg** [comment]
@bnorrell Thank you, that did the trick for me.

**Comment by murali013** [comment]
I tried to get the device token inside the  $cordovaPush.register() function. I have copied the code below

var config;
        if (ionic.Platform.isAndroid()) {
            config = {
               "senderID": "644284191156", // REPLACE THIS WITH YOURS FROM GCM CONSOLE - also in the project URL like: https://console.developers.google.com/project/434205989073
               "ecb": "function_to_be_called"
            };
        }
        else if (ionic.Platform.isIOS()) {
            config = {
                "badge": "true",
                "sound": "true",
                "alert": "true"
            }
        }

$cordovaPush.register(config).then(function(deviceToken) {
          // Success -- send deviceToken to server, and store for future use
          console.log("deviceToken: " + deviceToken)
          alert(deviceToken);
          //$http.post("http://server.co/", {user: "Bob", tokenID: deviceToken})
        }, function(err) {
          alert("Registration error: " + err)
        });

 $cordovaPush.register(config) is not working.

Please help me to get the device token.

Thanks in advance.

**Comment by gortok** [comment]
You're using the deprecated plugin; try it with $cordovaPushV5 and let me know how it goes?

**Comment by murali013** [comment]
Hello Gortok,

I have used the  $cordovaPushV5  and its works fine. Thanks lot.
