### ISSUE TITLE
How to locked screen orientation?

### ISSUE THREAD

**Issue by smallg** [driftyco/ng-cordova#646]
In my app, I want lock game page to horizontal.
And only this page is horizontal, which plugin implement this function?

Thank you.

**Comment by mebibou** [comment]
net.yoik.cordova.plugins.screenorientation

**Comment by smallg** [comment]
Thank you @mebibou, but I want lock one page only, other page still use sensor mode.

**Comment by Strnadj** [comment]
@smallg If you want to lock your screen dynamically use plugin, but if you want to lock your screen for whole app use Cordova Directive in config.xml:

```xml
<preference name="orientation" value="portrait/landscape" />
```

**Comment by smallg** [comment]
@Strnadj 
I think this config use all pages in one app.
I only want set one page to landscape.

**Comment by Strnadj** [comment]
@smallg Ok, I didn't notice that, but it can help to some other people later :)

**Comment by mebibou** [comment]
@smallg you could lock the screen when you enter the page and unlock it when you leave the page, couldn't you?

**Comment by smallg** [comment]
@mebibou

**Comment by mebibou** [comment]
@smallg I would suggest you use the `$stateProvider`, attach a controller to the url where the page is, and in the controller you lock the screen. There's also probably a way to know when you leave the page / the controller gets unloaded or something

**Comment by smallg** [comment]
Ok, I will try it.
Thank you, @mebibou

**Comment by smallg** [comment]
I use this event to watch url changed, and change screen mode.
The '/tab/chats/' means '/tab/chats/11' or '/tab/chats/12', this is chats detail page, I need set landscape mode.
Other page use mobile mode.
```
$rootScope.$on('$locationChangeSuccess', function (event, newUrl, oldUrl) {
                if(newUrl.indexOf('/tab/chats/')>0){
                    screen.lockOrientation('landscape');
                }
                if(oldUrl.indexOf('/tab/chats/')>0){
                    screen.unlockOrientation();
                }
            });
```

**Comment by Gajotres** [comment]
You can do it using Ionic view events now.

To do it only on selected pages, use this code inside an appropriate page controller:

$scope.$on('$ionicView.beforeEnter', function(){
    screen.lockOrientation('landscape');
});
If executed in a right controller this code will trigger orientation lock before the view becomes visible.

Read this if you want to find out more: http://www.gajotres.net/changing-locking-screen-orientation-in-ionic-application/

**Comment by anuragranjan242** [comment]
selected page only------------
$scope.$on('$ionicView.beforeEnter', function(){
    screen.lockOrientation('landscape');
});

**Comment by d1b1** [comment]
I am finding that this solution does not work, I have tried it in the Device Ready function at startup and on specific pages. Is there another way to lock the orientation?

**Comment by mebibou** [comment]
@d1b1 to lock the screen completely you can do it in the `config.xml`, but if you want to lock it on specific pages then you should use the plugin which should work. I think you should post an issue on the plugin directly
