### ISSUE TITLE
How to get the free disk space? (Question)

### ISSUE THREAD

**Issue by nikolayhg** [driftyco/ng-cordova#649]
How to get the free disk space for a folder?

The file plugins does not offer such methods.

**Comment by nraboy** [comment]
Does something like this help you out?:

https://blog.nraboy.com/2015/02/get-available-free-disk-space-using-apache-cordova/

Regards,

**Comment by nikolayhg** [comment]
yes, this works. It would be great if there was a cleaner version, like ``$cordovaFile.getFreeDiskSpace()`` ?

**Comment by nraboy** [comment]
I'll see about making a pull request on the project and adding one for you tonight or tomorrow.  Regardless it would still require callbacks since it is an asynchronous function.

**Comment by nraboy** [comment]
Created a pull request for this function found at https://github.com/driftyco/ng-cordova/pull/658

**Comment by nikolayhg** [comment]
great! Thank you @nraboy !

**Comment by nraboy** [comment]
@pbernasconi you can close this ticket now.
