### ISSUE TITLE
Allow options object for sqlitePlugin

### ISSUE THREAD

**Issue by SebastianRolf** [driftyco/ng-cordova#651]
What would be the best way to switch to the recommended method to open a database with the options object?

See: https://github.com/brodysoft/Cordova-SQLitePlugin#opening-a-database

I created a branch and a new method to try it out. Works fine in my project, and I can now use prepopulated databases that are distributed with the app.

**Comment by SebastianRolf** [comment]
Added pull request #653

**Comment by Honza-R** [comment]
This issue should be fixed, the current code behaves bad when used as shown in the documentation - passing the object to $cordovaSQLite.openDB leads to using a JSON string built from this object to be used as a filename for the database. This leads to various problems and makes it impossible to open a SQLCipher database properly.
