### ISSUE TITLE
ngCordova 0.1.12-alpha does not contain $cordovaFile.moveFile

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [driftyco/ng-cordova#656]
All is in the title

**Comment by Takkuz** [comment]
Do you use the .zip package or the bower version? Because Bower ones is outdated, minified or not. I was having same issue with "checkDir" and "moveDir", downloading the zip solves it.

**Comment by Yonn-Trimoreau** [comment]
Thank you for your reply, I managed to add moveFile method by copying it from raw of last version that contained it ;)

**Comment by Yonn-Trimoreau** [comment]
But still, this is an issue ;)

**Comment by ranrolls** [comment]
For me whole $cordovaFile is not working

angular.module('root')
	.controller('CordovaFileCtrl', ['toastr','$scope', '$ionicPlatform', '$cordovaFile', 'GlobalSettings', 'DSCacheFactory', CordovaFileCtrl]);


// $cordovaFile.getFreeDiskSpace()
							  // .then(function (success) {
									// // success in kilobytes
									// toastr.success('Operation Success');
									// // toastr.info(sucess);
									// // vm.result = success;
							  // }, function (error) {
									  // // error
									// toastr.error('Operation Fail');
									// // toastr.info(error);
									// // vm.result = error;
							  // });
