### ISSUE TITLE
Background GeoLocation:  Premium Version

### ISSUE THREAD

**Issue by christocracy** [driftyco/ng-cordova#662]
Hello, I'm the plugin author of cordova-background-geolocation.  

I've refactored Android significantly.

- much improved battery efficiency.
- no more in-plugin HTTP.  Now execs js callback just like ios.
- Android performance is as good or better than ios now.

The plugin now exists in a private repo.  ios will continue to be supported in free repo.  New Android development will occur only in non-free repo.

http://christocracy.github.io/cordova-background-geolocation/

**Comment by gortok** [comment]
That's great! Thanks.  We'll have to continue to use the free version for obvious reasons; thanks for your effort. I'm disappointed your work isn't licensed in a fashion where we can include it in an open source project; but I understand your position.

**Comment by christocracy** [comment]
People don't need an angular wrapper to use the premium version.

I've built an ionic-based SampleApp using the standard Cordova plugin.

https://github.com/christocracy/cordova-background-geolocation-SampleApp
