### ISSUE TITLE
readme linking to evothings/cordova-ble but src/plugins/ble.js is different

### ISSUE THREAD

**Issue by userfive** [driftyco/ng-cordova#665]
The readme is linking to evothings/cordova-ble but src/plugins/ble.js links to https://github.com/don/cordova-plugin-ble-central#:/plugin

Which plugin are we using?

**Comment by dwimberger** [comment]
evothings/cordova-ble states 

    Cordova versions 4.0.0 and later are not supported.

https://github.com/don/cordova-plugin-ble-central#:/plugin

This one works and is referenced from the source, so I made a Pull Request #751 to correct the link in the Readme.
