### ISSUE TITLE
Keep getting Authentication error with Oauth Twitter call

### ISSUE THREAD

**Issue by brianvandelden** [driftyco/ng-cordova#671]
Response [{"code":32,"message":"Could not authenticate you."}]}

After this call:
$http({method: "post", url: "https://api.twitter.com/oauth/request_token",data: "oauth_callback=http://localhost/callback" })

See also line 5180 in ng-cordova.js

Any idea?

**Comment by nraboy** [comment]
Please see here:

https://github.com/nraboy/ng-cordova-oauth/issues/45

I need to push the changes to ngCordova official still.  In the mean time, check if that version of the library corrects your problem.

Regards,

**Comment by ivanbtrujillo** [comment]
Hi guys, i have the same problem with Twitter (Facebook and G+ works fine). I've installed last version of oAuth from nraboy repo (I have already readed the other issue: https://github.com/nraboy/ng-cordova-oauth/issues/45) . I also have checked that the library have the correction of the issue, passing oauth_callback as a body param (ng-cordova-oauth.js line 534):
```
$http({
    method: "post",
    url: "https://api.twitter.com/oauth/request_token",
    headers: {
        "Authorization": signatureObj.authorization_header,
        "Content-Type": "application/x-www-form-urlencoded"
    },
    data: "oauth_callback=" + encodeURIComponent("http://localhost/callback")
})
```

My code is very simple (i'm just testing basic functionality):

Controller:
```
//Twitter
  var consumerKey = 'xxxMyConsumerKeyxxx';
  var consumerSecretKey = 'xxxMySecretKeyxxx';

  $scope.twitterLogin = function() {
      $cordovaOauth.twitter(consumerKey, consumerSecretKey).then(function(result) {
          alert( " Succesfull got token: "+result);
      },function(err){
          alert("Unable to connect to twitter: "+JSON.stringify(err));
     });
  } 
```
On the html file, I just have a button with calls the twitterLogin function via ng-click="twitterLogin()".

I also have checked that my consumerKey and secretKey work fine. I have builded a simple webapp using passport, express and node for testing it.

Any idea?

Thanks!

**Comment by nraboy** [comment]
It should work.  I tested it multiple times with code not too different than yours.

Please make sure you are not using Phonegap Build, ionic serve, or live-reload.  You need to do a full build and install with none of the convenience tools that are floating around.

**Comment by brianvandelden** [comment]
Fixed! Thanks!

**Comment by nraboy** [comment]
Great!

**Comment by nraboy** [comment]
@pbernasconi you can close this ticket now.

**Comment by lintangarief** [comment]
hy nraboy ,

i have question about login twitter with ng-cordova auth. but result, just show token and screen name. how to get email user after get token and screen name ?

**Comment by nraboy** [comment]
Oauth is for getting access tokens to the Twitter API.  If you want to get data from Twitter you'll have to use the oauth token with their APIs.  I encourage you to read their documentation for what you're looking for.

Best,

**Comment by alacret** [comment]
Any luck with this? my code is:
    $cordovaOauth.twitter(TWITTER_API_SECRET, TWITTER_CONSUMER_KEY).then(function(s){
      window.alert("S");
    },function(e){
      if (!e.errors){
        return;
      }
      var e = e.errors;
      for (var i =  0; i < e.length; i++) {
          var error = e[i];
          window.alert(error.code + ":" + error.number + ":" + error.message);
      }
    });

But i keep getting this error: 32: Could not authenticate you
