### ISSUE TITLE
cordovaPush.register() function is hanging when "notifications" are turned off in iOS

### ISSUE THREAD

**Issue by ranjitpandit** [driftyco/ng-cordova#672]
I have run into an issue when notifications are turned off in iOS settings for my app, cordovaPush.register() function call hangs without success or failure. 

Any ideas?

**Comment by tharrington** [comment]
have you solved this issue?

**Comment by lookitsatravis** [comment]
+1. I'm having this exact issue now.

**Comment by joeyrobert** [comment]
Seeing this issue as well. I would think the correct behaviour would be to reject the `$cordovaPush.register()` promise.
