### ISSUE TITLE
$cordovaDialogs.prompt does not show keyboard on iOS

### ISSUE THREAD

**Issue by sean-hill** [driftyco/ng-cordova#674]
When you use `$cordovaDialogs.prompt()` the keyboard is not shown on iOS, you have to click into the prompt dialog to show the keyboard, which is not how the native prompt works (it shows the keyboard)

**Comment by gortok** [comment]
Can you include a reproduction of this issue that we can use to test?  I'll be happy to re-open this then.

**Comment by igor9silva** [comment]
I have the same problem on both iOS and Android.
When the prompt is shown, the EditText does not gain focus.

**Comment by mkurzweil** [comment]
I have the same problem as @igor9silva.

cordova version --> 5.0.0
cordova platforms --> android 4.0.0.0, iOS 4.0.0.0
tested device --> android 5.0.2

           `$scope.changeAuthorizationLevel= function(authLevelChange){
            
            var authLevel = Shared.getAuthorizationLevel();
            var defaultText = "XXXXXX"
            var message = "XXXXXXX";
            var title = "XXXXXX"
            var buttonNames = ['Ok','Cancel'];
            var errorAuthMode = 'XXXXXXXX';

            //toggle active to the home button
            $scope.activeMenu = "Home";
            if(authLevelChange==2 || authLevelChange==3){
                $cordovaDialogs.prompt(message, title ,buttonNames , defaultText)
                    .then(function(result) {
                        var userInput = result.input1;
                        // no button = 0, 'OK' = 1, 'Cancel' = 2
                        var btnIndex = result.buttonIndex;
                        if(btnIndex == 1){
                            if(currentDevice.acl2key==userInput){
                                Shared.setAuthorizationLevel(2);
                                $scope.authLevel = Shared.getAuthorizationLevel();
                                toggleSidemenuWithID('#settings');
                                $scope.$emit('auth:updated', 'settings')
                            } else if(currentDevice.acl3key==userInput){
                                Shared.setAuthorizationLevel(3);
                                $scope.authLevel = Shared.getAuthorizationLevel();
                                toggleSidemenuWithID('#settings');
                                $scope.$emit('auth:updated', 'settings')
                            } else{
                                $cordovaDialogs.alert(errorAuthMode, 'Error', 'Ok');
                            }
                        }
                    });
            } 
        };`

**Comment by igor9silva** [comment]
@mkurzweil I ended up writing my own `cordova-plugin-dialogs` fork.

**Comment by mkurzweil** [comment]
@igor9silva thx for your suggestion.
I tried to combine `cordova-plugin-dialogs` and `ionic-plugin-keyboard`. Is there a opportunity to check that the dialog is successfully open?

**Comment by igor9silva** [comment]
@mkurzweil as I know, the dialog should always be successfully open when you call `$cordovaDialogs.prompt()` or `navigator.notification.prompt()`. About the keyboard, I don't think you'll be able to set focus into the EditText through JavaScript, that's why a fork is necessary.

**Comment by Thul999** [comment]
I still have the same issue with Android, does anyone have a suggestion?

**Comment by igor9silva** [comment]
wow people still using it
