### ISSUE TITLE
Update $cordovaLocalNotification

### ISSUE THREAD

**Issue by GIANTCRAB** [driftyco/ng-cordova#677]
Hello, 

@katzer/cordova-plugin-local-notifications has been recently updated and has some breaking changes. Please update ngCordova $cordovaLocalNotification.

Thank you.

**Comment by A1iAshoor** [comment]
+1

**Comment by DanailMinchev** [comment]
I have created pull request. I will update the docs with another pull request.

**Comment by increos** [comment]
Sorry if this has been answered...but has update happened ?

**Comment by DanailMinchev** [comment]
@increos 
No, my pull request is not merged yet.

However, there is partial update, which is merged.
Described here: https://github.com/driftyco/ng-cordova/issues/721

**Comment by increos** [comment]
@DanailMinchev  Thanks for the response. Adding my +1

**Comment by DanailMinchev** [comment]
@GIANTCRAB the pull request is merged. You can close the issue now.
Thank you!
