### ISSUE TITLE
cordovaFile error message

### ISSUE THREAD

**Issue by benwingz** [driftyco/ng-cordova#681]
Hey guys, I was trying to use cordovaFile plugin in order to upload pictures with my app and I get always the same error code 5 (Encoding problem said the doc). Is anybody already have this issue ?

**Comment by ranrolls** [comment]
I am unable to use $cordovaFile service provided by ngCordova.

Can u help with it.

Thanks in advance.

**Comment by benwingz** [comment]
Can you be more specific ?
(If your plugin is well installed don't forgot to load it in your dependancies in the beggining of your controller) like this:

angular.module('myModule')
.controller('MyCtrl', function($scope, $cordovaFile) { ...
