### ISSUE TITLE
Error: No such database, must open it first

### ISSUE THREAD

**Issue by Trexology** [driftyco/ng-cordova#683]
using ousenUI
After the deviceReady Listener events, i called for

 function checkScope() {
            alert("device ready");

            //DOES NOT WORK
            var db = $cordovaSQLite.openDB({
                name: "myDB.db",
            });

            //WORKS
            var db = window.sqlitePlugin.openDatabase({
                name: "myDB.db",
            });

            var query = "SELECT bla bla bla";
            $cordovaSQLite.execute(db, query, []).then(function(res) {
                alert("Result length: " + res.rows.length);
                alert("Result[0] name: " + res.rows.item(0).en_name);
            }, function(err) {
                alert(err);
            });
}

I got a error message when using the $cordovaSQLite.openDB but NOT when using the manual window.sqlitePlugin.openDatabase.

SQL statement is correct and $cordovaSQLite is added to the controller. Is this a bug or does it not work with OusenUI?

**Comment by beauby** [comment]
The problem comes from `$cordovaSQLite`'s `openDB` method #719. It should be called as:
   $cordovaSQLite.openDB("myDB.db")
instead of
   $cordovaSQLite.openDB({ name: "myDB.db" })
The example on the website is misleading (and wrong).
