### ISSUE TITLE
0.1.12-alpha release version different from the master branch and the documentation.

### ISSUE THREAD

**Issue by alfredooo** [driftyco/ng-cordova#686]
Hi all,
ng-cordova is great!

I noticed that the 0.1.12-alpha release version is retrieving a file that is different from the master branch.
and both are: * v0.1.12-alpha, in addition the latest documentation is refering to the master code and not to the code that is tagged and being used by bower.

here are the two files and they are different:
https://github.com/driftyco/ng-cordova/blob/v0.1.12-alpha/dist/ng-cordova.js
https://github.com/driftyco/ng-cordova/blob/master/dist/ng-cordova.js

Best,
Alfredo.

**Comment by gortok** [comment]
Is this still happening?
