### ISSUE TITLE
append is not working when writing file

### ISSUE THREAD

**Issue by sydneyhenrard** [driftyco/ng-cordova#687]
I use the cordovaFile plugin (v0.1.12-alpha) to write logs into a debug file. I tried using the append option but it seems it's not working because I always get the last log in the file. `debug1.txt` and `debug2.txt` have the same content.

```
$cordovaFile.writeFile('debug1.txt', logMessage, {append: true})
	.then(function (success) {
		console.log('success write');
		console.log(success);
		// success
	}, function (error) {
		// error
		console.log('error write');
		console.log(error);
	});
$cordovaFile.writeFile('debug2.txt', logMessage)
	.then(function (success) {
		console.log('success write');
		console.log(success);
		// success
	}, function (error) {
		// error
		console.log('error write');
		console.log(error);
	});
```

**Comment by ranrolls** [comment]
for me whole $cordovaFile is not working. I am using ionic and ngCordova. My solution to problem was using 

                                                 cordova.exec(function(result) {
							// alert("Free Disk Space: " + result);
							toastr.info(result);
						}, function(error) {
							// alert("Error: " + error);
							toastr.info(error);
						}, "File", "getFreeDiskSpace", []);


My previous code which is not working for me is below. You can see I have used almost everything to come out of this problem. But I am still unable to use $cordovaFile......() .  Can you help me with this.

angular.module('root')
	.controller('CordovaFileCtrl', ['toastr','$scope', '$ionicPlatform', '$cordovaFile', 'GlobalSettings', 'DSCacheFactory', CordovaFileCtrl]);

                                                      // $cordovaFile.getFreeDiskSpace()
							  // .then(function (success) {
									// // success in kilobytes
									// toastr.success('Operation Success');
									// // toastr.info(sucess);
									// // vm.result = success;
							  // }, function (error) {
									  // // error
									// toastr.error('Operation Fail');
									// // toastr.info(error);
									// // vm.result = error;
							  // });
  Can you help me with this.

Thanks in advance

My email is greatwebist@outlook.com
