### ISSUE TITLE
`$cordovaPush:notificationReceived` event not broadcasted

### ISSUE THREAD

**Issue by leonsas** [driftyco/ng-cordova#693]
As per the [docs](http://ngcordova.com/docs/plugins/pushNotifications/), I was trying to listen for notifications using:
`$rootScope.$on('$cordovaPush:notificationReceived', func(event, notification))`, which just wouldn't work.
Replacing that to listen for the `pushNotificationReceived` instead made it work for me. So I'm calling:
`$rootScope.$on('pushNotificationReceived', func(event, notification))` and the listener successfully works.

Not sure if the docs are wrong, or if I'm doing something wrong on my side so I figured I post here.

**Comment by Fayozjon** [comment]
Leon

http://miyonline.net/dollar

23.03.2015, 22:49, "Leon Sasson" <notifications@github.com>:As per the , I was trying to listen for notifications using:As per the , I was trying to listen for notifications using:
$rootScope.$on('$cordovaPush:notificationReceived', func(event, notification)), which just wouldn't work.
Replacing that to listen for the pushNotificationReceived instead made it work for me. So I'm calling:
$rootScope.$on('pushNotificationReceived', func(event, notification)) and the listener successfully works.

Not sure if the docs are wrong, or if I'm doing something wrong on my side so I figured I post here.

**Comment by KevinGurden** [comment]
I too am listening for $cordovaLocalNotification:clicked but it never get broadcast

**Comment by ArnaudSpanneut** [comment]
@leonsas Which version of ngCordova do you use?
Event name has changed on 0.1.11-alpha version.
[CHANGELOG](https://github.com/driftyco/ng-cordova/blob/master/CHANGELOG.md#push-notifications)

**Comment by KevinGurden** [comment]
I've just realised I'm talking about LocalNotifications not
PushNotifications. I'm on the 0.1.0

**Comment by leonsas** [comment]
I'm on the 0.1.8-alpha, so it makes sense that I still need to use `pushNotificationReceived`.

**Comment by bruno-serfe** [comment]
Hey Guys I've tried both ways and nothing works.. this is still an issue? I've followed this article but I cannot get the device resgistration id.

**Comment by KevinGurden** [comment]
Bruno, it was a while ago but I did get it working (LocalNotifications). I
don't have the working code anymore I'm afraid.
Kevin

**Comment by bruno-serfe** [comment]
Hi Kevin, thanks anyway, I've found the solution using this new plugin from phonegap https://github.com/phonegap/phonegap-plugin-push I hope this also works for others.

Best regards,

**Comment by gortok** [comment]
@bruno-serfe I added support for the new plugin in #984, also covered in issue #963.

**Comment by gortok** [comment]
Closed with the resolution of #963.
