### ISSUE TITLE
$cordovaNetwork is not working

### ISSUE THREAD

**Issue by mainalikishan** [driftyco/ng-cordova#70]
$cordovaNetwork  is not working. When I did "alert(JSON.stringify($cordovaNetwork));", It is returning "{}" in ios. Not tested in android though.

**Comment by landed1** [comment]
It's maybe not related but I have found in the browser of desktop this doesn't cause an issue...however on a device this causes some js error halting the block of code.

So I have to do this to get some initial device testing working
    //if ((navigator.connection && $cordovaNetwork.isOnline()) || !navigator.connection) {
    if (navigator.connection) {
