### ISSUE TITLE
File: ngCordovaMocks signature != ngCordova

### ISSUE THREAD

**Issue by marcocarnazzo** [driftyco/ng-cordova#703]
I'm using *ngCordova 0.1.14-alpha*.
I can't unit testing my app because function signature of ngCordovaMocks are different than ngCordova ones.

For example, createDir function in ngCordova is:
```javascript
createDir: function (path, dirName, replaceBool)
```
And in ngCordovaMocks:
```javascript
createDir: function(directory, overwrite)
```

**Comment by gortok** [comment]
Is this still an issue with the latest version?
