### ISSUE TITLE
[Request] Add plugin Shared Preferences [Android]

### ISSUE THREAD

**Issue by GistCode** [driftyco/ng-cordova#706]
Shared Preferences

What is it
android equivalent of ios KeyChain

http://ngcordova.com/docs/plugins/keychain/

For what?
Security

https://stormpath.com/blog/the-ultimate-guide-to-mobile-api-security

Why bother?
Since keychain doesn't work in android I guess your user would appreciate if they were introduced to an alternative

Thanks

**Comment by gortok** [comment]
Not sure of the actual question being posed here. Can you help me out by explaining the issue?   Not all plugins support all platforms; we're just the wrappers for the plugins themselves; so if you would like to write a cordova plugin that works the same across platforms, that'd be an awesome cordova plugin to have, and we'd love to have a wrapper made for it once that happens.
