### ISSUE TITLE
[Bug] Error: Unknown provider: $cordovaAppVersion1Provider 

### ISSUE THREAD

**Issue by wahyd4** [driftyco/ng-cordova#709]
When I try to use app version plugin with ng-corodva, then I got this issue.

```bash
Error: [$injector:unpr] Unknown provider: $cordovaAppVersion1Provider <- $cordovaAppVersion1
```

 But the weired thing is after I searched my ng-cordova.js I couldn't find this '$cordovaAppVersion1Provider ' word. So I have use this plugin with its original way.
I think it maybe a typo.

**Comment by gortok** [comment]
Could you include a Minimal Complete, verifiable example in code?  I'd love to fix this if you can reproduce it and share the code that reproduces this issue with us.
