### ISSUE TITLE
BarcodeScanner class not found problem

### ISSUE THREAD

**Issue by abedalzain** [driftyco/ng-cordova#710]
Hi, I would to use BarcodeScanner but I got errors, any help appreciated.

please see attached file.

![error](https://cloud.githubusercontent.com/assets/9558960/6899786/3801fbd4-d70b-11e4-957f-2693ce4caac3.png)

**Comment by MateenKadwaikar** [comment]
Check this out . It was working fine for me.

app.js file

 .controller('MapCtrl', ['$scope', '$cordovaBarcodeScanner',
        function($scope, $cordovaBarcodeScanner) {

               $scope.getPicture = function() {
                $cordovaBarcodeScanner.scan().then(function(imageData) {
                    alert(imageData.text);
                    console.log("Barcode Format -> " + imageData.format);
                    console.log("Cancelled -> " + imageData.cancelled);
                }, function(error) {
                    console.log("An error happened -> " + error);
                });
            };


        }
    ]);

html file

<ion-view view-title="Barcode Scanner">


            <ion-header-bar class="bar-stable">
                <h1 class="title">Ionic Blank Starter</h1>
            </ion-header-bar>
            <ion-content>
                <img ng-show="imgURI !== undefined" ng-src="{{imgURI}}" style="width:;">
			    <img ng-show="imgURI === undefined" ng-src="http://placehold.it/300x300">
			    <button class="button" ng-click="getPicture()">Take Picture</button>
            </ion-content>
       
</ion-view>

**Comment by abedalzain** [comment]
Thanks it works fine now.
