### ISSUE TITLE
Facing problem in running the App

### ISSUE THREAD

**Issue by VinodLouis** [driftyco/ng-cordova#711]
HI I just cloned the App from github and used the WIP-coradovaReady-new branch went into the demo folder and did

$ ionic platform add android
$ ionic build android

later installed the apk in my mobile but the functionalities do not work ? Am I missing something.

while on browser I'm getting error 

TypeError: document.getElementById(...) is null
document.getElementById('fb-root').appendChild(e);

**Comment by gortok** [comment]
Why the WIP and not pulling the latest version? The WIP Branch is pretty old.
