### ISSUE TITLE
$cordovaNetwork: TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by MateenKadwaikar** [driftyco/ng-cordova#725]
I am also facing the same issue. This is my controller

.controller('MapCtrl', ['$scope', '$rootScope', '$cordovaNetwork',

    function($scope, $rootScope, $cordovaNetwork) {

        $ionicPlatform.ready(function() {

            var type = $cordovaNetwork.getNetwork()

            var isOnline = $cordovaNetwork.isOnline()

            var isOffline = $cordovaNetwork.isOffline()

            // listen for Online event
            $rootScope.$on('$cordovaNetwork:online', function(event, networkState) {
                console.log(event);
                console.log(networkState);
                var onlineState = networkState;
            })

            // listen for Offline event
            $rootScope.$on('$cordovaNetwork:offline', function(event, networkState) {
                console.log(event);
                console.log(networkState);
                alert(networkState);
            });
        });
    }
]);

**Comment by gortok** [comment]
If you could include a sample project that reproduces this issue with the latest version, I'd be happy to re-open this issue.
