### ISSUE TITLE
Problem with Blackberry10

### ISSUE THREAD

**Issue by darmie** [driftyco/ng-cordova#726]
Blackberry10 cordova app seems to be having problems with ng-cordova

error messages from web inspector:
``adding proxy for Geolocation cordova.js:947 
Failed to load resource local:///js/ng-cordova_plugins.js 
TypeError: undefined is not an object (evaluating 'window.cordova.plugins.Keyboard') app.js:14
module cordova/plugin_list not found ionic.bundle.js:19387``

**Comment by mlynch** [comment]
We don't support blackberry as a platform in ngCordova. However, this issue
appears to be related to the ionic starter template just not checking for
window.plugins first (which I recently fixed today).

Closing, thanks!

On Sat, Apr 4, 2015 at 12:58 PM, darmie <notifications@github.com> wrote:

> Blackberry10 cordova app seems to be having problems with ng-cordova
>
> error messages from web inspector:
> adding proxy for Geolocation cordova.js:947
> Failed to load resource local:///js/ng-cordova_plugins.js
> TypeError: undefined is not an object (evaluating
> 'window.cordova.plugins.Keyboard') app.js:14
> module cordova/plugin_list not found ionic.bundle.js:19387
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ng-cordova/issues/726>.
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/
