### ISSUE TITLE
It's impossible to use ngCordova !

### ISSUE THREAD

**Issue by paulogr** [driftyco/ng-cordova#728]
It doesn't have even half othe its services mocked !

It's impossible to continue developing an application after install some plugins via ngCordova.

It's frustrating.

I'm trying to ship the source code to a client but he wouldn't be able to test in a browser. He won't be able to continue the development or change anything because the app just won't work on browser.

If I make pull requests to new mock plugins you guys will merge ? Or have another solutions for that ? Or ngCordova aren't on Driftyco plans ?

Really thanks !

**Comment by phox081** [comment]
Have you solved?
Why did you closed this issue?

**Comment by mlynch** [comment]
Hi there,

Most of the plugins require you to test on the device to have any
functionality. It is a native plugin wrapper, after all.

In the future I'd love to have more mocking, but that's a Hard Problem.

On Sun, Apr 5, 2015 at 12:53 PM, Paulo Guilherme Rodrigues <
notifications@github.com> wrote:

> It doesn't have even half othe its services mocked !
>
> It's impossible to continue developing an application after install some
> plugins via ngCordova.
>
> It's frustrating.
>
> I'm trying to ship the source code to a client but he wouldn't be able to
> test in a browser. He won't be able to continue the development or change
> anything because the app just won't work on browser.
>
> If I make pull requests to new mock plugins you guys will merge ? Or have
> another solutions for that ? Or ngCordova aren't on Driftyco plans ?
>
> Really thanks !
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ng-cordova/issues/728>.
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by diegozhu** [comment]
@mlynch  find a volunteer or hire a part-time dev to do this. :laughing:
