### ISSUE TITLE
REQUEST: Encode audio plugin

### ISSUE THREAD

**Issue by wootwoot1234** [driftyco/ng-cordova#729]
It would be great if an encode audio plugin was added.  Recording audio in wav format is a huge storage hog.  This plugin works great:

https://github.com/wootwoot1234/cordova-phonegap-audio-encode

**Comment by gortok** [comment]
That's awesome!  Since it looks like you're the plugin author, you'd be the best person to write the wrapper for that plugin. if you can write the wrapper and include it as a pull request, we'd be happy to have it.
