### ISSUE TITLE
Wrong admob api using

### ISSUE THREAD

**Issue by umbrella-anton-karmazin** [driftyco/ng-cordova#733]
On page http://ngcordova.com/docs/plugins/adMob/ has link to https://github.com/floatinghotpot/cordova-admob-pro, but in code use api from  https://github.com/floatinghotpot/cordova-plugin-admob

**Comment by karmazzin** [comment]
I corrected the wrong API on the correct version.

**Comment by EdL** [comment]
Hi, this has been mentioned back here in case you are interested:
https://github.com/driftyco/ng-cordova/issues/360
