### ISSUE TITLE
BluetoothSerial connect function

### ISSUE THREAD

**Issue by nicklx** [driftyco/ng-cordova#736]
The BluetoothSerial documentation states for the `connect` function:

"The callback is long running. Success will be called when the connection is successful. Failure is called if the connection fails, or later if the connection disconnects".

Given on connection the promise is resolved, the failure callback is never called. I'm not entirely sure how to go around fixing this. Looking at the Angular docs, using `notify` won't work as the promise will have already been resolved.

**Comment by gortok** [comment]
Seems like we'd need a better API for this than just 'connect'. other plugins have separate API calls for the act of connecting, the act of reconnecting, disconnecting, and reporting whether or not we're still connected.    I'm not sure how to fix it either; but I'll chew on it.
