### ISSUE TITLE
Question: Why do you handle module-mocks.js and module.js different?

### ISSUE THREAD

**Issue by paroos** [driftyco/ng-cordova#738]
Hi

Why do you handle the angular module initialization module-mocks.js and module.js different?

**module-mocks.js**

```javascript
var ngCordovaMocks = angular.module('ngCordovaMocks', []);
```

**module.js**

```javascript
angular.module('ngCordova', [
  'ngCordova.plugins'
]);
```

Kind regards, patrick

**Comment by gortok** [comment]
Written at different times, probably by different people; I'm sure there's a reason; but I'm not seeing an actual problem to solve here.  Consistency would be nice; but lower on our list than other issues currently.
