### ISSUE TITLE
DeviceInformation plugin

### ISSUE THREAD

**Issue by sidchilling** [driftyco/ng-cordova#740]
Plugin for https://github.com/vliesaputra/DeviceInformationPlugin

Can we get this integrated? I am having a hard time understanding how to do this?

**Comment by gortok** [comment]
If you look at issue #885 ; I show a few commits where I had to create a wrapper for a cordova plugin. It was the first time I created a wrapper.  That's going to be the fastest way to get this integrated.  Create the wrapper and submit a pull request for it.
