### ISSUE TITLE
$cordovaInAppBrowser.setDefaultOptions not working

### ISSUE THREAD

**Issue by zeronil** [driftyco/ng-cordova#742]
Trying to do this:

$cordovaInAppBrowser.setDefaultOptions(inAppBrowserOptions);

Results in the following error:

Uncaught TypeError: Object #<Object> has no method 'setDefaultOptions' 

To get it to work I moved the setDefaultOptions function in ngCordova.plugins.inAppBrowser (ng-cordova.js) inside of the return

        return {

        setDefaultOptions: function (config) {
          defaultOptions = angular.extend(defaultOptions, config);
        },

        open: function (url, target, requestOptions) { 
        ...
        }
        ...

Not sure if that is what was intended, but it works ;-)

There's also a typo in the ng-cordova documentation in that the function is documented as:

$cordovaInAppBrowserProvider.setDefaultOptions(options)

and it should be 

$cordovaInAppBrowser.setDefaultOptions(options)

**Comment by gortok** [comment]
Thanks for letting us know. Please include a pull request with these fixes and I'll be happy to merge them in!
