### ISSUE TITLE
$cordovaBLE wrapper only returns first device found for scan

### ISSUE THREAD

**Issue by dwimberger** [driftyco/ng-cordova#750]
The current implementation of the wrapper for ble will return the first device result from the scan to the promise, the scan will continue anyway for the time specified.

Somehow this is not what I expected from the scan method semantics and limits the usefulness of the wrapper.

To fix this issue I have modified the wrapper to collect devices for the time it was asked to scan and return the list as promised.

See Pull Request  #749

**Comment by tubaman** [comment]
My PR (#836) is better than #749 because it returns the device as their found using q.notify.
