### ISSUE TITLE
Bug: $cordovaLocalNotification is not aligned with cordova-plugin-local-notifications

### ISSUE THREAD

**Issue by mbarzeev** [driftyco/ng-cordova#754]
Hi guys,

When trying to use the "add()" method of the plugin mentioned above I receive the message:
"Depreated: Please use `notification.local.schedule` instead."
BTW - there are other API's which might be useful to introduce to ngCordova wrapper such as "get()".

Many thanks and keep on the good work!

**Comment by DanailMinchev** [comment]
[Update $cordovaLocalNotification](https://github.com/driftyco/ng-cordova/issues/677)
[$cordovaLocalNotification: 'add' event not fired; proposed pull request ignored](https://github.com/driftyco/ng-cordova/issues/721)

[Update $cordovaLocalNotification to latest plugin version](https://github.com/driftyco/ng-cordova/pull/688)
[Update $cordovaLocalNotification documentation](https://github.com/driftyco/ng-cordova/pull/707)

**Comment by DanailMinchev** [comment]
@mbarzeev the pull request is merged. You can close the issue now.
Thank you!

**Comment by mbarzeev** [comment]
Many thanks :)
