### ISSUE TITLE
Geolocation: Watching for location updates in background

### ISSUE THREAD

**Issue by anuragbhd** [driftyco/ng-cordova#756]
Using the [geolocation](http://ngcordova.com/docs/plugins/geolocation/) plugin, is it possible to watch for location updates while the app is in background? Or does watchPosition() method work only when the app is in foreground?

Also, is it possible to use a Cordova plugin with ngCordova that is not in the officially supported listed, such as [cordova-plugin-background-geolocation](https://github.com/christocracy/cordova-plugin-background-geolocation)?

**Comment by laidig** [comment]
I second this question if someone is able to answer.

**Comment by anuragbhd** [comment]
@laidig Fortunately, [cordova-plugin-background-geolocation](https://github.com/christocracy/cordova-plugin-background-geolocation) is now part of ngCordova. More details here http://ngcordova.com/docs/plugins/backgroundGeolocation/.
