### ISSUE TITLE
cordovaOauth Could not find InAppBrowser plugin error

### ISSUE THREAD

**Issue by mypark** [driftyco/ng-cordova#757]
Not sure what I'm missing but I added the plugin and and added the ngCordova code but I get the error "Could not find InAppBrowser plugin" when I try to use the cordovaOauth plugin.

This is after I add ngCordova as usual and then add plugin via 
 cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-inappbrowser.git

and call it like

     $cordovaOauth.facebook("CLIENT_ID_HERE", ["email"]).then(function(result) {
            console.log(result);
        }, function(error) {
            console.log(error);
        });

**Comment by mypark** [comment]
doing 

`cordova plugin add org.apache.cordova.inappbrowser`

instead seems to have fixed it

**Comment by jasonshark** [comment]
I had to add it that way also. There is more discussion [here](https://github.com/nraboy/ng-cordova-oauth/issues/57)

**Comment by staklau** [comment]
I'm sure this worked once upon a time, but now when you run that command you get this message:

> Notice: org.apache.cordova.inappbrowser has been automatically converted to cordova-plugin-inappbrowser to be fetched from npm. This is due to our old plugins registry shutting down.

**Comment by nineclicks** [comment]
It worked for me to change every instance of `org.apache.cordova.inappbrowser` to `cordova-plugin-inappbrowser` in the `ng-cordova.js`. I suppose you'd want to do the same to the `ng-cordova.min.js` file as well if that's what is being used.
