### ISSUE TITLE
$cordovaKeyboard lacks the method .show()

### ISSUE THREAD

**Issue by fretman92** [driftyco/ng-cordova#759]
Hi, why does this factory lack the .show() method that allows to open the keyboard on Android ?

Even if it's an [Android only feature](https://github.com/driftyco/ionic-plugins-keyboard#keyboardshow), it does not break the functionnality on iOS or other platfroms.

Here is the function I'd add in [$cordovaKeyboard](https://github.com/driftyco/ng-cordova/blob/master/src/plugins/keyboard.js#L14): 

`
    show: function () {
        return cordova.plugins.Keyboard.show();
    },
`

**Comment by bostondv** [comment]
+1
