### ISSUE TITLE
pushNotifications not broadcasting

### ISSUE THREAD

**Issue by sfielder** [driftyco/ng-cordova#762]
Using the provided example code provided from http://ngcordova.com/docs/plugins/pushNotifications/ to register and receive push notifications.

1) Registration works perfectly.
2) Receive notifications fine when in background or device locked mode
3) Unable to successfully receive push notifications when app is in foreground.

I have added some debug alerts to onNotification
```javascript
onNotification: function (notification) {
        alert("ON NOTIFICATION IN NGCORDOVA");
        alert("NOTIFICATION: " + JSON.stringify(notification));

        $timeout(function () {
            $rootScope.$broadcast('$cordovaPush:notificationReceived', notification);
          });
        

      },
```

both alerts pop and notification looks good.

Once it hits the broadcast.. nothing appears to happen!

This is snipped from app.js inside $ionicPlatform.ready...
```javascript
$rootScope.$on('$cordovaPush:notificationReceived', function(event, notification) {

      alert("NOTIFICATION RECEIVED APP CTRL");

     if (notification.alert) {
       alert(notification.alert);
     }

     if (notification.sound) {
       var snd = new Media(event.sound);
       snd.play();
     }

     if (notification.badge) {
       $cordovaPush.setBadgeNumber(notification.badge).then(function(result) {
         // Success!
       }, function(err) {
         // An error occurred. Show a message to the user
       });
     }
   });
```

**Comment by pbernasconi** [comment]
I assume @sfielder closed this because it was resolved?
