### ISSUE TITLE
Angular 2.0 support

### ISSUE THREAD

**Issue by jonchenn** [driftyco/ng-cordova#764]
As title.

**Comment by mlynch** [comment]
I love the eagerness! Be patient though, we are doing Ionic v2 w/ Angular 2 first, then ngCordova. ngCordova is a crucial part of Ionic, so rest assured we will make a similar improvement :)

**Comment by jonchen92** [comment]
Sounds good, looking forward to seeing the progress!

**Comment by astec** [comment]
@mlynch, Is it going to be developed in the same (this) repository?  Branch "v2"?

Any chance to see Contacts for Angular2 anytime soon? Would it make to create a new v2-alpha miltestone?

**Comment by trucle** [comment]
+1

**Comment by jechol** [comment]
+1

**Comment by giacomocariello** [comment]
+1

**Comment by stewones** [comment]
+1

**Comment by kno** [comment]
+1

**Comment by tsm91** [comment]
+1

**Comment by dannyadrizer** [comment]
+1

**Comment by dmurawsky** [comment]
+1

**Comment by mlynch** [comment]
Hey all, we are moving development to Ionic Native: https://github.com/driftyco/ionic-native. It has a few plugins already and we'd love some more :)

The nice thing about this is the wrapper code is smaller so we're not maintaining additional code on top of a plugin. Also typescript support means autocompletion.

**Comment by judypol** [comment]
+1

**Comment by iBasit** [comment]
+1

**Comment by gmpeterson** [comment]
+1
