### ISSUE TITLE
Implement `trackException` in `$cordovaGoogleAnalytics`

### ISSUE THREAD

**Issue by vladipus** [driftyco/ng-cordova#766]
The functionality seems to be available in the plug-in already, but not in ng-cordova:
https://github.com/danwilson/google-analytics-plugin#javascript-usage

The link to the wrapper's sources is also broken here:
http://ngcordova.com/docs/plugins/googleAnalytics/

**Comment by vladipus** [comment]
Supposed implementation (untested!):

```javascript
      trackException: function (desc, fatal) {
        var d = $q.defer();

        $window.analytics.trackException(desc, fatal, function (response) {
          d.resolve(response);
        }, function (error) {
          d.reject(error);
        });

        return d.promise;
      },
```

**Comment by ozexpert** [comment]
No one's tracking issue? this is documented and is working.. cause I'm using it :+1:

**Comment by vladipus** [comment]
This issue seems to have been resolved.
