### ISSUE TITLE
Error on Example - iOS for $cordovaPush

### ISSUE THREAD

**Issue by agustinf** [driftyco/ng-cordova#769]
The example goes like this 
```javascript
    $cordovaPush.register(iosConfig).then(function(result) {
      // Success -- send deviceToken to server, and store for future use
      console.log("result: " + result)
      $http.post("http://server.co/", {user: "Bob", tokenID: result.deviceToken})
    }, function(err) {
      alert("Registration error: " + err)
    });
```
but it should be
```javascript
    $cordovaPush.register(iosConfig).then(function(token) {
      // Success -- send deviceToken to server, and store for future use
      console.log("result: " + token)
      $http.post("http://server.co/", {user: "Bob", tokenID: token})
    }, function(err) {
      alert("Registration error: " + err)
    });
```
All versions of the plugin I could find call back with a string that contains the token, not an object. [See here](https://github.com/phonegap-build/PushPlugin/blob/master/src/ios/PushPlugin.m#L190)

**Comment by pbernasconi** [comment]
@agustinf thanks for spotting that, do you mind making a PR with the correct changes?

**Comment by agustinf** [comment]
I surely would if you point me to the right repository and file

**Comment by pbernasconi** [comment]
See if this page works: [edit /plugins/pushNotifications](https://github.com/driftyco/ng-cordova/edit/gh-pages/docs/plugins/pushNotifications/index.md).
