### ISSUE TITLE
Feat: Support cordova 5.0.0 plugins

### ISSUE THREAD

**Issue by jskrzypek** [driftyco/ng-cordova#771]
See Cordova's blog posts about the [new tools release](http://cordova.apache.org/news/2015/04/21/tools-release.html) and the [new plugin system](http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html)

Will ngCordova switch over sometime soon and what if anything might be required of projects using ngCordova to migrate? (I have the same questions regarding `ionic` & `ionic-cli` but I guess I may open separate issues there later)

**Comment by anasmithiam** [comment]
I am worried about this too.

All ngCordova stuff will work with cordova plugins installed with the new ids? (cordova-plugin-* instead of org.apache.cordova.*)

related #846
