### ISSUE TITLE
$cordovaInstagram not cant find Instagram plugin

### ISSUE THREAD

**Issue by DarrylD** [driftyco/ng-cordova#772]
Added the cordova plugin
`cordova plugins add https://github.com/vstirbu/InstagramPlugin`

Added `ng-cordova.js` (before `cordova.js`) in the `index.html`.

Added `ngCordova` to the angular app dependency list and can successfully inject `$cordovaInstagram`.

Example of code:
```
$scope.share = function() {
        document.addEventListener("deviceready", function () {
            alert('Event trigger') //this fires

            $cordovaInstagram.share(png, 'Just quoting...').then(function() {
                alert('done!') //nothing fired
            }, function(err) {
                alert('broke!!') //nothing fired
                // Didn't work
            });
        });
};
```

The problem is that `window.Instagram` isn't available.

```
if (!window.Instagram){
  alert('no ig!!') //fires...
}
```

Any idea why the plugin isn't loading? Any step i'm missing?

**Comment by asanka-x** [comment]
Hey I also ran into the same problem, did you find any solution ? or what is the cause. I did check ng-cordova.js also, but everthing seems to fine there

**Comment by DarrylD** [comment]
@asanka-x I gave up and decided to use http://ngcordova.com/docs/plugins/socialSharing/ 

You can choose IG on the device shared list (or whatever it is...). Not as good as going directly to IG, but works nonetheless.

**Comment by sibizavic** [comment]
Probably related with my issue:

Injecting the $cordovaInstagram into my service as follows:

    .factory('ShareInstagramFactory', function($cordovaInstagram, $q) {
        var self = this;
        
        // Options
        var shareMessage = "Message";

        //
        // Instagram
        self.shareInstagram = function(imageData) {
            
            console.log("shareInstagram")
            
            var qInstagram = $q.defer();
            
            $cordovaInstagram.share(imageData, shareMessage).then(function() {
                // Worked
                qInstagram.resolve(true)
             }, function(err) {
                // Didn't work
                qInstagram.reject(err);
             });
            
            return qInstagram.promise;
        };
    
        return self;
    })

... returns the following error:

    Error: $injector:unpr
    Unknown Provider
    
    https://docs.angularjs.org/error/$injector/unpr?p0=$cordovaInstagramProvider%20%3C-%20$cordovaInstagram%20%3C-%20ShareInstagramFactory

**Comment by niou-ns** [comment]
I've found the solution:

1) You've to add the ngCordova.plugins.instagram - in your controllers or directives, for example:
angular.module('myapp.directives', ['ngCordova.plugins.instagram'])

2) Then, as usual:
.directive('saveCanvas', function($cordovaInstagram) { ...

3) Documentation for $cordovaInstagram was wrong, you should pass the parameters as object {image: '', caption: ''), for ex.
$cordovaInstagram.share({image: canvas.toDataURL(), caption: '#testtag'})
