### ISSUE TITLE
bad usability for some of the plugins

### ISSUE THREAD

**Issue by ctaepper** [driftyco/ng-cordova#773]
ok, i am quite new to ionic/cordova, i am building my first real hybrid app for a client right now and i run into bad usability of some plugins.

for instance the camera plugin: http://ngcordova.com/docs/plugins/camera/
i understand tha ng-cordova is just an angular-layer on top of the cordova plugins. so to my understanding, i should only need to use the angular service in my app. however, the $cordovaCamera service only exposes getPicture() and cleanup(), but not the constants and Popover functions provided by the underlying cordova plugin... whats up with that? i use the angular service to get the picture, but for all the options and popover functions i have to look up values in the cordova plugin?

the camera plugin is not the only example for this kind of behaviour... so is it just me? is this an intended behaviour of the plugins?

**Comment by vqoph** [comment]
I have the same issue

**Comment by gortok** [comment]
Sometimes the API for the plugins is not fully fleshed out; you can definitely submit a pull request that fleshes it out more.
