### ISSUE TITLE
InAppBrowser plugin renamed

### ISSUE THREAD

**Issue by tizianozonta** [driftyco/ng-cordova#774]
Installing InAppBrowser

`cordova plugin add org.apache.cordova.inappbrowser`

I get this message 

`WARNING: org.apache.cordova.inappbrowser has been renamed to cordova-plugin-inappbrowser. You may not be getting the latest version! We suggest you 'cordova plugin rm org.apache.cordova.inappbrowser' and 'cordova plugin add cordova-plugin-inappbrowser'`

all "if" statement like this

`if(cordovaMetadata.hasOwnProperty("org.apache.cordova.inappbrowser") === true) ...`

fail.

Now InAppBrowser plugin is registered with this name: `cordova-plugin-inappbrowser`

Previous line become:

`if(cordovaMetadata.hasOwnProperty("cordova-plugin-inappbrowser") === true) ...`

**Comment by napcat** [comment]
+1 

Updated to cordova 5, and I'm also changing that line.
Probabli you will need to leave both validations to keep it compatible with older cordova builds.

**Comment by nraboy** [comment]
This was merged in the latest master.  @pbernasconi can close this ticket.
