### ISSUE TITLE
Oauth linkedin modifies global header Content-Type to 'application/x-www-form-urlencoded'

### ISSUE THREAD

**Issue by brayancastrop** [driftyco/ng-cordova#775]
After digging in the oauth code i noticed this change to global headers 

$http.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded';

which makes any subsequent post in the app to use that header instead the original default (Content-Type: application/json), i think we can avoid this by supplying a headers property in the config object passed when calling $http(config), which overrides the defaults without changing them globally, i've already forked and made the change but i was wondering how do you test changes on Oauth plugin so i can test it and make a pull request for it

**Comment by gortok** [comment]
I've not used the OAuth plugin myself, but my guess is that you'd set up a proxy for your device through something you have fiddler attached to and watch the traffic and make sure the headers are correct.  I'll be happy to accept a pull request when you're ready for us to take a look at it.
