### ISSUE TITLE
Local Notification events bug

### ISSUE THREAD

**Issue by virix** [driftyco/ng-cordova#779]
$window.plugin.notification.local.on("click", function (id, state, json) {
      var notification = {
        id: id,
        state: state,
        json: json
      };
      $timeout(function () {
        $rootScope.$broadcast("$cordovaLocalNotification:clicked", notification);
      });
    });

should be:

    $window.plugin.notification.local.on("click", function (notification) {      
      $timeout(function () {
        $rootScope.$broadcast("$cordovaLocalNotification:clicked", notification);
      });
    });

to follow java code.

**Comment by DanailMinchev** [comment]
What is the difference between the two?
Anyway, plugin has been updated - close the issue if it's not applicable now.

Thank you

**Comment by virix** [comment]
Cordova plugin (in ClickActivity.java) passes notificationObj to click event, not (id, state, json).
The difference is the object passed from ng-cordova to js event.
The fist (wrong) passes an object like this:
{
  id: notificationObj,
  state: undefined
  json: undefined
}
The second passes simply notificationObj (correct).

Anyway, I see your changes and It seems ok now.

Thank you.
