### ISSUE TITLE
Email Composer Docs Link, need update

### ISSUE THREAD

**Issue by TrevorJTClarke** [driftyco/ng-cordova#781]
Hello!
I just tried to grab the plugin via the example in the docs:
cordova plugin add https://github.com/katzer/cordova-plugin-email-composer.git@0.8.2

This seemed to cause an issue. 
Instead I used: 
cordova plugin add https://github.com/katzer/cordova-plugin-email-composer 
and all worked well.

**Comment by quanghoc** [comment]
Actually that is for the latest branch. For stable, use this (according to their Github readme)

`cordova plugin add de.appplant.cordova.plugin.email-composer@0.8.2`

**Comment by root-io** [comment]
@TrevorJTClarke You're right the link is broken, the correct url is:
https://github.com/katzer/cordova-plugin-email-composer.git#0.8.2

I don't understand why we don't use the master branch on this one, there is no difference.
https://github.com/katzer/cordova-plugin-email-composer/commits/master
