### ISSUE TITLE
$cordovaDialogs.prompt can not change the title!

### ISSUE THREAD

**Issue by ShiyangHuang** [driftyco/ng-cordova#785]
It shows index.html all the time.
code here
$cordovaDialogs.prompt('Create New Folder','New Title');
on IOS emulate, newest one
![image](https://cloud.githubusercontent.com/assets/6767493/7485333/0390b5fc-f362-11e4-9fb2-3d3f2d3e7a9f.png)

**Comment by gortok** [comment]
Please include a sample project that reproduces this issue.  I don't see this issue in 0.1.17.
