### ISSUE TITLE
Feat: enhance cordovaToast mock 

### ISSUE THREAD

**Issue by 11lein** [driftyco/ng-cordova#788]
I would like to enhance the toast mock to get a feedback in the browser.

Please suggest me a solution.

1. simple console.log(message)
2. use https://developer.mozilla.org/en/docs/Web/API/notification (won't work in all browsers)
3. make a very simple toast function e.g. showing the message on top centered and hide it after 5 seconds.

**Comment by gortok** [comment]
It'd be awesome if all mocks worked in the browser;  sadly we haven't yet written code for all of them to work in the browser. If you'd like to help us by adding one for toast, I'd be happy to accept a PR.
