### ISSUE TITLE
Custom build incorrectly references module dependencies

### ISSUE THREAD

**Issue by jfrumar** [driftyco/ng-cordova#790]
I just built a custom JS file:

```js
angular.module('ngCordova', [
  'ngCordova.plugins'
]);


angular.module('ngCordova.plugins', [
	 'file',
	 'fileOpener2',
	 'fileTransfer',
	 'progressIndicator'
]);
```

It fails with ```Uncaught Error: [$injector:modulerr] Failed to instantiate module groupAhead due to:
Error: [$injector:modulerr] Failed to instantiate module ngCordova due to:
Error: [$injector:modulerr] Failed to instantiate module ngCordova.plugins due to:
Error: [$injector:modulerr] Failed to instantiate module file due to:
Error: [$injector:nomod] Module 'file' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.```

It works when I change to:

```js
angular.module('ngCordova.plugins', [
  'ngCordova.plugins.file',
  'ngCordova.plugins.fileOpener2',
  'ngCordova.plugins.fileTransfer',
  'ngCordova.plugins.progressIndicator'
]);
```

**Comment by gortok** [comment]
This would seem to be 'working as designed' since the plugins are namespaced to the `ngCordova.plugins.` namespace.  I could also be looking at this wrong.
