### ISSUE TITLE
$cordovaFile.checkDir says folder does not exist but $cordovaFile.createDir says folder already exists

### ISSUE THREAD

**Issue by jonnysmith1981** [driftyco/ng-cordova#792]
I am trying to work with the ngCordova File plugin as documented here: http://ngcordova.com/docs/plugins/file/, but am getting strange behaviour.

I am trying to create a folder if it does not already exist. I am testing for its existence using:

$cordovaFile.checkDir(cordova.file.dataDirectory, 'inbound')

Now this returns NOT_FOUND_ERR so i try to create the folder subsequently by calling:

$cordovaFile.createDir(cordova.file.dataDirectory, 'inbound', false);

But this then returns PATH_EXISTS_ERR

Why would checkDir tell me it does not exist, but then createDir tell me it DOES exist?

NOTE: This is using an Android device.

**Comment by jonnysmith1981** [comment]
I didn't read the manual - sorry. Nothing to see here.

**Comment by jonnysmith1981** [comment]
I have now set the config.xml to match my requirements for accessing cordova.file.dataDirectory but i am still getting the above errors.

**Comment by jonnysmith1981** [comment]
Issue was caused by rebuilding and redeploying over the top of the existing Android install. I uninstalled the app and re-installed and I was able to use the cordovaFile plugin with no problems.

**Comment by AravindMedida** [comment]
I'm facing the same problem currently but not able to resolve it. I've uninstalled the app and reinstalled it but still its not working. Can some one help me on this
