### ISSUE TITLE
Contributor Guidelines and Coding Standard

### ISSUE THREAD

**Issue by gortok** [driftyco/ng-cordova#793]
I've forked ngCordova/ngCordovaMocks to provide a compatible BluetoothLE plugin wrapper for Cordova 4.0+; and in the course of writing the code, I wanted to make sure I'm following whatever guidelines are out there.  I don't presently see any guidelines, and some files have a mixture of tabs and spaces (some files use tabs, some use spaces).

So for guidelines:

What JSLint or JSHint settings should be set?
2 space indent? or 2 space tab indent?

**Comment by mlynch** [comment]
Hey George,

Good point, we should clarify that. For JS we use 2 spaces. Need to go back
and apply that to all files.

On Tue, May 12, 2015 at 3:20 PM, George Stocker <notifications@github.com>
wrote:

> I've forked ngCordova/ngCordovaMocks to provide a compatible BluetoothLE
> plugin wrapper for Cordova 4.0+; and in the course of writing the code, I
> wanted to make sure I'm following whatever guidelines are out there. I
> don't presently see any guidelines, and some files have a mixture of tabs
> and spaces (some files use tabs, some use spaces).
>
> So for guidelines:
>
> What JSLint or JSHint settings should be set?
> 2 space indent? or 2 space tab indent?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ng-cordova/issues/793>.
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by gortok** [comment]
@mlynch Are there any JSHint or JSlint specific settings this project uses to ensure code style remains the same?

**Comment by pbernasconi** [comment]
I think we would make use of [JSCS](http://jscs.info/) for the formatting issue. I'll look into it!

**Comment by pbernasconi** [comment]
Done. https://github.com/driftyco/ng-cordova/blob/master/gulpfile.js#L84

Usage:
```
gulp test
```
