### ISSUE TITLE
Issue while trying to inject cordova-plugin-googleplus into my controller

### ISSUE THREAD

**Issue by OSSDeveloper** [driftyco/ng-cordova#796]
Hi ,

Am trying to use the cordova-plugin-googleplus plugin and, am getting an error. Please check the issue. 
Am pasting the error msg from browser(Am running it in device, using browser just for error log) :-

Error: [$injector:unpr] Unknown provider: $cordovaGooglePlusProvider <- $cordovaGooglePlus <- loginController
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=%24cordovaGooglePlusProvider%20%3C-%20%24cordovaGooglePlus%20%3C-%20loginController
at REGEX_STRING_REGEXP (ionic.bundle.js:8762)
at ionic.bundle.js:12696
at Object.getService as get
at ionic.bundle.js:12701
at getService (ionic.bundle.js:12843)
at invoke (ionic.bundle.js:12875)
at Object.instantiate (ionic.bundle.js:12892)
at ionic.bundle.js:17161
at IonicModule.controller.self.appendViewElement (ionic.bundle.js:48253)

---------------------------------------------------------------------------------------------------------------
And, here is my controller :- 
var loginController = starterApp.controller('loginController', function($scope, $cordovaGooglePlus){
	$cordovaGooglePlus.login().then(function(data){
		alert(data);
	}, function(err){
		alert(err)
	});
});

**Comment by guillermo-varela** [comment]
Hi,
The plugin was added at some point, but was deleted again in this commit: https://github.com/driftyco/ng-cordova/commit/712fe8d7de28a2abf354e146ef0c364b04f1d136#diff-cf07438d7faebd091483bb63caa510e7L4836

Any reason for it?

Thanks.
