### ISSUE TITLE
$timeout is not defined

### ISSUE THREAD

**Issue by johannds** [driftyco/ng-cordova#798]
Hi,

I get this:

I/chromium( 5033): [INFO:CONSOLE(8)] "Uncaught ReferenceError: $timeout is not defined", source: file:///android_asset/www/lib/ngCordova/dist/ng-cordova.min.js (8) on Android when running crosswalk 10.

My app freezes up and becomes totally unusably slow when I try to input any text. It only happens on Android 4.1.2 and 4.1.1 from what I can see.

Any ideas?

Kindly,
Johann

**Comment by ctotheameron** [comment]
+1 for me too

**Comment by pbernasconi** [comment]
Could you try using the *un-minified* `ng-cordova.js` file, so that I can see exactly where the error is?

**Comment by dymo** [comment]
I had the same problem, but it looks like it was solved in 0dc3b651e980aeb591572949dfd8e301e5b04d76
