### ISSUE TITLE
Unable to build Ionic iOS project with XCode 6.3 after adding ngCordova $cordovaBadge plugin

### ISSUE THREAD

**Issue by degamer106** [driftyco/ng-cordova#800]
Steps to reproduce:

1) Add the cordovaBadge plugin to your Ionic project: cordova plugin add https://github.com/katzer/cordova-plugin-badge.git
2) Build your project via Terminal command: ionic build ios
3) You will get the following message: ** BUILD FAILED **

The following build commands failed:
	Ld build/emulator/TriNetPOC.app/TriNetPOC normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/alin/dev/projects/mobile/ionic/TriNetPOC/platforms/ios/cordova/build-debug.xcconfig,-project,TriNetPOC.xcodeproj,ARCHS=i386,-target,TriNetPOC,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/alin/dev/projects/mobile/ionic/TriNetPOC/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/alin/dev/projects/mobile/ionic/TriNetPOC/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/alin/dev/projects/mobile/ionic/TriNetPOC/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/alin/dev/projects/mobile/ionic/TriNetPOC/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

**Comment by ankurextreme** [comment]
After adding plugin i get following error

** BUILD FAILED **


The following build commands failed:
	Ld build/emulator/ionCordova.app/ionCordova normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/ankurpatel/Desktop/ionic_apps/ionCordova/platforms/ios/cordova/build-debug.xcconfig,-project,ionCordova.xcodeproj,ARCHS=i386,-target,ionCordova,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/ankurpatel/Desktop/ionic_apps/ionCordova/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/ankurpatel/Desktop/ionic_apps/ionCordova/platforms/ios/build/sharedpch
Error: /Users/ankurpatel/Desktop/ionic_apps/ionCordova/platforms/ios/cordova/run: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
 

Please HELP
