### ISSUE TITLE
Gently fail when plugins is not available (not installed or testing in browser)

### ISSUE THREAD

**Issue by begrossi** [driftyco/ng-cordova#801]
I'm started now to migrate my code to use ngCordova, that is a great tool! 
But I saw that a lot of plugins don't fails gently and/or with a common contract if plugin is not present.

Examples:
* [Camera Plugin](https://github.com/driftyco/ng-cordova/blob/master/src/plugins/camera.js) returns null if it's not installed: ```if (!navigator.camera) { q.resolve(null);  return q.promise;}```
* [DatePicker](https://github.com/driftyco/ng-cordova/blob/master/src/plugins/datepicker.js) and [Calendar](https://github.com/driftyco/ng-cordova/blob/master/src/plugins/calendar.js) throws an exception, broken promises contract!

I known it should not work in a browser, but I think that I don't need to check if a plugin is present with something like window.plugin.calendar, because so it turns ngCordova unecessary!
I think it should be standarlized that each plugin should check if it is present and reject the promise if it is not present.

Thanks in advance,
Bruno

**Comment by gortok** [comment]
Have you used ngCordovaMocks for browser work?
