### ISSUE TITLE
SocialSharing plugin documentation error

### ISSUE THREAD

**Issue by JerryBels** [driftyco/ng-cordova#806]
Just to report a little plugin doc error : 

On this page : http://ngcordova.com/docs/plugins/socialSharing/ there is a mistake, CC mail has been forgotten.

    // toArr and bccArr must be an array, file can be either null, string or array
      $cordovaSocialSharing
        .shareViaEmail(message, subject, toArr, bccArr, file)

Should be replaced with

    // toArr, ccArr and bccArr must be an array, file can be either null, string or array
      $cordovaSocialSharing
        .shareViaEmail(message, subject, toArr, ccArr, bccArr, file)

**Comment by pbernasconi** [comment]
thanks, fixed aec080702e809033591adcf5f252040b4aeecbea
