### ISSUE TITLE
Upload pdf to dropbox

### ISSUE THREAD

**Issue by inceptiveSujit** [driftyco/ng-cordova#813]
down vote
favorite
1
Does any one implemented uploading pdf to dropbox, I am using dropbox api and file plugin.

I tried every method of file plugin (ReadAsArrayBuffer, ReadAsBinaryString, ReadAsText) using all that I am able to upload file to dropbox however format of PDF got corrupted upon downloading.

Please let me know if anybody has any solutions on it

**Comment by gortok** [comment]
Are you having an issue with ngCordova?  If so, please provide a sample project that reproduces the issue you're seeing and I'll be happy to re-open this issue.
