### ISSUE TITLE
Error: 404 Not Found: cordova-plugin-statusbar

### ISSUE THREAD

**Issue by larpo1** [driftyco/ng-cordova#814]
Install fails following docs here: http://ngcordova.com/docs/plugins/statusbar/

```
$ cordova plugin add cordova-plugin-statusbar
Fetching plugin "cordova-plugin-statusbar" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-statusbar
npm http 404 http://registry.cordova.io/cordova-plugin-statusbar
Error: 404 Not Found: cordova-plugin-statusbar

```

**Comment by umcsdon** [comment]
Hi @larpo1 

The plugin changed it's name to <b>org.apache.cordova.statusbar</b>. 

<code>
cordova plugin add org.apache.cordova.statusbar.
</code>

http://plugins.cordova.io/#/package/org.apache.cordova.statusbar
