### ISSUE TITLE
Feat: Alarms?

### ISSUE THREAD

**Issue by MichaelJCole** [driftyco/ng-cordova#815]
Hi, I'm looking for alarms in Ionic.  

What's the best way?  Is there something obvious I'm missing?  Is there a reason alarms aren't in ngCordova?

I found [this](https://github.com/wnyc/cordova-plugin-wakeuptimer) but was having trouble getting it to work.  (Literally no comments or API documentation).

Thanks!

Mike

**Comment by gortok** [comment]
What do you mean by alarms?
