### ISSUE TITLE
Network Settings intent

### ISSUE THREAD

**Issue by leejinhuey** [driftyco/ng-cordova#819]
A common issue with ng-cordova applications is they don't work when you run out of internet juice. Providing a handy way for users to adjust their network settings appropriately is useful and rather straightforward. Therefore, I suggest a way to provide access to native network settings from the app, probably through opening the native Settings application. 

In Android, natively, this is as straightforward as:

    startActivity(new Intent(android.provider.Settings.ACTION_WIRELESS_SETTINGS));

**Comment by gortok** [comment]
Yea; it seems like there would need to be a Cordova plugin written for this; then we could add a wrapper on top of that. are there any cordova plugins you know of that do this that we should include support for?
