### ISSUE TITLE
$cordovaContacts.find doesn't work with lb-services

### ISSUE THREAD

**Issue by gautamkishore** [driftyco/ng-cordova#822]
It was working completely when I used just ngCordova but when I included lbServices, it stopped working. it doesn't go to then() neither generates any error.

    .controller('FriendsCtrl', function($scope, $cordovaContacts) {

      $scope.getContactList = function() {
        $cordovaContacts.find({filter: ''}).then(function(result) {
            $scope.contacts = result;

        }, function(error) {
            console.log("ERROR: " + error);
    });

    })

**Comment by gortok** [comment]
Yes; filter is currently busted. I've added a fix for this in PR #891. Thanks for catching this!
