### ISSUE TITLE
 Cannot read property 'toast' of undefined

### ISSUE THREAD

**Issue by MaxBalance** [driftyco/ng-cordova#828]
" Cannot read property 'toast' of undefined ".This problem happens in the official demo and my project.

I have used this serval times , but until today , I get this problem.

Any help will be appreciated~

**Comment by david-byng** [comment]
Hi MaxBalance,

Is the plugin added to the project with cordova [like in the docs](http://ngcordova.com/docs/plugins/toast/)?

Are you testing on a real device or in the browser?

**Comment by MaxBalance** [comment]
Thanks a lot.I put the plugins with a wrong path...
