### ISSUE TITLE
Telerik Push plugin support

### ISSUE THREAD

**Issue by maxrevilo** [driftyco/ng-cordova#839]
Hey, what about giving some support for the Telerik PushPlugin?
https://github.com/Telerik-Verified-Plugins/PushNotification

I could send a PR if you agree, the Telerik plugin have extended functionality and is actively supported.

I would add sopport for iOS interactive notifications and to check if push notifications are enabled.

https://github.com/Telerik-Verified-Plugins/PushNotification

**Comment by paulogr** [comment]
+1
Em 06/06/2015 16:29, "Oliver Perez" <notifications@github.com> escreveu:

**Comment by mhartington** [comment]
So the telerik plugins are actually just the standard cordova plugins that have been forked and tested by the people at telerik. There really is no difference between the two.
