### ISSUE TITLE
cordova plugin add giving 404 error

### ISSUE THREAD

**Issue by jonnysmith1981** [driftyco/ng-cordova#847]
I have tried this on multiple computers on different internet connections, but each time i try to install the capture, camera, file or sqlite plugins I am getting:

Failed to install 'cordova-plugin-media-capture':Error: 404 Not Found

**Comment by bricktownseo** [comment]
Jonny,

It worked for me... What version of cordova are you using?

Phil

**Comment by jonnysmith1981** [comment]
Thanks for the tip Phil. I was running 4.3.0. Upgraded to 5.1.1 and the plugin installed correctly.
