### ISSUE TITLE
Let cordovaEmailComposer.open() fail promise when "cordova is not defined" for testing in browser

### ISSUE THREAD

**Issue by DarianLewin** [driftyco/ng-cordova#848]
*FEATURE REQUEST*

The cordovaEmailComposer.open method throws the following error when testing in a browser:

> ReferenceError: cordova is not defined
>    at Object.open (ng-cordova.js:1575)

The open() method returns a promise.
I propose to use the existing promise to give feedback in case that cordova is required. The promise could be made to fail/rejected when cordova is not available.

This would allow the failure to be handled and/or ignored more easily and (in my opinion) more consistently as the failure callback of a promise is already used to resolve failures.

**Comment by gortok** [comment]
This is a great suggestion. Could you make a pull request for this feature request? We'd be happy to look at this issue further then.
