### ISSUE TITLE
Network Information plugin fails to run

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ng-cordova#853]
I downloaded a custom build that made use of *just* network information. When I try to inject it into my controller, I get an error:

0     930369   error    Error: [$injector:modulerr] Failed to instantiate module starter due to:
[$injector:modulerr] Failed to instantiate module ngCordova due to:
[$injector:modulerr] Failed to instantiate module ngCordova.plugins due to:
[$injector:modulerr] Failed to instantiate module network due to:
[$injector:nomod] Module 'network' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by gortok** [comment]
Please include a sample project that reproduces this issue. once you do that, I'll be happy to re-open.

**Comment by cfjedimaster** [comment]
Here is an example.  Um shoot - I can't upload a zip. Here's a Dropbox link.

https://dl.dropboxusercontent.com/u/88185/ni-test.zip

Appears to be uploading still on crappy hotel wifi so if the link doesn't work, give it a minute. I didn't even inject it in my controller, just loading ngCordova causes the issue.
