### ISSUE TITLE
TypeError: Cannot read property 'browserInit' of undefined

### ISSUE THREAD

**Issue by ShubhamBadal** [driftyco/ng-cordova#854]
I want to run on browser for testing and ui development, don't want to do that on phone or emulator everytime. I saw http://ngcordova.com/docs/plugins/facebook/ and under web development section saw this is possible. Made changes as said in config.js but I am getting this error.

Uncaught ReferenceError: cordova is not defined
TypeError: Cannot read property 'browserInit' of undefined

I have added facebookConnectPlugin.js to index.html
I have added < div id="fb-root" > < /div > inside body of index.html

I am using Cordova/Ionic.

**Comment by gortok** [comment]
If you can include a sample project that reproduces this issue; I'll be happy to take a look.  I do know that generally cordova isn't loaded in the browser, so it won't be defined.
