### ISSUE TITLE
Beacons/iBeacons Plugin 

### ISSUE THREAD

**Issue by jordanskole** [driftyco/ng-cordova#862]
Feat, Feature

Create a angular service for the Cordova "proximity" / beacons / iBeacon plugin.

* https://github.com/petermetz/cordova-plugin-ibeacon
* https://github.com/petermetz/cordova-proximity-quickstart

**Comment by DanailMinchev** [comment]
There is a pull request "[Add $cordovaBeacon plugin](https://github.com/driftyco/ng-cordova/pull/857)" for that already

**Comment by jordanskole** [comment]
Oh nice! I searched the issues but didn't search the PRs.
