### ISSUE TITLE
$cordovaMedia documentation wrong

### ISSUE THREAD

**Issue by Kurtz1993** [driftyco/ng-cordova#866]
In the example we see the following code:

module.controller('MyCtrl', function($scope, $cordovaMedia) {
  var src = "/src/audio.mp3";
  var media = $cordovaMedia.newMedia(src).then(function() {
    // success
  }, function () {
    // error
  });
  var iOSPlayOptions = {
    numberOfLoops: 2,
    playAudioWhenScreenIsLocked : false
  }
  media.play(options); // iOS only!
  media.play(); // Android
  media.pause();
  media.stop();
  media.release();
  media.seekTo(5000); // milliseconds value
  media.setVolume(0.5);
  media.startRecord();
  media.stopRecord();
  // media.getDuration(media); not working yet
  // media.getCurrentPosition().then(...); not working yet
});

But the actual way the media variable Works is this:

var media = $cordovaMedia.newMedia(src);

without the .then methods. If we follow the example in the documentation we get a media object with only a $$state parameter, with no Media methods, but if we don't use the .then methods we get the full Media object.

**Comment by gortok** [comment]
If you can update the documentation with a PR and submit that PR, we'd be happy to accept it.

**Comment by Kurtz1993** [comment]
Where should I make de PR of ng-cordova documentation of the webpage http://ngcordova.com/ ?

**Comment by gortok** [comment]
It's located on the gh-pages branch of this Repo. see the 'contributing.md' doc in the root of this Repo for more directions.

**Comment by Kurtz1993** [comment]
Thank you!

Enviado desde mi Windows Phone
________________________________

**Comment by gortok** [comment]
Thanks for doing this.
