### ISSUE TITLE
SQLite problem.

### ISSUE THREAD

**Issue by marcelodelta** [driftyco/ng-cordova#872]
var db = $cordovaSQLite.openDB({name:"banco.db"});
    $cordovaSQLite.execute(db, 'CREATE TABLE IF NOT EXISTS registros (id integer primary key, data text)');

ERROR: Uncaught TypeError: Cannot read property 'openDatabase' of undefined

**Comment by gortok** [comment]
Could you put together a minimal reproduction of this issue here or in a github repo that I can pull to investigate this issue for you?  I'll re-open this when you do that.
