### ISSUE TITLE
BLE compatible with Cordova 4.0.0+

### ISSUE THREAD

**Issue by gortok** [driftyco/ng-cordova#873]
I've implemented a wrapper for a BLE library that is compatible with Cordova 4.0+. The evothings library is not. https://github.com/Jewelbots/ng-cordova/tree/bluetoothle-plugin-addition  I'd like to submit a pull request to include it; but I understand that having two BLE libraries may be weird.  I'm opening this issue to discuss how we should approach this issue.

**Comment by gortok** [comment]
This would probably cause confusion with the advent of multiple BLE plugins; but we need a better way to handle abandoned plugins vs. active plugins. Perhaps including this in a new major version of NgCordova? as Cordova 5 compatible? Anyone else have any thoughts on this?

**Comment by mhartington** [comment]
What is the BLE plugin that you have added a wrapper for? 
I like the idea of supporting a minimum cordova version. Only issue with that is cordova-ios is now at 3.9 and cordova-android is at 4.1. So pinning a particular version of cordova is a bit tough.

**Comment by gortok** [comment]
https://github.com/randdusing/BluetoothLE is the plugin; the wrapper is available through the first comment link; I'd clean it up before adding it.   

I'd like for there to be an easier way for users to be able to see what plugins are supported at their Cordova level; it'd save a lot of heartache; but it does add some complexity on our part.

**Comment by mhartington** [comment]
Now how does this differ from this BLE plugin? 

https://github.com/don/BluetoothSerial
https://github.com/don/cordova-plugin-ble-central

**Comment by gortok** [comment]
It wasn't until two days ago that an outstanding PR #751 was merge; so I was thinking the evothings was the actual under the hood plugin, and it didn't support Cordova 4.0+; and that led me to creating the wrapper for this plugin.  Since then, i've added a few features to this plugin; notably how to search for specific devices; but that's nothing that couldn't be replicated.

**Comment by mhartington** [comment]
So again, what the main difference between the plugins then? Doesn't seem necessary to add another bluetooth plugin. ngCordova does have both the BLE plugins, just no docs at the moment.

**Comment by gortok** [comment]
The BluetoothSerial is for serial communication over bluetooth; and the ble.js wrapper is the standard BLE wrapper; we don't need multiples them, you're right. 

I'll continue using the bluetoothle plugin (the custom one in my repo), and will put docs around it.
