### ISSUE TITLE
Watch Acceleration Throws TypeError exception on browser

### ISSUE THREAD

**Issue by davidecavaliere** [driftyco/ng-cordova#874]
Didn't had the time to check browsers other than chrome version 43.0.2357.130 64 bit on Linux.

When trying to get acceleration in browser as in: 

```javascript
var watch = $cordovaDeviceMotion.watchAcceleration({
  frequency : 5000
});
```

console shows this error:

```
Uncaught TypeError: Cannot read property 'watchAcceleration' of undefined
```

This is due to

``` 
navigator.accelerometer 
```
being 'undefined' in browser

**Comment by gortok** [comment]
Cordova Plugins don't work in the browser.
