### ISSUE TITLE
 $cordovaDeviceOrientation example error

### ISSUE THREAD

**Issue by phillamarmotte** [driftyco/ng-cordova#881]
Hi, 
first of all thank you for this library.
I think i 've found a mistake in your documentation of  $cordovaDeviceOrientation

In the documentation example :

var watch = $cordovaDeviceOrientation.watchHeading(options).then(
      null,
      function(error) {
        // An error occurred
      },
      function(result) {   // updates constantly (depending on frequency value)
        var magneticHeading = result.magneticHeading;
        var trueHeading = result.trueHeading;
        var accuracy = result.headingAccuracy;
        var timeStamp = result.timestamp;
      });
///
///
///
    watch.clearWatch();

but it doesnt work because of the declaration of watch (it's a promise with only a $$state property)

i think we're suposed to do something like this : 

var watch = $cordovaDeviceOrientation.watchHeading(options);

watch.then(
      null,
      function(error) {
        // An error occurred
      },
      function(result) {   // updates constantly (depending on frequency value)
        var magneticHeading = result.magneticHeading;
        var trueHeading = result.trueHeading;
        var accuracy = result.headingAccuracy;
        var timeStamp = result.timestamp;
      });

    watch.clearWatch();

in this case you've got an object watch with all the desired methods.

best regards

**Comment by gortok** [comment]
Thanks for this.  Could you help us out by forking the gh-pages branch of this repo, adding the fix to the documentation there, and submitting a pull request? 

Thanks again!
