### ISSUE TITLE
findEvent for calendar plugin success callback

### ISSUE THREAD

**Issue by akj627** [driftyco/ng-cordova#882]
Hi,
The findEvent success callback for the $cordovaCalendar has a response object returned, but I always get a length of 0 in it even if the event is in the calendar.
Do you guys know if the success callback can tell me whether the event was found in the calendar or not ?
Thanks
Achint

**Comment by gortok** [comment]
Please include a minimal example that reproduces the issue you're seeing so that we can help you resolve this issue.  If you do that, I'll be happy to re-open.
