### ISSUE TITLE
$cordovaCamera.getPicture promise rejected prematurely on Blackberry

### ISSUE THREAD

**Issue by funkjedi** [driftyco/ng-cordova#883]
When `navigator.camera.getPicture` is called on a Blackberry the error callback gets called immediately with no arguments. However an actual error hasn't occurred. The success callback is fired successfully after the picture selected.

![navigatorcameragetpicture](https://cloud.githubusercontent.com/assets/9314/8702759/ce858af0-2ae7-11e5-8320-c0bebb395d0e.png)

If you are calling `navigator.camera.getPicture` directly this isn't an issue however if you try and use `$cordovaCamera.getPicture` it doesn't work because the promise is rejected prematurely when the error callback is called prior to the camera/library opening.

I realize the underlying issue is a Cordova bug and putting a workaround in ngCordova probably isn't the best solution. So this is more for reference if others are using ngCordova on Blackberry and need an immediate solution.

```js
function getPicture(options) {
	var q = $q.defer();

	if (!navigator.camera) {
		q.resolve(null);
		return q.promise;
	}

	navigator.camera.getPicture(function (imageData) {
		q.resolve(imageData);
	}, function (err) {
		angular.isUndefined(err) || q.reject(err);
	}, options);

	return q.promise;
}
```

**Comment by gortok** [comment]
If you submit a pull request for this, we'd be happy to accept.

**Comment by jskrzypek** [comment]
We're experiencing this same issue as well, I'll submit a PR.

**Comment by jskrzypek** [comment]
@gortok Is my PR acceptable?
