### ISSUE TITLE
$cordovaDatePicker only returns first date

### ISSUE THREAD

**Issue by joewoodhouse** [driftyco/ng-cordova#885]
With the latest version of the cordova-plugin-datepicker, when the datepicker appears the underlying plugin fires the `show` callback multiple times, each time the user changes the date, until the picker is dismissed.

However because `$cordovaDatePicker` wraps the show callback in a promise, and a promise can only be resolved once, the result is that you only get notification of the first change of date, and not any subsequent ones.

Given the promise-y nature, I'm not sure what the solution is. Perhaps the promise `notify` could be called on each date change, with the promise being resolved with the final date value once the user has dismissed the picker.

As a workaround, for now I've just used the underlying $window.datePicker, e.g.

```
$window.datePicker(options,function(date){
  // Gets called every time date changes
  $timeout(function(){
    // do something with date
  });
});
```

**Comment by gortok** [comment]
Using notify for this makes sense; if you'd like to put together a pull request, we'd be happy to accept.  

I also had to do this for the custom plugin wrapper I wrote for the bluetoothle.js (not the ble.js that you know and love); that commit is here: https://github.com/Jewelbots/ng-cordova/commit/88463cb6b2adf09b052c362c5928b4d9223c2f1f

I also wrote a more complex version of that so for another function here: 
https://github.com/Jewelbots/ng-cordova/commit/8fe7866eea4234d8e3d0442469ceac2ff95a46a0

I'll close this; and submit a pull request for this issue and we'll handle it there.
