### ISSUE TITLE
dist should be added to gitignore

### ISSUE THREAD

**Issue by gortok** [driftyco/ng-cordova#890]
The dist folder should be added to git ignore; Or, if there's a pain free way of developing with the dist folder around, could you share that?

My present work flow is this:

delete local dist folder
commit 
pull
make changes
gulp build
add dist folder
add commits
rebase (squashing commits)
add PR.

Is there an easier way?

**Comment by gortok** [comment]
One of the reasons I bring this up is that I'm always getting merge conflicts in the dist/ related items due to builds.

**Comment by mhartington** [comment]
Not really. Not everyone is building ng-cordova, so there needs to be a local copy available for them to reference. Dist needs to stay.
