### ISSUE TITLE
Plugin Media + attribute

### ISSUE THREAD

**Issue by judsonbomfim** [driftyco/ng-cordova#893]
Hello!

I'm having trouble loading an audio through the media plugin.

If you put this way works
thisMedia = $cordovaMedia.newMedia('audio/audio/mp3');

If put in this way does not work
thisMedia = $cordovaMedia.newMedia($scope.linkAudio);

Can anyone help me solve this?

Note: I am using Ionic

**Comment by gortok** [comment]
If you include a sample project that reproduces this issue, we'll be happy to take a look.
