### ISSUE TITLE
v0.1.18-alpha is failing

### ISSUE THREAD

**Issue by seronal** [driftyco/ng-cordova#908]
After updating to latest version (v0.1.18-alpha), ngCordova fails to load.

```
[$injector:modulerr] Failed to instantiate module ngCordova due to:
[$injector:modulerr] Failed to instantiate module ngCordova.plugins due to:
[$injector:modulerr] Failed to instantiate module ngCordovaOauth due to:
[$injector:nomod] Module 'ngCordovaOauth' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

**Comment by gortok** [comment]
Looks like the oAuth submodule is in a broken state. @nraboy?

**Comment by mhartington** [comment]
Might be worth ditching the submodule and either 
A) Pulling ngCordovaOauth in officially
B) Take ngCordovaOauth out of ng-cordova proper and make it's module

Not a fan of git submodules TBH. 
cc @nraboy

**Comment by gortok** [comment]
At this time, install0.1.17, I'm not near a PC; but if you remove the oAuth module, you'll also be Ok.

**Comment by nraboy** [comment]
All the haters here with submodules.  Pretty sure it broke because one of the pull requests made some changes that shouldn't have been made.

I will look into it, but in the end one of two things could happen:

1. I fix the submodule in ngCordova
2. I drop support for ngCordova and people use strictly ngCordovaOauth

I tried playing the maintain two repositories game and it didn't work.  I would like ngCordovaOauth to remain its own entity.

I'll keep you posted.

cc @gortok @mhartington

**Comment by nraboy** [comment]
So it appears gulp-git is asynchronous so it was building the library before the submodule finished downloading.  It worked the first time for me since the submodule had already downloaded before I pushed.

I am working on a fix.

I apologize for wrongfully accusing a bad merge.

**Comment by mhartington** [comment]
We all make mistakes :grin: 

What you could do instead of running gulp-git inline, is this

```
gulp.task('git', function(){
git.updateSubmodule({ args: '--init --remote' });
}

gulp.task('build', ['git'], function () {
```

This will call git before performing the build task.

**Comment by nraboy** [comment]
No bueno.  The submodule doesn't finish downloading before the build:

```
macbookpro:ng-cordova nraboy$ gulp
[19:23:14] Using gulpfile ~/Desktop/ng-cordova/gulpfile.js
[19:23:14] Starting 'prepare'...
[19:23:14] Finished 'prepare' after 5.08 ms
[19:23:14] Starting 'build'...
[19:23:16] Finished 'build' after 1.73 s
[19:23:16] Starting 'default'...
[19:23:16] Finished 'default' after 9 μs
[19:23:16] Submodule 'src/plugins/oauth' (https://github.com/nraboy/ng-cordova-oauth) registered for path 'src/plugins/oauth'
Submodule path 'src/plugins/oauth': checked out '8cf594947cd8aa52ae64be2ff9f234b85f127293'
 Cloning into 'src/plugins/oauth'...
```

**Comment by nraboy** [comment]
Should be fixed now:

https://github.com/driftyco/ng-cordova/pull/909

**Comment by mhartington** [comment]
Looks good, @nraboy thanks. 

Will do a release in the AM.
