### ISSUE TITLE
[Bug] ngCordovaOauth not packaged with the others on `ngCordova`

### ISSUE THREAD

**Issue by matheusrocha89** [driftyco/ng-cordova#912]
The new release `0.1.18-alpha` does not packaged within the `ngCordovaOauth` code, I believe it was because of the submodule, maybe I guess it is because the `ngCordova` build process was not configure to download submodules.

**Comment by matheusrocha89** [comment]
Oh, I saw here that @nraboy already fix that, I guess on the next release will be fix.

**Comment by gortok** [comment]
fixed with tag v0.1.19-alpha.
