### ISSUE TITLE
Renaming to factory '$cordovaMedia2' in media.js causes issues when trying to inject $cordovaMedia

### ISSUE THREAD

**Issue by leschirmeur** [driftyco/ng-cordova#920]
It seems that the $cordovaMedia factory in the Media plugin (media.js) has been renamed to $cordovaMedia2. This is causing issues when injecting $cordovaMedia. A bower install ngCordova installs version 0.1.19-alpha in which the factory has been renamed. This renaming is not present in version 0.1.17-alpha.

**Comment by gortok** [comment]
Yea; it appears this change was made in PR #871;  Errgh.
