### ISSUE TITLE
build(npm): Please release the new version to npm

### ISSUE THREAD

**Issue by leon** [driftyco/ng-cordova#929]

**Comment by gortok** [comment]
I've been added to the npm deploy; I'll push one out today.

**Comment by gortok** [comment]
I'll issue a release to npm once the PR #932 is done on Travis-CI.  It'll be a new release.

**Comment by gortok** [comment]
Done. v0.1.20-alpha is on npm and bower.

**Comment by leon** [comment]
@gortok Awesome!
