### ISSUE TITLE
Camera not sending updated URI

### ISSUE THREAD

**Issue by Duovili** [driftyco/ng-cordova#946]
I keep getting this issue where the camera is returning the same data URI regardless of the pic.

**Comment by gortok** [comment]
Can you provide a sample repo that reproduces this issue?

**Comment by Duovili** [comment]
I know what the data URI is and I have gone through my code and its no where there is like its cached is there a way to clear data?

**Comment by gortok** [comment]
It's hard to help you without you providing me with a sample repo I can use to look through this problem with you. Without that it's just me guessing at possibilities.

**Comment by Duovili** [comment]
I george sorry I only have my local version how can I send you that? Below is tge data URI i keep getting. I have done a clean install and still getting this error. I need  to launch last week so any help would be appreciated.

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCADhAZADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDx

**Comment by gortok** [comment]
I'd put the code used to do this on github in a minimal example so I can build and run it on my own device; and then I can see what you're seeing and see if it's a problem in Code.  You can also try running the Cordova plugin directly without the ngCordova extensions to see if it's an ngCordova bug or a cordova plugin bug.

**Comment by Duovili** [comment]
below is the code I am using. and i am using the ng cordova plugin. I am running an alert before I touch the code and the data is already edited there. I have tested this on multiple devices and its still showing. I dont know where this could be getting set.

var options = {
                                quality: 50,
                                destinationType: Camera.DestinationType.DATA_URL,
                                sourceType: Camera.PictureSourceType.CAMERA,
                                allowEdit: true,
                                encodingType: Camera.EncodingType.JPEG,
                                targetWidth: 400,
                                targetHeight: 400,
                                popoverOptions: CameraPopoverOptions,
                                saveToPhotoAlbum: false
                            };
                            $ionicPlatform.ready(function () 
                            {
                                $cordovaCamera.getPicture(options).then(function (imageData) {
                                    alert(imageData);
                                    $scope.user.userDetails.imagePath = "data:image/jpeg;base64," + imageData;
                                    var result = userSrvc.updateProfileImage($scope.user.userDetails);
                                    result.success(function ()
                                    {
                                          
                                    });
                                    result.error(function ()
                                    {
                                        var Popup = $ionicPopup.alert({
                                            title: 'Error!',
                                            template: 'Oops somethign went wrong.'
                                        });
                                    });

                                }, function (err) {
                                    var Popup = $ionicPopup.alert({
                                        title: 'Error!',
                                        template: err
                                    });
                                });
                            });

**Comment by Duovili** [comment]
I finally solved this by doing a clean install and reinstalling the plugin

**Comment by gortok** [comment]
I'm glad this was solved.  I know it seems painful; but there are so many  moving parts that a problem can be caused by half a dozen things;  asking for a clean repo helps ensure that we're not chasing ghosts.
