### ISSUE TITLE
Cannot Unit Test Angular Factory if $cordovaCalendar is injected n.plugins.calendar undefined

### ISSUE THREAD

**Issue by rlrhett** [driftyco/ng-cordova#952]
I need to test a service that depends on $cordovaCalendar.  I understand that using Karma to run tests in the browser I cannot actually test a non-existant calendar.  That's OK.  I just want to unit test other methods on my Factory.  In fact, I'm only using the findAllEventsInNamedCalendar method. What I need to do is mock out $cordovaCalendar to send Karma some pre-defined mock events.

I can't get past the angular.mocks.injector instantiating the factory so that I can mock the data. Even though I am NOT testing any method that calls $cordovaCalendar, and even though Karma will not load custom Factory dependencies, it STILL throws an error that n.plugins.calendar is undefined.  Any other dependency of my factory would remain undefined, but for some reason with $cordovaCalendar it all grinds to a halt at that error.

I am finding that I literally have to delete $cordovaCalendar from the list of injected services AND delete or comment out any method that has $cordovaCalendar before Karma will even get past the mock.inject phase.  This is a major pain and prone to introducing errors.

Am I missing something obvious?  How do I get past the instantiation of the factory so that I can stub out $cordovaCalendar.findAllEventsInNamedCalendar()?

Simplified example:

```coffeescript

angular.module "test", ['ngCordova']
.factory 'GetEvents', ->
  return {
    readDevice: ->
      events = $cordovaCalendar.findAllEventsInNamedCalendar()
      return events
    manipulateSomeHow: (events) ->
      . . . 
  }
```
```coffeescript

describe 'GetEvents factory', ->
  beforeEach ->
    module 'test'
    inject (_GetEvents_) ->
      GetEvents = _GetEvents_
      GetEvents.readDevice = sinon.stub().returns {one:1, two:2}
  it 'exists', ->
    GetEvents.should.exist
```
```
FAILED TESTS:
  GetEvents factory
    ✖ "before each" hook
      PhantomJS 1.9.8 (Mac OS X 0.0.0)
    the object {
      "line": 60336
      "message": "'undefined' is not an object (evaluating 'n.plugins.calendar')"
      "name": "TypeError"
```

**Comment by Ionitron** [comment]
Greetings @rlrhett!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
