### ISSUE TITLE
$cordovaFacebook invalid key hash

### ISSUE THREAD

**Issue by marcussaad** [driftyco/ng-cordova#954]
So, I'm implementing facebook auth and managed to get it working on Genymotion and android's emulator.

Code for reference:
```
$cordovaFacebook.login(['public_profile', 'email', 'user_friends'])
        .then(function(success) {
        	$scope.fbCredentials = {
        		'accessToken' : success.authResponse.accessToken,
        		'sessionKey' : success.authResponse.session_key,
        		'status' : success.authResponse.status
         	};
         	$state.go('timeline');
        }, function(error) {
      		$scope.fbCredentials = null;
        });
```
When deploying to my device, I'm getting 
```Invalid key hash. The key hash <key_here> does not match any stored key hashes```. The point is, this key being mentioned by this error message is far from being close to the one I've generated and have set on the developers.facebook.com page. 

Am I supposed to add this key hash to the ones accepted? (Where does this key hash gets pulled from?)

**Comment by marcussaad** [comment]
Right. Figured it out finally.

For those who may run into this issue in the future, on linux and mac this key hash will be pulled from
```bash
~/.android/debug.keystore
```
In order to find out what the hash key will be, you may use
```bash
keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64
```
Then proceed to developers.facebook.com, select your app, include Android as platform, and include the value given by the previous command in the 'Key Hashes' input. 

You're good to go!

(/may be closed).

**Comment by gortok** [comment]
Thanks; this is really helpful. would you consider putting this into docs form and adding it to the plugin wrapper docs for the Facebook plugin?

**Comment by marcussaad** [comment]
@gortok Yes, of course. Can you point me to docs repo? The second one you refer is https://github.com/Wizcorp/phonegap-facebook-plugin/blob/master/platforms/android/README.md ?
