### ISSUE TITLE
releases doesn't mention 0.20.

### ISSUE THREAD

**Issue by ptarjan** [driftyco/ng-cordova#966]
https://github.com/driftyco/ng-cordova/releases

**Comment by gortok** [comment]
Nice catch. I hadn't checked there. ::sheepish grin::.

**Comment by ptarjan** [comment]
I found it by viewing https://github.com/driftyco/ng-cordova/blob/master/CHANGELOG.md

If that is the wrong place to look for what is new in 0.20 please point it at the right place.

**Comment by gortok** [comment]
@ptarjan That's the right place; I hadn't been using the release function; I should have been.  For 0.1.21-alpha I'll make sure to use that functionality. Sorry about that.

**Comment by ptarjan** [comment]
@gortok no problem, I just like changelogs when updating
